### ISSUE TITLE
StringUtil.php + Notification center

### ISSUE THREAD

**Issue by Alibi-Contao** [terminal42/contao-notification_center#101]
Habe im Notification center folgenden Code für die Email-Ausgabe eingegeben:

    {if form_rueckruf=="ja"}
    Weitere Mitteilungen:a
    {elseif form_aussendienst=="ja"}
    Weitere Mitteilungen:b
    {elseif form_angebot=="ja"}
    Weitere Mitteilungen:c
    {endif}

    {if form_rueckruf=="ja"}

        Um Rückruf wird gebeten. {endif} {if form_aussendienst=="ja"}
        Ein Außendienst-Besuch ist gewünscht. {endif} {if form_angebot=="ja"}
        Bitte schicken Sie mir ein Angebot. {endif}

Die Buchstaben a, b und c hinter "Weitere Mitteilungen:" dienen nur zur Kontrolle, welche Zeile in die Email verwendet wurde.
Ziel:
Wenn eine der Checkboxen aktivert wurde, soll die Zeile "Weitere Mitteilungen:" (und darunter die entsprechenden Texte) in die Email geschrieben werden.
Mit der "StringUtil.php" aus Contao 3.5.15 hat alles funkioniert, mit der Fassung aus Contao 3.5.16 leider nicht mehr.
Wenn man unter 3.5.16 die erste und die letzte Checkbox aktiviert, bekommt man das:
Weitere Mitteilungen:a
Weitere Mitteilungen:c
    Um Rückruf wird gebeten.
    Bitte schicken Sie mir ein Angebot.

Also zweimal "Weitere Mitteilungen:"
Siehe auch hier: https://community.contao.org/de/showthread.php?63978-Frage-zum-Notification-center

**Comment by Toflar** [comment]
Das wäre ja dann ein Contao Core Bug, nicht ein Bug im NC?

**Comment by Toflar** [comment]
@ausi hat der neue Parser ein Problem mit `elseif`?

**Comment by Alibi-Contao** [comment]
Contao Core Bug hatte ich auch gedacht. Siehe hier:
https://github.com/contao/core/issues/8491
