### ISSUE TITLE
Semicolons from form input are passed through into CSV files

### ISSUE THREAD

**Issue by Loilo** [terminal42/contao-notification_center#102]
This is an inconvenience for developers as we need to rip those out of POST data manually as well as a potential security issue.
I'd be glad to do a pull request to fix this.

**Comment by Toflar** [comment]
Can you explain this a bit more?

> I'd be glad to do a pull request to fix this.

Sure! Maybe the code explains the issue already ;)

**Comment by Loilo** [comment]
I'm not sure anymore if that's actually an issue since user's do define the structure of their CSVs theirselves.
I just realized there's no sane way to escape the CSV separating character in e.g. `##form_*##`. Maybe there should be a way to define characters that should be escaped but I'm not really sure how since CSV is merely a standardized format...

**Comment by Toflar** [comment]
Yeah, never understood why there are options to use e.g. `;` as delimiter. CSV is very much standardized and there's no need for anything different than that. Closing then?

**Comment by Loilo** [comment]
I think so. Escaping such characters could then be done on a per-project-basis with #105.
