### ISSUE TITLE
Hooks are not compatible with PHP 7

### ISSUE THREAD

**Issue by Loilo** [terminal42/contao-notification_center#103]
[Calling hooks](https://github.com/terminal42/contao-notification_center/blob/00c83f4a0c0df8ea537656e236ec8c51e29cdbc2/library/NotificationCenter/Model/Message.php#L46) is not respecting the PHP 7 changes to evaluation order.
I'll attach a PR in a moment. :)

**Comment by aschempp** [comment]
Closed in favor of #104
