### ISSUE TITLE
Feature request: Add a hook to to modify tokens

### ISSUE THREAD

**Issue by Loilo** [terminal42/contao-notification_center#105]
I came up with the need to modify tokens of certain notifications.
That's generally possible with the `sendNotificationMessage` hook when taking the the tokens by reference.
Problem is that if you actually change the tokens then they'll be changed for every process of the notification (e.g. email and CSV export of the same form) even if you only want to change it for one of them.

I suggest a new hook (for example call it `mapNotificationTokens`) that provides the same data as the `sendNotificationMessage` but takes back a new set of tokens. This would be pretty useful.

I've implemented this feature already in a fork of the notification center so I'd be glad to start a pull request to possibly put this feature into the extension repository.

**Comment by Toflar** [comment]
> I've implemented this feature already in a fork of the notification center so I'd be glad to start a pull request to possibly put this feature into the extension repository.

Feel free to submit a PR! This will ensure the hook is at exactly the place you need it :)

**Comment by Loilo** [comment]
I'll attach one soon™
