### ISSUE TITLE
Feature Request: Send queue immdetiately

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-notification_center#107]
Hello,

it would be awesome to have a button in the queue view in the backend to send the queue immdetiately. Currently when testing always waiting for the queue being sent or navigating to system/cron/cron.php every time is a bit inconvenient.

Would that be possible with little effort?

**Comment by Toflar** [comment]
Should be possible, yes. But it would require an interface so you can e.g. choose to send only the stuff from queue 1 or queue 2 etc.

**Comment by Toflar** [comment]
Closing this. Need some cleanup here.
