### ISSUE TITLE
Add an opportunity to prevent image embedding in HTML emails

### ISSUE THREAD

**Issue by Loilo** [terminal42/contao-notification_center#108]
**The scenario:**

A customer wants to send notification emails with an HTML and a plain text version. They want to use images in the HTML version.

**The problem:**

The images are embedded into the email source code. That's a problem for several email clients (Thunderbird, Outlook, ...) which cannot display the regular plain text version if embedded images are present and rather will create their own "plain text" version from the HTML version.

Contao's `Email` class embeds images into the email source code by default. This behaviour is controlled by the `$blnEmbedImages` property but the notification center does not offer an interface to access that property (as opposed to, for example, Contao's newsletter module which has a checkbox dedicated to that).

**The solution:**

The notification center should offer such an interface, probably in the form of just an additional checkbox that is shown when you choose to send an HTML email.

What do you think?
I'd be happy to attach a PR.

**Comment by Toflar** [comment]
Cool, PR's are most welcome!

**Comment by Loilo** [comment]
We'd use a forked version of the notification center anyway, might as well give the implemented feature back to you guys. Extensions from extension repository are most welcome for customers since they're updateable. 😉

**Comment by Loilo** [comment]
PR attached at #109. 🎉

**Comment by Toflar** [comment]
Closing in favor of https://github.com/terminal42/contao-notification_center/pull/109 then.
