### ISSUE TITLE
Allow ##formconfig_recipient## for various fields

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-notification_center#112]
Please allow the token ##formconfig_recipient## for

- recipients
- email_recipient_cc
- email_recipient_bcc
- email_replyTo
- email_sender_address

The field "recipient" in form config will always include an Email-address, otherwise I can't save the field.

**Comment by Toflar** [comment]
Added/Fixed in 5e029f07ee23e203311b8adc1d3b3ec256a5538d and published as 1.3.9.

**Comment by frontendschlampe** [comment]
sänk ju
