### ISSUE TITLE
Push-Benachrichtigung als Gateway?

### ISSUE THREAD

**Issue by ngdot** [terminal42/contao-notification_center#113]
Hallo, wie wäre es, wenn man eine Push-Benachrichtigung auf sein Handy bekommt, wenn ein Formular übertragen wird? Ich persönliche würde diese Funktion super finden :) Ein Dienst mit dem das möglich sein sollte, wäre [Pushbullet](https://pushbullet.com/) ([DOCS](https://docs.pushbullet.com/)). Ich nutze diesen Dienst bereits mit UpTimeRobot und bin sehr zufrieden.

**Comment by Toflar** [comment]
Klar, alles was eine API hat lässt sich anbinden :-) Pull Requests sind willkommen.

**Comment by hermannbrauer** [comment]
@NicolasGoerlach 

hast du dir das schon angeschaut?

[https://packagist.org/packages/richardhj/contao-notification_center_clockworksms](https://packagist.org/packages/richardhj/contao-notification_center_clockworksms)

**Comment by NicolasGoerlach** [comment]
@hermannbrauer Nein noch nicht, werde ich für das nächste Projekt sicher mal testen :) Danke für den Tipp!
