### ISSUE TITLE
Error "Allowed memory size" wenn Token in HTML nicht aufgelöst werden kann

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-notification_center#114]
NC 1.3.9 Referenz: f79f2922
C 3.5.19

Wenn in der HTML-E-Mail ein Token vorhanden ist, was nicht aufgelöst werden kann, kommt es zu

```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 73479 bytes) in /../system/modules/core/library/Contao/StringUtil.php on line 504
```

im Textfeld ist das kein Problem...

**Comment by Toflar** [comment]
Ist "haste" auf dem neusten Stand?

**Comment by zonky2** [comment]
codefog/contao-haste 	4.12.0

**Comment by aschempp** [comment]
Please update to the latest version and see if the issue still exists.

**Comment by zonky2** [comment]
I´ll check this at next night...

**Comment by aschempp** [comment]
Closing, I assume this has been fixed with latest Contao and Haste versions.
