### ISSUE TITLE
File Uploads: notification email contains path only

### ISSUE THREAD

**Issue by eBlick** [terminal42/contao-notification_center#115]
I used the simple token ##form_upload1## to have the uploaded file attached to the notification email. The email contains the path to the file only.
Contao 3.5.21
cnc 1.3.8

**Comment by Toflar** [comment]
And where does it contain the path? I mean the e-mail? Did you enter it in the text??

**Comment by eBlick** [comment]
Yes indeed.

I entered the token as usual in the text and rte-editor.
The output in the notification email:
[cid:A0D224DE-0895-4050-871D-B1DE567BE272@fritz.box]

**Comment by Toflar** [comment]
Yeah so it's correct? If you want to output it in the text then it is shown there? If you want to attach it you enter the token in the field "attachment tokens".

**Comment by eBlick** [comment]
ough, stupid. Sorry,  I tumbled again over the wrong description at this field (kommaseparierte Liste der EMPFÄNGER)...
please close 
![bildschirmfoto 2017-01-23 um 13 50 06](https://cloud.githubusercontent.com/assets/6641281/22204573/ee33c342-e172-11e6-8429-21bab846a13b.png)

**Comment by Toflar** [comment]
That's likely a wrong translation on transifex :)
