### ISSUE TITLE
keine mail an Admin bei Registrierung ?

### ISSUE THREAD

**Issue by sfx12** [terminal42/contao-notification_center#117]
Hallo,

habe glaube ich einen Bug entdeckt: wenn man beim Registrierungsmodul eine Benachrichtigung aus dem notification-Center wählt, bekommt der admin keine email, dass sich ein neues Mitglied registriert hat.

Hab alles erdenklich Mögliche probiert. Egal ob bei "Benachrichtigung" oder "Aktivierungsbenachrichtigung" 
sobald da was gewählt wird, kommt keine mail über "Neuregistrierung"
![unbenannt-1](https://cloud.githubusercontent.com/assets/16244014/22610033/cb3c047c-ea63-11e6-9b82-6b66991c72af.jpg)
 an den Admin mehr.

Contao Version: 3.5.17 
Notofication center Ver. 1.4.0

**Comment by Toflar** [comment]
Steht was in den Logs?

* Systemlog
* `system/logs/error.log`
* `system/logs/email.log`

**Comment by sfx12** [comment]
in email.log steht nur das mail gesendet wurde (die an das registrierte mitglied) in der error.log steht nichts.. bzw. nichts , wenn ich es teste. wie gesagt.. sobald eine Benachrichtigung gewählt wird, kommt keine mail an admin "neuer user registriert..." man benötigt logischerweise jedoch beides !

**Comment by Toflar** [comment]
Das ist richtig und gewollt so. Die Benachrichtigung an den Admin stellst du ja dann auch im Notification Center ein. Es macht keinen Sinn für die eine Nachricht das NC zu verwenden und für die andere die Standard-E-Mail, die sich nicht übersetzen lässt. Einfach eine 2. Nachricht in die Benachrichtigung einfügen und sie so konfigurieren, wie der Admin es eben möchte.

**Comment by sfx12** [comment]
Aber das ist doch auch genau der Punkt.. siehe ersten Post "Screenshot"....auch wenn ich die Aktivierungsbenachrichtigung wähle... kommt nur die Benachrichtigung (links) an das Mitglied an !!!

**Comment by Toflar** [comment]
Das eine ist bei Registrierung. Das andere bei der Aktivierung. Das sind zwei unterschiedliche Vorgänge. Ich verstehe das Problem nicht.

**Comment by sfx12** [comment]
Ok, jetzt hab ich es verstanden, man kann ja bei Benachrichtigungsmail" mehere Nachrichten innerhalb davon erstellen. und rechts kommt dann die mail wenn ich den user "manuell" aktiviert habe.. richtig ?! Danke.

**Comment by Toflar** [comment]
Auch wenn der User sich selbst aktiviert durch das Token in der Mail. Einfach halt wenn er aktiviert wird :D

**Comment by sfx12** [comment]
Ok Super, Danke
