### ISSUE TITLE
member id token und andere felder aus tl_member in reg:mail

### ISSUE THREAD

**Issue by sfx12** [terminal42/contao-notification_center#118]
Hallo,

in der mail vom Registrierungs Benachrichtigung, funktioniert das Feld bzw. der simple token ##member_id## nicht ?

Zudem, lassen sich auch keine tokens aus anderen Feldern wie z.b xt_member einsetzen ? die in tl_member gespeichert sind in der DB ! was muss man tun, damit auch XT member tokens in der email funktionieren ?

Danke schon mal

**Comment by Toflar** [comment]
Hmm, das liegt wohl leider daran, dass der Hook nicht alle Daten mitliefert.
Kannst du mal https://github.com/terminal42/contao-notification_center/commit/5c27e512c9740321c78c9633cb2ec1b8f4d0da61 versuchen?

**Comment by sfx12** [comment]
Cool, jetzt funktioniert zumindest die Übergabe vom "xt_feld" aber die member id wird leider noch nicht übergeben mit ##member_id## :-(

**Comment by sfx12** [comment]
??

**Comment by aschempp** [comment]
I cannot reproduce the missing data, it should be present with @Toflar's patch. Fixed in version 1.4.1
