### ISSUE TITLE
Error in Notifications > Language

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-notification_center#119]
Please change the code for "Send a CC to" and "Send a BCC to":

**Before**
`<div class="w50" style="height:auto widget">`

**After**
`<div class="w50 widget" style="height:auto">`

![error](https://cloud.githubusercontent.com/assets/1942550/22793079/0ce2258e-eeef-11e6-90d6-9c8fe98e8da6.png)

**Comment by cliffparnitzky** [comment]
Seems the `style` attribute in the eval array is set twice:

https://github.com/terminal42/contao-notification_center/blob/master/dca/tl_nc_language.php#L218
https://github.com/terminal42/contao-notification_center/blob/master/dca/tl_nc_language.php#L230

The question ist, which `height` is the right one?

**Comment by aschempp** [comment]
I've changed the input fields to `text` instead of `testarea` in 40a979c4e054cce43c96c069524b32e516f8365b, that should fix the problem.
