### ISSUE TITLE
Cannot trigger queue with Contao 4

### ISSUE THREAD

**Issue by sleitz** [terminal42/contao-notification_center#120]
Executing the queue binary (manually or via cronjob) in Contao 4 results in this:

    $> ./vendor/terminal42/notification_center/bin/queue 
    PHP Warning:  require_once(/…/vendor/terminal42/notification_center/bin/../../../../../system/initialize.php): failed to open stream: No such file or directory in /…/vendor/terminal42/notification_center/bin/queue on line 20
    PHP Fatal error:  require_once(): Failed opening required '/…/vendor/terminal42/notification_center/bin/../../../../../system/initialize.php' (include_path='.:/opt/remi/php70/root/usr/share/pear:/opt/remi/php70/root/usr/share/php:/usr/share/pear:/usr/share/php') in /…/vendor/terminal42/notification_center/bin/queue on line 20

**Comment by Toflar** [comment]
Should work when you run it via `system/modules/notification_center/bin` no?

**Comment by sleitz** [comment]
Same error, unfortunately.

**Comment by aschempp** [comment]
Fixed in b273583368482531b21b51e7aef5487b8290270f
