### ISSUE TITLE
contao/standard-edition 4.3.7 -> Kein Sprachen-Menü bei den Benachrichtigungen

### ISSUE THREAD

**Issue by chuckki** [terminal42/contao-notification_center#121]
Hallo,

ich habe via ```composer require terminal42/notification_center``` zur aktuellen standard-edition probiert das Notification Center zu installieren. 
AppKernel.php wurde aktualisiert - ebenso Datenbank via /contao/install.

Sieht alles soweit super aus, jedoch werden mir beim Anlegen der Benachrichtigungen kein "Sprachen"-Menü angezeigt (siehe Screen):
<img width="896" alt="bildschirmfoto 2017-04-11 um 11 35 04" src="https://cloud.githubusercontent.com/assets/1282645/24902698/45618756-1eab-11e7-893a-34aa4be75d5c.png">

Der AJAX Request beim Öffnen des Menü-Punktes gibt mir ein 204 Status zurück. 

Testweise habe ich dies einmal mit einer komplett cleanen standadard-editon replizieren können. Weiterhin habe ich es mit der managed-edition probiert - dort funktioniert alles.

**Comment by Toflar** [comment]
Ich denke das liegt daran, dass die Symlinks zurzeit nicht korrekt angelegt werden. Siehe https://github.com/contao/core-bundle/issues/751 für Details und Lösungsmöglichkeiten.

**Comment by aschempp** [comment]
In der Standard Edition musst du die entsprechenden Abhängigkeiten (in diesem Fall z.B. `multicolumnwizard`) auch im AppKernel aktivieren.

**Comment by chuckki** [comment]
Alles klar - es lag an den Abhängigkeiten.
Vielen Dank!
