### ISSUE TITLE
"Send a CC to" & "Send a BCC to" visual bug in contao4

### ISSUE THREAD

**Issue by NicolasGoerlach** [terminal42/contao-notification_center#122]
![bildschirmfoto 2017-05-27 um 00 24 04](https://cloud.githubusercontent.com/assets/8327905/26514551/cf72ed32-4272-11e7-9082-8ebcbea6cf8b.png)

**Comment by Toflar** [comment]
See https://github.com/contao/core-bundle/issues/827
