### ISSUE TITLE
"Raw text" & "HTML"

### ISSUE THREAD

**Issue by NicolasGoerlach** [terminal42/contao-notification_center#123]
width should be 100%, just add class "long" to "widget".
![bildschirmfoto 2017-05-27 um 00 26 15](https://cloud.githubusercontent.com/assets/8327905/26514610/1d94d80e-4273-11e7-8ac1-d9f6f83b6793.png)

**Comment by Toflar** [comment]
I guess that's a Contao 4 issue. See https://github.com/contao/core-bundle/issues/827
