### ISSUE TITLE
Consider the `defaultFileChmod` and `defaultFolderChmod` configuration settings

### ISSUE THREAD

**Issue by xchs** [terminal42/contao-notification_center#126]
When it comes to deliver a notification through a "**Write to file**" gateway, it would be nice if we could consider the [`defaultFileChmod`](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/config/default.php#L122) and [`defaultFolderChmod`](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/config/default.php#L123) configuration settings in the [`saveToLocal`](https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/Gateway/File.php#L158-L195) and [`saveToFTP`](https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/Gateway/File.php#L197-L258) methods, respectively (see e.g. https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/FileUpload.php#L172).

**Comment by aschempp** [comment]
Fixed in d92c1a5

**Comment by xchs** [comment]
Thanks a lot!
