### ISSUE TITLE
host said 553 5.7.1: Sender address rejected: not logged in

### ISSUE THREAD

**Issue by hermannbrauer** [terminal42/contao-notification_center#128]
Hallo Ihr, 
ich versuche über das Notification_Center Meldungen abzusetzen, nur bleiben die beim empfangenden Mail-Server hängen mit der Begründung das Absender nicht angemeldet ist. So ich das denn richtig interpretiere...

```
<empfänger@domain.tld>: host fqnd[ipv4] said: 553
    5.7.1 <sender@domain.tld>: Sender address rejected: not logged in
    (in reply to RCPT TO command)
```

Wenn ich jetzt meinem Postfix sage schau nicht nach:

reject_authenticated_sender_login_mismatch und reject_sender_login_mismatch

gehen die Mails "sauber" durch.

Ist es möglich, dass der Login für den SMTP nicht wirklich genutzt wird? 
Ist jetzt Contao 4.4 jedoch unter Contao 3.5.x hat der Versand mit den identischen Zugangsdaten noch funktioniert

Wie schon geschrieben, bei "kastriertem" Postfix läuft es...

**Comment by aschempp** [comment]
Der Email Versand in Contao 4 hat sich grundlegend geändert, die Zugangsdaten werden vermutlich ignoriert :(

**Comment by hermannbrauer** [comment]
habt Ihr da ne Chance das "kurzfristig" zu fixen? Ich kann mir vorstellen, dass Ihr gerade größere Baustellen habt wie den Mail-Versand...

**Comment by aschempp** [comment]
see https://github.com/contao/core-bundle/pull/943

**Comment by hermannbrauer** [comment]
Hallo @aschempp 

ist es möglich das der Fehler mit dem Versand der E-Mail vom Notification Center noch vorhanden ist? Ich hatte das so verstanden, dass dieser Fehler in der 4.4.1 beseitigt sein sollte, kannst du hierzu evtl. etwas sagen?

Gruß und vielen Dank
Hermann

**Comment by aschempp** [comment]
dieses Ticket ist noch offen, entsprechend wurde das noch nicht korrigiert.

**Comment by qzminski** [comment]
Fixed in dedf902.
