### ISSUE TITLE
Schließen-Button im PopUp Benachrichtigungen->Nachrichten->Sprachen optisch deaktiviert

### ISSUE THREAD

**Issue by mpitz** [terminal42/contao-notification_center#129]
Der Schließen-Button unten ist optisch deaktiviert/ausgegraut und ein Verbotssysmbol erscheint beim Hover:

Contao 4.4.0, Notification Center 1.4.1

![image](https://user-images.githubusercontent.com/6831223/27736853-319fff06-5da6-11e7-9f7e-806622bcd08e.png)

**Comment by cliffparnitzky** [comment]
Kann ich bestätigen

**Comment by Toflar** [comment]
Das ist ein Contao Core Bug. Sollte eigentlich bereits behoben sein, aber da ist was beim Mergen schief gegangen, siehe auch https://github.com/contao/core-bundle/issues/990

**Comment by fritzmg** [comment]
I though this is related to https://github.com/terminal42/contao-dcawizard/issues/19 ?
(See also https://github.com/isotope/core/issues/1819)

**Comment by Toflar** [comment]
No, it has to be fixed in core :)
