### ISSUE TITLE
Formular ID is shown even if backend user has no permissions

### ISSUE THREAD

**Issue by mpitz** [terminal42/contao-notification_center#131]
The form ID is shown in the navigation if backend user has no permission for the form:

![image](https://user-images.githubusercontent.com/6831223/29662583-1fc1eda6-88c8-11e7-87fe-f4cd6f893af5.png)

**Comment by mpitz** [comment]
maybe it is a issue for leads?

**Comment by aschempp** [comment]
then you should probably not create it here 😉
