### ISSUE TITLE
Formular is selectable even if backend user has no permissions

### ISSUE THREAD

**Issue by mpitz** [terminal42/contao-notification_center#132]
In this example the backend user has no permissions to the Formular "Kartenbestellungen (Backup-Formular)" but can select it in "Hauptkonfiguration"

![image](https://user-images.githubusercontent.com/6831223/29662706-9fb5fb56-88c8-11e7-9e47-e340c0f4148b.png)

**Comment by mpitz** [comment]
maybe it is an issue for leads?

**Comment by aschempp** [comment]
then you should probably not create it here 😉
