### ISSUE TITLE
Token-Popup broken

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-notification_center#134]
Hello,

since Contao 4.4.5 (I guess at least), the little window that pops up after typing "##" in one of a notification language's fields is broken. JavaScript errors are thrown directly after opening a language in modal (so I guess the fact that the token window doesn't work anymore is just a symptom):

> hover.js:2 Uncaught TypeError: Cannot read property 'getElement' of null
>     at Object.setupProfileToggle (hover.js:2)
>     at hover.js:2
>     at mootools.min.js:3
>     at Array.forEach (<anonymous>)
>     at Function.forEach (mootools.min.js:2)
>     at Array.each (mootools.min.js:2)
>     at fireEvent (mootools.min.js:3)
>     at HTMLDocument.h (mootools.min.js:4)
> setupProfileToggle @ hover.js:2
> (anonymous) @ hover.js:2
> (anonymous) @ mootools.min.js:3
> (anonymous) @ mootools.min.js:2
> each @ mootools.min.js:2
> fireEvent @ mootools.min.js:3
> h @ mootools.min.js:4

**Comment by Toflar** [comment]
I guess that's the same issue as mentioned here and thus a core issue: https://github.com/contao/core-bundle/issues/1093
