### ISSUE TITLE
notification on manual activation by admin

### ISSUE THREAD

**Issue by rustykowski** [terminal42/contao-notification_center#135]
Ich möchte, dass neu registrierte Mitglieder manuell im Backend durch einen Admin aktiviert werden. Kann ich automatisch eine notification an das neue Mitglied senden, um ihm mitzuteilen, dass sein Account nun aktiviert wurde?
Mein Eindruck ist, das Aktivierungsbenachrichtigungen nur verschickt werden, wenn das Mitglied sich per E-Mail Opt-in selbst aktiviert.

**Comment by Toflar** [comment]
Das ist korrekt, das wird momentan nicht unterstützt. Einfach nur eine Benachrichtigung schicken sobald "Login erlauben" aktiviert wurde, geht sowieso nicht. Ein Admin kann diese Checkbox ja beliebig oft umschalten, man müsste sich also merken, ob bereits jemals eine Bestätigung verschickt wurde.

**Comment by cliffparnitzky** [comment]
Das geht damit: https://github.com/menatwork-ia/registration_info_mailer ... ABER: wie @Toflar schon erklärt hat, gemerkt wird sich da nix. Die Aktivierungsmail kann mehrfach gesendet werden.

**Comment by rustykowski** [comment]
Danke für eure superschnellen Antworten!

**Comment by Toflar** [comment]
Ich schliesse das Ticket, da es bereits Lösungen gibt. Wenn Interesse daran besteht, das in den Core des NC aufzunehmen, bitte PR stellen :)

**Comment by hermannbrauer** [comment]
Hey, 

das Funktioniert, wir setzen das ohne weitere Plugins ein....

1. Mail an Kunden - Ihr Account wird manuell aktiviert
2. Mail an Backoffice - Account prüfen und Freischalten
   - hier liefere ich dem Backoffice den Aktivierungslink für das Konto

wenn Backoffice den Account freigeschaltet hat erfolgen 
1. Mail an Kunde - Ihr Account ist aktiviert
2. Mail an Backoffice - Account wurde aktiviert

**Comment by rustykowski** [comment]
> Mail an Backoffice - Account prüfen und Freischalten
hier liefere ich dem Backoffice den Aktivierungslink für das Konto

Gute Idee, danke!
