### ISSUE TITLE
Implement a "Dry Run" interface?

### ISSUE THREAD

**Issue by richardhj** [terminal42/contao-notification_center#136]
I was wondering what you guys are thinking about implementing this interface (https://github.com/richardhj/contao-notification_center_checksendinterface) to the extension.

## Why did I created this interface?
I made this extension: https://github.com/richardhj/contao-notification_center_member_selectable
For me it is a pretty useful extension. Users can opt-in and opt-out different messages (like E-Mail, SMS).
The Problem I came up: When the user decides to opt-out E-Mail and opt-in SMS exclusively, I have had to check whether a mobile number is given at the user account, which is not naturally.

So, when a gateway implements this interface, the gateway implements a `canSendDraft()` method. This method returns true "if a mobile number is given and valid" (to keep using the example).

## Links
A gateway implementing the interface: https://github.com/richardhj/contao-notification_center_clockworksms
Implementation gateway: https://github.com/richardhj/contao-notification_center_clockworksms/blob/master/src/NotificationCenter/Gateway/ClockworkSms.php#L159-L187

So, Implementing the Interface or not?

**Comment by Toflar** [comment]
Why would that method be named `canSendDraft()`? I mean what does "draft" have to do there? :) A `canSendMessage(Message $message)` sounds more logical to me or did I miss anything?

**Comment by richardhj** [comment]
Yep, right. Actually it is a "dummy draft". And actually, we're not sending the message, we're just checking the preconditions (e.g. recipients are not empty).
The method can be `canSendMessage(Message $message)` or `checkPreconditions(Message $message)` or `doDryRunOnMessage(Message $message)` :-)

To check that the interface addresses the problem right, you can implement the method to a Gateway you already created using [this as an example](https://github.com/richardhj/contao-notification_center_clockworksms/blob/master/src/NotificationCenter/Gateway/ClockworkSms.php#L159-L187).

And to mention it: This Feature Request ist **not urgent** at all :-)

**Comment by Toflar** [comment]
Sounds fine to me, feel free to create a PR :)

**Comment by richardhj** [comment]
Ok, count on me in 2018 😄

**Comment by zonky2** [comment]
> Ok, count on me in 2018

@richardhj ... which month? :smiley_cat:

**Comment by Tastaturberuf** [comment]
Haha its 2020 now ;-)
