### ISSUE TITLE
Contao 4.4 NC 1.4.1 No Token ToolTipp available

### ISSUE THREAD

**Issue by eBlick** [terminal42/contao-notification_center#137]
Editing a notification now opens a new popup window.

The Tooltipps when entering '#' are no longer available.
Is this a bug or intentional?
I find them useful.
![bildschirmfoto 2017-11-15 um 09 44 50](https://user-images.githubusercontent.com/6641281/32826806-1d47bbce-c9ea-11e7-81c7-2a86606758db.png)

**Comment by Toflar** [comment]
This is a bug but I cannot reproduce it. What does the JS console say? What browser are you using? What exact version of Contao?

**Comment by eBlick** [comment]
Contao 4.4.5, Chrome Version 61.0.3163.100 (Offizieller Build) (64-Bit)

hover.js:2 Uncaught TypeError: Cannot read property 'getElement' of null
    at Object.setupProfileToggle (hover.js:2)
    at hover.js:2
    at mootools.min.js:3
    at Array.forEach (<anonymous>)
    at Function.forEach (mootools.min.js:2)
    at Array.each (mootools.min.js:2)
    at fireEvent (mootools.min.js:3)
    at HTMLDocument.h (mootools.min.js:4)
﻿

​

**Comment by Toflar** [comment]
Does not sound like this is related to NC. I guess you have a general JS error in the back end which breaks all JS on the website. Try updating to the latest version.

**Comment by eBlick** [comment]
This solved it! THX
