### ISSUE TITLE
Notification Center 220 but got code

### ISSUE THREAD

**Issue by redwise** [terminal42/contao-notification_center#140]
Hallo Ihr Lieben, 

leider versuche ich schon seit 8 Stunden das Notification Center in Betrieb zu bekommen, leider vergebens.

Das Forum samt Lösungsansätze habe ich bereits gelesen und getestet, ebenfalls das Video von Yannik habe ich gesehen.

Komponenten Contao Version 4.5.2 notification_center Version 1.4.2 Ohne den Einsatz des Notification Center funktioniert der Versand des Formulars.

Nur eben mit kommt nichts an. 

Folgendes steht im System-Log:

[2018-01-20 20:54] Form "Rückrufformular" has been submitted by 87.172.4.0.
ID:	16
Datum:	2018-01-20 20:54
Ursprung:	Frontend
Kategorie:	FORMS
Benutzer:	anon.
Details:	Form "Rückrufformular" has been submitted by 87.172.4.0.
Funktion:	Contao\Form:rocessFormData

[2018-01-20 20:54] Could not send email for message ID 7: Expected response code 220 but got code "", with message ""
ID:	15
Datum:	2018-01-20 20:54
Ursprung:	Frontend
Kategorie:	ERROR
Benutzer:	anon.
Details:	Could not send email for message ID 7: Expected response code 220 but got code "", with message ""
Funktion:	NotificationCenter\Gateway\Email::send

Wen. ich die entsprechenden SMTP Einstellungen vornehme sehe folgende Meldung in den Logs

[2018-01-20 21:22:29] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMe thodException(code: 0): Attempted to call an undefined method named "newInstance" of class "Swift_SmtpTransport". at /staktffm/www.domain.de/contao/vendor/terminal42/notification_center/library/NotificationCenter/Gateway/Email.php:73)"} []

Leider komme ich als nicht Programmierer nicht zurecht.

Hättet Ihr einen Hinweis?

Vielen Dank für Eure Hilfe vorab..

Post auch im Forum:
https://community.contao.org/de/showthread.php?69465-Notification-Center-220-but-got-code&p=462245#post462245

Steffen

**Comment by aschempp** [comment]
Ich vermute Contao 4.5 funktioniert aktuell nicht mit eigenen SMTP-Verteilern weil SwiftMailer aktualisiert wurde.

**Comment by redwise** [comment]
Hallo Andreas, das gleiche Verhalten ist auch bei der Version 4.4.12. Sobald ich das Center wieder entferne funktioniert der Mailversand.

**Comment by Toflar** [comment]
Imho this is an incompatibility with the latest swiftmailer version 6. See https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/Gateway/Email.php#L73

@qzminski you introduced that version 4 compatiblity, can you check that it's also compatible with swiftmailer 6, please? :)

**Comment by redwise** [comment]
In der Testumgebung 
Version 4.4.12
Swift-5.4.8
bekomme ich keine Funktion.

Danke!!

**Comment by qzminski** [comment]
Fixed in 8061d3f. @terminal42/pilots I am not sure about the implementation though, maybe it would be better if we somehow check the Swiftmailer version?

**Comment by Toflar** [comment]
Yeah that fix is not correct I guess. What about `method_exists()` on `newInstance`?

**Comment by qzminski** [comment]
@Toflar good idea, changed in 4886fb0.

**Comment by Toflar** [comment]
@redwise can you check if the hotfix branch fixes your issue? You can just require the hotfix branch and tell composer to act as if this was already released as 1.4.3:

```
"terminal42/notificaton_center": "dev-hotfix/1.4.3 as 1.4.3"
```

I will release it as soon as you confirm :)

**Comment by redwise** [comment]
Hallo Yanick, das kann ich gern machen, nur wie auf die Version 1.4.3 heben. Aktuell ist die Version 1.4.2 (6.11.2017, 13:07:13) aktiv.

**Comment by Toflar** [comment]
Das hab ich doch oben beschrieben?

**Comment by redwise** [comment]
@Toflar ich vermute mal per Terminal? Sorry für die blöde Frage.

**Comment by redwise** [comment]
@Toflar verstanden... teste es

**Comment by redwise** [comment]
@Toflar so... in der aktuellen Version 4.4.2 finktioniert die "terminal42/notificaton_center": "dev-hotfix/1.4.3 as 1.4.3" ohne Fehler.

in der Version 4.5.2 mit der 1.4.3 

ID: | 24
-- | --
Datum: | 2018-01-23 11:49
Ursprung: | Frontend
Kategorie: | ERROR
Benutzer: | anon.
Details: | Form "Rückrufformular" could not be sent: Expected response code 220 but got code "", with message ""
Funktion: | Contao\Form::processFormData

**Comment by Toflar** [comment]
Aber keine Exception mehr, richtig?

**Comment by redwise** [comment]
@Toflar in Contao Version 4.4.2 funktioniert jezt alle wie es soll in der 4.5 keine Veränderung.

**Comment by redwise** [comment]
@Toflar wenn man das Formular über das Contao eigene sendet dann tritt die Fehlermeldung vom Center mit auf. Es kommt aber auf der Mail nichts an.

ID: | 37
-- | --
Datum: | 2018-01-23 12:18
Ursprung: | Frontend
Kategorie: | FORMS
Benutzer: | anon.
Details: | Form "Rückrufformular" has been submitted by 87.172.11.0.
Funktion: | Contao\Form::processFormData


ID: | 36
-- | --
Datum: | 2018-01-23 12:18
Ursprung: | Frontend
Kategorie: | ERROR
Benutzer: | anon.
Details: | Form "Rückrufformular" could not be sent: Expected response code 220 but got code "", with message ""
Funktion: | Contao\Form::processFormData

**Comment by redwise** [comment]
@Toflar zur Info, folgenden Test habe ich vorgenommen

Eine Contao 4.4.12 mit den Noti Center dev-hotfix/1.4.3 as 1.4.3 wo der Mailversand funktioniert auf die 4.5.3 geupt.

Dann nochmal der Test, leider gehen keine Mails raus Error 220.

Dann zurück auf die 4.4.12, das deinige was war ist, dass die

Spalten ändern
--
  | Alle auswählen
  | DROP INDEX path ON tl_files
Spalten anlegen
  | Alle auswählen
  | CREATE INDEX path ON tl_files (   path(333) )

im Install Tool hängen...

Danach den Mailversand getestet und dieser funktioniert wieder.

Hoffe, diese Erkenntnis hilft irgendwie.

**Comment by Toflar** [comment]
Sorry, im Moment habe ich keine Zeit mir das näher anzusehen, es läuft alles problemlos mit der 4.5 hier. Funktioniert es, wenn du im Email-Gateway die SMTP-Einstellungen selber eingibst?
Funktionieren denn normale Contao-Mails?

**Comment by redwise** [comment]
ok, habe eine ganz saubere Installation neue 4.5 getestet und die vorhandene due von 4.4 auf die 4.5 gehoben wurde. Zugänge kommen per Mail.

Danke

**Comment by redwise** [comment]
Danke nochmals für den Klasse Support!!!

**Comment by Toflar** [comment]
Alles klar, ist jetzt offiziell released, du kannst also den Constraint auf `^1.4.3` anpassen um die nächsten Updates automatisch zu kriegen.
