### ISSUE TITLE
There is no model method 'findByType()' 

### ISSUE THREAD

**Issue by tsarma** [terminal42/contao-notification_center#141]
```php
$objNotificationCollection = NotificationCenter\Model\Notification::findByType($strType);
```
This don't return any model or collection.
From Documentation: https://github.com/terminal42/contao-notification_center#sending-a-notification

**Comment by Toflar** [comment]
It does, because Contao maps unkown methods to columns.

**Comment by qzminski** [comment]
https://github.com/contao/core/blob/3.5/system/modules/core/library/Contao/Model.php#L1004

**Comment by tsarma** [comment]
Thanks, it does. My mistake
