### ISSUE TITLE
Backend spelling mistake - Label CC-Empfänger

### ISSUE THREAD

**Issue by tschero** [terminal42/contao-notification_center#145]
Hi,

while declaring an new Notification the Label "CC-Empfänger" has an spelling mistake.

`Emptänger die eine Kopie des Mails erhalten sollten. Mehrere Adressen per Komma separieren.`

Greetz

**Comment by aschempp** [comment]
Should be fixed in 7ea95f3678aba52adf00318302a226c397f08e02
