### ISSUE TITLE
Passwort vergessen: ##firstname## ##lastname##

### ISSUE THREAD

**Issue by sgei** [terminal42/contao-notification_center#147]
Hallo,

in dem normalen Modul für "Passwort vergessen" kann man im Text eine persönliche Anrede mittels ##firstname## ##lastname## machen.
Im Notification Center sind diese Simple Tokens allerdings nicht zulässig.

Könnt ihr die mit einbauen?

Steffen

**Comment by Toflar** [comment]
Die sollten da sein? `member_*` ist da m.M.n. vorhanden?

**Comment by sgei** [comment]
Hallo,

ja - sind da.
Ich hatte es mit ##firstname## anstatt ##member_firstname## probiert.

Danke.

Kann geschlossen werden.
