### ISSUE TITLE
Send notification for newsletters

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-notification_center#150]
Would be cool to send notifications instead of the plain email for the Contao newsletter modules (registration and unregistration)

**Comment by bezin** [comment]
Hi there, 

I just though of that the other day as well. As far as I see things this would require some changes to the [newsletter bundle](https://github.com/contao/newsletter-bundle): 

# Subscribe
Right now, the activation email is hardcoded into [ModuleSubscription](https://github.com/contao/newsletter-bundle/blob/master/src/Resources/contao/modules/ModuleSubscribe.php#L344-L357). This must be [made optional as in ModuleRegistration](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/ModuleRegistration.php#L383-L387). Maybe inform the site admin if no mail was sent like in [ModuleRegistration](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/ModuleRegistration.php#L445-L449). 

Aditionally, we would need to add an **addRecipient** hook to capture that event and send the activation message ourself.

Same goes for **activateRecipient** i.e. after a user clicked the confirmation link. There is no email by default in this case yet but that might be handy and desirable. The [registration module](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/ModuleRegistration.php#L542-L549) already works like this. 

# Unsubscribe
The **removeRecipient** hook is already present and could be used for that. 

Anything else neccessary?

**Comment by Toflar** [comment]
See https://github.com/terminal42/contao-notification_center/pull/156

**Comment by frontendschlampe** [comment]
I think, you can't close the ticket, because we just add the possibility to send notifications additionally to the standard Contao activation mail. We don't replace it.

**Comment by Toflar** [comment]
It is closed already 😄

**Comment by frontendschlampe** [comment]
I write **can't** ;-)

**Comment by Toflar** [comment]
Ah well, imho that's the same. It's also how it works in other places. You can for example still activate the core feature to send form data via e-mail. The notification is just on top of that.
