### ISSUE TITLE
file upload attachment fails when filename contains white spaces

### ISSUE THREAD

**Issue by ameotoko** [terminal42/contao-notification_center#151]
If a file has spaces in its name, it doesn't get attached to a message. This is because the filename is URL encoded in `$arrTokens` (contains `'%20` instead of whitespaces), and  `is_file()` returns `false` with such a filename in [`NotificationCenter\Util\StringUtil:getTokenAttachments()`](https://github.com/terminal42/contao-notification_center/blob/fc8855cf66e3a8305df9c2938fe0bbc76b26dbb8/library/NotificationCenter/Util/StringUtil.php#L85)

The quick workaround is to use `sendNotificationMessage` hook and `str_replace` every '%20' back to whitespace in tokens, but having a whitespace in a filename is a valid scenario nowadays, so maybe it should be fixed?

**Comment by Toflar** [comment]
Can you provide a PR to fix it please? :)

**Comment by ameotoko** [comment]
I'll try! Never done it before, but always wanted to contribute :)

**Comment by Toflar** [comment]
Ah sorry, I thought because you already debugged it you might know how 😄 But yeah, we all have to start at some point, do it! 😄
