### ISSUE TITLE
Benachrichtigungstyp Aktivierung funktioniert nicht wie erwartet

### ISSUE THREAD

**Issue by bflessa** [terminal42/contao-notification_center#153]
Hallo!

Bin mir nicht sicher ob es ein Bug ist oder ich die Funktion nicht durchschaue. Ich wüsste gerne einmal welche Aktion den Benachrichtigungstyp "Mitglied-Aktivierung" auslöst. Bisher habe ich es nur geschafft das der Link den ich nach der Registrierung zusende diesen Funktion auslöst (in der Mail eingebettet als "##link##".
Ich würde allerdings ungern den Autologin und die eigene Freischaltung durch den User nutzen, sondern gerne die Freischaltung im Backend durch den Admin durchführen lassen. Ablauf wäre dann
1) Registrierung im Frontend
2) User erhält Bestätigungsmail per NC mit Hinweis das der Admin ihn freischaltet und er dann eine Nachricht erhält
3) Admin erhält eine Mail in der er darauf hingewiesen wird das er den User freischalten muss
4) Admin geht ins Backend und schaltet User frei (indem er den User aktiviert und Login erlaubt)
5) Mail geht danach automatisch per NC raus (und genau das passiert nicht wenn man den User im backend manuell freischaltet. Die Mail geht nur raus wenn der Link angeklickt wird (##link##) allerdings ist dann der User nur sichtbar geschaltet aber der Haken bei Login erlauben fehlt ...)

Gibt es da eine Lösung?

**Comment by aschempp** [comment]
Die Benachrichtigung wird nur aus dem entsprechenden Frontend-Modul versendet, nicht aus dem Backend.

**Comment by bflessa** [comment]
OK, ich habe es nun so gelöst das ich dem Admin den Freischalt Link zusende per NC und dem User nur eine Hinweis Mail die ihm mitteilt das sein Account durch den Admin geprüft und freigeschaltet wird. Das ist so eine runde Lösung für alle, Danke für die Rückmeldung - und natürlich für die Erweiterung ;-)
