### ISSUE TITLE
Problems with if/endif simple tokens

### ISSUE THREAD

**Issue by eBlick** [terminal42/contao-notification_center#154]
I don't get any e-mail output when using conditions in nc:

formfield: date_birth

NC Condition: 
{if form_date_birth !=""}
Geburtstag: ##form_date_birth##
{endif}

The email does not contain the data although the date_birth field is filled.

The syntax should be correct when I look at the documentation?!

I have also tried:
{if form_date_birth !=''}
{if form_date_birth !=" "}
{if form_date_birth !=' '}

still no effect... is there any chance to debug this?

**Comment by asaage** [comment]
try without space after .._birth!
```{if form_date_birth!=""}```

or maybe even ```{if form_date_birth}``` though i'm not shure if that works.

https://community.contao.org/de/showthread.php?56835-Fehlermeldung-bei-Simple-Token-und-if-else

**Comment by aschempp** [comment]
This is not a bug or issue of Notification Center, parsing simple tokens is done in Contao core. Please refer to the community forum or the Contao documentation (https://docs.contao.org/books/manual/4.4/en/04-managing-content/newsletters.html#personalized-newsletters)

**Comment by madmaharaja** [comment]
> try without space after .._birth! `{if form_date_birth!=""}`

Yes, thank you -- this syntax did the trick for me --> https://community.contao.org/de/showthread.php?67065-Leads-Notification-Center-Probleme-mit-Ausgabe-Dateiname-von-Anhang&p=557986#post557986
