### ISSUE TITLE
Entering Languages is not possible

### ISSUE THREAD

**Issue by wschwaiger** [terminal42/contao-notification_center#155]
Please find attached. Entering languages under Notifications is not possible. No listing is provided. Contao Version 3.5.36.
![bildschirmfoto 2018-09-25 um 10 29 20](https://user-images.githubusercontent.com/458603/46002255-e3e34e00-c0ad-11e8-91d9-bdd9d6ee885e.png)

![bildschirmfoto 2018-09-25 um 10 26 35](https://user-images.githubusercontent.com/458603/46002193-ac74a180-c0ad-11e8-9dce-94c3b9370fe2.png)
![bildschirmfoto 2018-09-25 um 10 26 46](https://user-images.githubusercontent.com/458603/46002194-ac74a180-c0ad-11e8-9c69-c5af340d8de2.png)

**Comment by aschempp** [comment]
Looks like not all dependencies haven been installed? Please try to repair the extension.

**Comment by wschwaiger** [comment]
Ok. I tried now to reinstall and update the extension. It requests haste 4.17.x but still no effect. Same result. What dependency are you referring to?

**Comment by aschempp** [comment]
dcawizard, but that seems installed 🤔

**Comment by wschwaiger** [comment]
The extension qwat-gks was the reason. uninstalled it and everything is working fine. hmm
