### ISSUE TITLE
Anpassung Übersetzung für Simple Token

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-notification_center#159]
Ihr müsstet bitte mal die deutsche Übersetzung für das Simple Token ```formlabel_*``` anpassen.

Im Deutschen heißt es: _Alle Formularfelder und ihre Labels_ das ist aber falsch, denn es suggeriert, dass die Labels **und** die Werte ausgegeben werden. Richtigerweise sollte es aber heißen: _Label des jeweiligen Formularfeldes_

Für ```form_*``` sollte _Inhalt des jeweiligen Formularfeldes_ und ```raw_data``` sollte _Rohinhalt des Formulars_

**Comment by aschempp** [comment]
Die Übersetzung werden auf Transifex gepflegt, du kannst dich dort gerne als Übersetzer melden 😉 
https://www.transifex.com/terminal42/notification_center/
