### ISSUE TITLE
Verfügbarkeit des letzten Release

### ISSUE THREAD

**Issue by asaage** [terminal42/contao-notification_center#160]
Ich wollte die NewsletterNotifications testen aber ich bekomme kein Update angeboten.
es scheint hier irgendwie noch nicht gelistet zu sein.
https://packagist.org/packages/terminal42/notification_center
```Could not find package terminal42/notification_center in a version matching  1.5.0```

**Comment by Toflar** [comment]
Dürfte daran gelegen haben, dass GitHub gestern einen Totalausfall hatte.
