### ISSUE TITLE
Geschlecht ausgeben

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-notification_center#163]
Hallo,

wenn ich in einer Nachricht `##member_gender##` eintrage, wird das Ganze wie gewünscht ausgegeben.

Wenn ich jetzt aber
`{if ##member_gender##=='male'}Sehr geehrter Herr {endif}{if ##member_gender##=='female'}Sehr geehrte Frau {endif}##member_lastname##,`
in die Nachricht eintrage um die Anrede unterscheiden zu können, wird das Ganze nicht akzeptiert. Die folgende Fehlermeldung wird beim speichern angezeigt:

![grafik](https://user-images.githubusercontent.com/2067428/48204414-0d102300-e36a-11e8-9ca0-b9068db7978d.png)

Hängt das eventuell mit [#49](https://github.com/terminal42/contao-notification_center/issues/49) zusammen?

**Comment by Toflar** [comment]
Nein, in einer `if`-Bedingung musst du keine `##` angeben und `'` sind auch nicht unterstützt.

Richtig wäre:

```
{if member_gender=="male"}Sehr geehrter Herr{endif}{if member_gender=="female"}Sehr geehrte Frau{endif} ##member_lastname##,
```

**Comment by Schmidty2** [comment]
Danke für die Korrektur, funktioniert jetzt wie gewünscht
