### ISSUE TITLE
Exception "Warning: array_merge(): Argument #1 is not an array" in in vendor/terminal42/notification_center/library/NotificationCenter/AutoSuggester.php (line 63)

### ISSUE THREAD

**Issue by arboc** [terminal42/contao-notification_center#164]
**How to reproduce:**

- Open contao backend with **app_dev.php/contao**
- Go to notification center
- Edit a notification
- Edit a message
- Edit a language

**Comment by sgei** [comment]
Same problem...

**Comment by aschempp** [comment]
Closed in favor of https://github.com/terminal42/contao-notification_center/pull/162
