### ISSUE TITLE
Hide notification types if the bundle is not installed

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-notification_center#165]
We should hide the newsletter notification types if the newsletter bundle or extension is not installed.

**Comment by qzminski** [comment]
Fixed in bde7757e977e53d954b022d7b83bc72e14c66315, @aschempp do you mind quickly checking that?

**Comment by aschempp** [comment]
The `ModuleLoader` automatically maps legacy modules, so a `version_compare` seems not necessary.

**Comment by qzminski** [comment]
True but I wanted to avoid the deprecated class call. Shall I change it then?

**Comment by aschempp** [comment]
Yes please. It's a Contao 3 module, so deprecations are fine for me
