### ISSUE TITLE
Mitglieder-Registrierung und Bestätigungsseite

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-notification_center#166]
Wird über Contao bei der Mitglieder-Registrierung eine E-Mail gesendet, ist der Link in der URL auf die Seite der Registrierung - wird aber bei der Option "Bestätigungsseite" eine weitere Seite ausgewählt, wird man automatisch dahin geleitet. Auf der Seite kann z.B. stehen "Registrierung abgeschlossen" + Loginformular.

Die Option "Bestätigungsseite" ist aber nur sichtbar, wenn man die Contao-E-Mail-Versendung anklickt - Contao wertet die Weiterleitung aber dennoch aus, auch wenn die Contao-Checkbox nicht gesetzt ist.

Es wäre prima, wenn beim installierten NC die Auswahl für die Weiterleitungsseite auch zu sehen wäre.

Aktueller Workaround:
* Contao-Checkbox E-Mail setzen
* Weiterleitungsseite auswählen
* Checkbox wieder deaktivieren

**Comment by richardhj** [comment]
Fixed in 8c06fea1f2b3685b773022967dfbd68d851cb985.

**Comment by aschempp** [comment]
@richardhj Ich denke wir sollten bei Auswahl einer Notification per `submitOnChange` die Seite neu laden, und nur dann das entsprechende Feld direkt anzeigen. Das Feld ist sonst Pflicht, wenn man weder Checkbox gesetzt noch Notification gewählt hat?

**Comment by richardhj** [comment]
Es ist kein Pflichtfeld 🤔

https://github.com/contao/contao/blob/e7486e952d0b54843d3a899d872cffa6413de0ee/core-bundle/src/Resources/contao/dca/tl_module.php#L600-L609
