### ISSUE TITLE
##link## token= leer

### ISSUE THREAD

**Issue by thescrat** [terminal42/contao-notification_center#171]
Hi,
nach unzähligen Test lande ich beim NotificationCenter, welches anscheinend ein Problem mit dem optin System von Contao 4.7 hat. 

Leider ist es mir nicht möglich eine Registrierung abzuschließen, da im InsertTag ##link## der Token nicht ersetzt wird. 

Könntet ihr das bitte nochmal prüfen?

**Comment by tinokramm** [comment]
Zwar ist mein Problem etwas anders gelagert, aber ich habe auch Probleme beim Abschließen der Registrierung.

[https://github.com/terminal42/contao-notification_center/issues/172](url)

**Comment by thescrat** [comment]
Das Problem liegt übrigens an dieser Stelle:

https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/ContaoHelper.php#L38

Hier wird der Token aus dem Feld activation gezogen, ohne, dass hier überhaupt etwas drin steht! Keine Unterscheidung zwischen Contao >=4.7 etc.

**Comment by thescrat** [comment]
Das funktioniert aber nicht! Sowohl im Testsystem als auch Produktivsystem!

**Comment by richardhj** [comment]
Warum nicht?

**Comment by thescrat** [comment]
Weil der Fix irgendwie nicht richtig über den Composer geladen wurde. Erst nach der vollständigen Deinstallation und erneuten Installation gehts. Jetzt klappt steht auch was hinter dem Token :-)
