### ISSUE TITLE
Newsletter Abo-Aktivierung klappt nicht

### ISSUE THREAD

**Issue by tinokramm** [terminal42/contao-notification_center#172]
Hallo!

Ich beiße mir die Zähne aus. Wie bekommt man mit dem NotificationCenter die Newsletter Anmeldung UND Aktivierung hin? Das NC verschickt zwar fleißig E-Mails nach Anmeldung sowie auch Aktivierung, aber der Abonnent wird im Newsletter Verteiler nicht aktiviert. Das NC erkennt nach Klick auf den Aktivierungslink in der Mail eine Aktivierung und gibt auch positives Feedback im Frontend. Im Backend wird im Newsletter Modul ein neuer Abonnent angelegt, aber nicht aktiviert.

Umgebung:
Contao 4.4.36
NotificationCenter 1.5.3 (1.5.4 ging auch nicht)
Contao newsletter-bundle

Mache ich etwas falsch oder könnte es ein Bug sein? Ich kann nirgendwo eine Anleitung finden, um mein Modul-Setup zu kontrollieren.

Beste Grüße

Tino

PS: Mit den Contao-eigenen Modulen klappt die Aktivierung reibungslos.

**Comment by richardhj** [comment]
Ich hab das gerade getestet. Bin zwar auf Contao 4.7, aber das sollte keinen Unterschied machen.
hast du die beiden Module *Aktivierung* und *Anmeldung* auf die gleiche Seite gepackt?

**Comment by tinokramm** [comment]
Ja. Ich habe verschiedenen Varianten durchgespielt. Aktuell habe ich Anmeldung und Aktivierung auf der selben Seite.

**Comment by frontendschlampe** [comment]
Ich habe mit Contao 3.5 und NC 1.5.4 das selbe Problem

**Comment by frontendschlampe** [comment]
mit der Version 1.5.2 funktioniert die Aktivierung

**Comment by frontendschlampe** [comment]
bei mir funktioniert es auch mit der 1.5.3

**Comment by tinokramm** [comment]
Nach dem Update auf NC 1.5.5 funktioniert es nun bei mir. Tausend Dank für die schnelle Reaktion.
