### ISSUE TITLE
Contao 4.4: Newsletter-Activation does not work

### ISSUE THREAD

**Issue by danielwolf1** [terminal42/contao-notification_center#174]
Hi, thanks for that wonderful module.

We found the following bug: In Contao 4.4, it's not possible to activate a newsletter subscription due to the following bug in **ModuleNewsletterActivateNotification.php. Line 120**:

The $objRecipient is found by a token and is a ModelCollectionReader. Thus, there is only one item in this list. So **$objRecipient->next() returns always false** and the recipient is not activated.

Could you fix this, please? For example by just removing this while-loop as there should be only one recipient found given a token.

           while ($objRecipient->next()) {
                /** @var NewsletterChannelModel $objChannel */
                $objChannel = $objRecipient->getRelated('pid');

                $arrAdd[] = $objRecipient->id;
                $arrCids[] = $objChannel->id;

                $objRecipient->active = 1;
                $objRecipient->token = '';
                $objRecipient->pid = $objChannel->id;
                $objRecipient->confirmed = $time;
                $objRecipient->save();
            }

**Comment by richardhj** [comment]
Actually, this is the same behavior as in Contao Core. https://github.com/contao/contao/blob/4.4/newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php#L189
I will have a look

**Comment by danielwolf1** [comment]
Yes, but in Contao Core, the is no access to the object before calling next() - in your module, the email property is read, thus the internal index is not -1 but 0, it points to the first object already.

Thus, I would recommend to remove the while loop or call $objRecipient->reset() just before the while loop.

**Comment by richardhj** [comment]
You‘re on the latest version? I already fixed this.

**Comment by danielwolf1** [comment]
You are right - the old version was cached...sorry.
