### ISSUE TITLE
Feature Request: Hook in sendFormNotification

### ISSUE THREAD

**Issue by danielwolf1** [terminal42/contao-notification_center#175]
Hi, would it be possible to add a Hook in https://github.com/terminal42/contao-notification_center/blob/5823680ca06626dba3081fa34ce5ce3c83f2f856/classes/tl_form.php#L63 in order to check if notification sending was successfull?

This way, we handle errors, if the mail server is not available at the moment.

**Comment by Toflar** [comment]
That would be the wrong place for a hook. This would be only for forms sent via form generator and not for all notifications. Moreover, it's a gateway specific thing anyway: An email must be handled differently from some API etc. so I'm not sure we can currently implement that. The architecture of the extension is too messed up (aka old :-)).
I think it would be best for you to just register your own gateway type. You can then extend the existing `Email` gateway and override whatever you need and handle errors the way you like 😊

**Comment by danielwolf1** [comment]
Thanks for that hint. I close this ticket...

**Comment by bezin** [comment]
You could have a look at our Slack Gateway: 

[Gateway class](https://github.com/presprog/contao-slack-notification/blob/develop/src/Gateway/Slack.php)

[Add fields for that gateway](https://github.com/presprog/contao-slack-notification/blob/develop/src/Resources/contao/dca/tl_nc_gateway.php)

[Register the new gateway](https://github.com/presprog/contao-slack-notification/blob/develop/src/Resources/contao/config/config.php#L3)
