### ISSUE TITLE
Token collision

### ISSUE THREAD

**Issue by asaage** [terminal42/contao-notification_center#176]
I can't have the newsletter-activation module and the register-member module on the same page because they compete for the ```token``` parameter.
If i try to activate a membership the newsletter-activation kicks in and tells me that an newsletter-subscription was activated (which is not intended and not true) an the member-register module tells me the token has already been confirmed (~the member-activation is successful~* - just don' get the correct output in the FE).
Can you make the newsletter-activation only to use tokens starting with ```nl-``` and ignore ```reg-``` tokens or do i have to split this into different pages/layouts?

*the member-activation is **not** successful

**Comment by asaage** [comment]
If i change the order of the modules (NL-Activation at the bottom) everything works.
I will fix the rest with css and maybe js. Feel free to close this.

**Comment by asaage** [comment]
The module still reacts on other token (namely now the ```pw-``` token in my case) and renders an empty  ```<div class="mod_newsletterActivateNotificationCenter">``` It would be nice if it just was not there.
Can you reopen or is it another issue?

**Comment by richardhj** [comment]
We need to extend the condition in https://github.com/terminal42/contao-notification_center/blob/95f5308f9d15835baeb5c58eea4e529eb09e97c6/modules/ModuleNewsletterActivateNotificationCenter.php#L46
But tbh I don't think we need to add further complexity to the module.
