### ISSUE TITLE
Newletter Abo-Aktivierung bei mehreren Archiven klappt nur beim ersten Verteiler

### ISSUE THREAD

**Issue by Kahmoon** [terminal42/contao-notification_center#177]
Hallo zusammen,

ich habe auch ein Problem bei der Aktivierung von Newsletter Abonneten. Bei einem Archiv (alphabetisch das Erste) klappt es einwandfrei (#172), allerdings aktiviert er bei mehreren Newsletter Verteilern den Benutzer nur im Ersten. Beim zweiten Archiv wird er zwar angelegt, ist aber inaktiv.

Die Abmeldung aus zwei Verteilern gleichzeitig klappt problemlos. Hier wird die Adresse aus beiden Verteilern entfernt.

Hatte hier schon ein Thread im Forum aufgemacht aber es handelt sich ja um Module des Notification Centers https://community.contao.org/de/showthread.php?75324-Aktivierung-bei-mehreren-Verteilern&p=506448#post506448

VG Frank

**Comment by richardhj** [comment]
Hi @Kahmoon,
deine Contao-Version?

**Comment by Kahmoon** [comment]
Sorry!

Contao Version 4.7.6
NC Version 1.5.6

**Comment by richardhj** [comment]
Kannst du den Branch hotfix/1.5.7 installieren (weißt du, wie das geht) und mir sagen, ob das Problem damit gelöst ist?

**Comment by Kahmoon** [comment]
Ich weiss leider nicht genau wie das geht. Kannst mir aber kurz ne PN mit einer Kurzanleitung schreiben.

Einfach die Version im Paketmanager eintragen hat nicht funktioniert.

**Comment by richardhj** [comment]
Da wo du die Version eintragen kannst bitte "dev-hotfix/1.5.7 as 1.5.7" eintragen.

**Comment by Kahmoon** [comment]
Mit dem Hotfix funktioniert es.
