### ISSUE TITLE
Queue gets blocked instead of changing the status of a single e-mail to error

### ISSUE THREAD

**Issue by rorych** [terminal42/contao-notification_center#180]
If we add an e-mail to the queue with a "bad" (does not comply with RFC 2822) address, this results in an error in the log:
```
app.CRITICAL: An exception occurred. {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [##form_email##] does not comply with RFC 2822, 3.6.2. at /home/public_html/contao4-managed/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:345)"} []
```
But the e-mail in the queue does not change the status to "error", it is still "queued".
That means, all future mails never get processed - even if there address would is ok.

We tested this in the "reply-to" field, but i assume it also happens with the sender, to, cc, bcc, etc. fields

Is it possible, that you could check the address and if it is not ok or catch the error that lands in the log and change the status to "error" so the queue doesn't get blocked by a single message?

**Comment by richardhj** [comment]
This issue is related to the reply-to field and not exclusive for emails in a queue.
Fixed in ca1eb42c64d39d245b72f3da0bc7d93f4444ebe0.
