### ISSUE TITLE
Support for InsertTags in attachment tokens

### ISSUE THREAD

**Issue by loilo** [terminal42/contao-notification_center#181]
The attachment token field can currently contain plain file paths as well as simple tokens. I think it would be feasible to support InsertTags in there as well.

My concrete use case is this:

For a customer, I modified Contao's upload form field to take multiple files (via the [`multiple`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-multiple) attribute). It required some fiddling with the `storeFormData` hook, but it works well.

Unfortunately I cannot represent those multiple files through `##form_*##` simple tokens. However, it would be rather easy to implement an InsertTag that resolves to a comma-separated list of file paths.

In general, InsertTags in the token attachments field would provide a little more room for custom logic when it comes to attachments.

What do you think? If you'd approve of the feature, I'd be happy to attach a PR.

**Comment by Toflar** [comment]
The idea is the other way around. Make your user use something like `{{foobar::##form_*##}}`.
That's why we have loads of insert tags included in haste: https://github.com/codefog/contao-haste/blob/master/docs/Util/InsertTags.md

**Comment by loilo** [comment]
Exactly, that's how I'd like it to work. However, the notification center will not replace any InsertTags used inside the `attachment_tokens` field.

**Comment by Toflar** [comment]
Ah, you mean we can probably just use `\Haste\Util\StringUtil::recursiveReplaceTokensAndTags` here: https://github.com/terminal42/contao-notification_center/blob/d20dfdd5ddb409bc8ff606bca62babbeb5076148/library/NotificationCenter/Util/StringUtil.php#L76-L80

**Comment by loilo** [comment]
Exactly.

**Comment by Toflar** [comment]
Okay, feel free to send in a PR then :)

**Comment by loilo** [comment]
Well that's gonna be a simple one I guess. 😁
