### ISSUE TITLE
email priority

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-notification_center#185]
the setting of e-mail priority has been removed in 2016, because allegedly a gradation of e-mails takes place in the spam filters - see https://github.com/contao/core/issues/8298

According to PHPmailer, this should only be done if the priority is set to 3 (normal) https://github.com/PHPMailer/PHPMailer/issues/449

Now the question is, should the Contao core be clean again?

https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Email.php#L455-L459

```diff
        // Set the return path (see #5004)
        $this->objMessage->setReturnPath($this->strSender);
+
+        // Set priority
+        if ($this->priority !== 3) {
+            $this->objMessage->setPriority($this->priority);
+        }

        // Send the e-mail
        $intSent = $this->objMailer->send($this->objMessage, $this->arrFailures);

``` 

or the NC removes the setting?

**Comment by richardhj** [comment]
IMHO this ticket belongs to contao/core.
Whether Contao should re-add priority setting.
If core members vote against re-adding email priority, we need to remove the corresponding settings in NC.
However, any change will not take place prior to Contao 4.9.

WDYT @terminal42/pilots ?

**Comment by zonky2** [comment]
I add a issue... https://github.com/contao/contao/issues/608
