### ISSUE TITLE
FR: "Anzeigen ab / Anzeigen bis" für Nachrichten

### ISSUE THREAD

**Issue by xchs** [terminal42/contao-notification_center#186]
Wäre es eventuell möglich, das Standard-Contao-Feature "_Anzeigen ab / Anzeigen bis_" auch für einzelne Nachrichten des Notification Centers verfügbar zu machen? So könnte man Benachrichtigungen zeitgesteuert veröffentlichen.

**Comment by Toflar** [comment]
This will be possible in [version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277). I'm closing it because I need to keep track for myself somehow. Once there is a public beta, I'd appreciate some testing :)

**Comment by xchs** [comment]
Great. Thanks a lot.
