### ISSUE TITLE
FR: Token for all fields with content

### ISSUE THREAD

**Issue by ngdot** [terminal42/contao-notification_center#187]
It would be nice to have a new token that returns only filled in form fields. Like the standard function of the contao form "Skip empty fields". ##raw_data## currently returns all fields, filled or not filled.

**Comment by mecintosch** [comment]
Die Auflistung mit ##raw_data## wird bei vielen Feldern schnell unübersichtlich. Wenn sich dann die Formulare auch noch laufend ändern wird es kompliziert wenn für jedes Feld eine Abfrage eingebaut werden muss. 

Würde mich über so ein Feature freuen.

**Comment by aschempp** [comment]
Das hört sich für mich nach einer relativ einfachen Funktion an, die jemand per Pull Request contributen könnte? 🙃

**Comment by contaoacademy** [comment]
+1

**Comment by aschempp** [comment]
closed in favour of https://github.com/terminal42/contao-notification_center/pull/231
