### ISSUE TITLE
setLoadAfter vom Notification Center in Contao4-Bundle

### ISSUE THREAD

**Issue by srhinow** [terminal42/contao-notification_center#188]
In meinem Contao4-Bundle benötige ich das NotificationCenter welches zuvor geladen werden muss. Denn ich erstelle ein type welches dann ja vom NotificationCenter überschrieben wird wenn es erst später als mein Bundle geladen wird. Normalerweise macht man das ja in der Plugin.php mit 

->setLoadAfter([NotificationCenter::class])

Aber das geht ja so nicht da das notification_center noch mit alter Contao3 -Logik in system/modules und autoload.ini arbeitet. Wie mach ich das in diesem Fall?

**Comment by Toflar** [comment]
`setLoadAfter('notification_center')`
