### ISSUE TITLE
Extract notifcations so that grouping is optional

### ISSUE THREAD

**Issue by Toflar** [terminal42/contao-notification_center#19]
Rework the grouping of notifications so that it's not necessary to have "groups":
- Notifications
- Notification Packages
- Gateways

**Comment by Defcon0** [comment]
Totally :+1:

**Comment by Defcon0** [comment]
Any news here? Will there be such a feature in near future?

**Comment by Toflar** [comment]
No.

**Comment by Defcon0** [comment]
OK :-(
