### ISSUE TITLE
add editAll at queue to delete multiple or all

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-notification_center#191]
add editAll at queue to delete multiple or all

**Comment by Kahmoon** [comment]
Ahh i did not see this ticket and opened the same request...but this is from Sept/2019. So this change/enhancement seems to be very unlikely :-(

https://github.com/terminal42/contao-notification_center/issues/228

**Comment by zonky2** [comment]
I think implementation becomes more likely when
a) someone submits a PR or
b) someone makes a bank transfer

;-)

**Comment by Tastaturberuf** [comment]
I would prefer something like a cronjob that deletes all entries older than 14 days or something.

**Comment by Kahmoon** [comment]
Both would be good. Lately my db backup gets really big and i wondered why....it was the table nc_queue wich became 300+ MB. Actually the only way to fix this is to truncate the table directly in phpmyadmin :-(

**Comment by Tastaturberuf** [comment]
As a warkround you can make our own cronjob in \App

https://docs.contao.org/dev/framework/cron/

I can't make a PR here for this because the extension is Contao 3 module style and supports no services.

**Comment by zonky2** [comment]
> the extension is Contao 3 module style

oh - I had not thought of that at all

**Comment by zonky2** [comment]
... I could take over the fundraising if someone programmes it (well).

**Comment by Kahmoon** [comment]
> As a warkround you can make our own cronjob in \App
> 
> https://docs.contao.org/dev/framework/cron/


Thats above my skills :-P

**Comment by Kahmoon** [comment]
Any updates from this issue? :-D

**Comment by Toflar** [comment]
This gateway seems to be used extremely rarely. I've used it once in ten years for a project which is when I've contributed it to the core. Ever since, nobody else has been contributing to it. Thus, in [version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277) support for the queue will be dropped for sure.
I need to do some cleanup here.
