### ISSUE TITLE
Multiple BCC E-Mail Notifications not working

### ISSUE THREAD

**Issue by eBlick** [terminal42/contao-notification_center#192]
I have encountered problems with the bcc E-Mails. Only the first E-Mail adress is being notified.
The second, comma-separated adress does not receive a notification.
I am running on Release 1.5.4

**Comment by richardhj** [comment]
What Contao version?
What does the system log say? Should be `An e-mail has been sent to recipient@example.org, BCC to bcc1@example.org, bcc2@example.org`
Did you check your spam filter?

**Comment by richardhj** [comment]
Closing this as I was not able to reproduce it, but feel free to reopen the issue.
