### ISSUE TITLE
Error 500 after login in install tool

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-notification_center#194]
I have a Contao 4.8.4 and installed Contao News and Notification Center 1.5.8 (PHP 7.3, `memory_limit = 256 MB`). After installing the extension I go to the install tool for updating the database. After Login to install tool I get a white screen. I delete `var/cache/*` and now I can login again and I see the DB-updates. When I click the button to confirm the updates, it ends in a white screen again. I deinstalled Notifiction Center and it's working without any problems. I installed 8 other extensions (no Notification Center) and it's working. Installing Notification Center ends up in a white screen again. With `APP_ENV=dev` it's working.

I also tried with a fresh and clean Contao installation and it's ended in a white screen, too.

**Comment by frontendschlampe** [comment]
> With `APP_ENV=dev` it's working.

It's not working, I can just see the overview of DB-updates, but when I confirm them, I get I white page again.

**Comment by Toflar** [comment]
Somewhere there seems to be a memory leak. Not sure this is related to NC or NC just raises it to the surface. I'll see if I can reproduce and profile this.

**Comment by Toflar** [comment]
Cannot reproduce.
