### ISSUE TITLE
Simple Token "_" Underscore Problem

### ISSUE THREAD

**Issue by Ainschy** [terminal42/contao-notification_center#195]
Wenn ein Formularfeld einen Underscore enthält wird es bei der Simple Token Verarbeitung in der NC Message nicht ausgegeben. 

Beispiel:
Ausgabe im NC von Feldname: 
checkbox_agb keine Ausgabe von ##form_checkbox_agb##
checkbox-agb Ausgabe mittels ##form_checkbox-agb## funktioniert

Falls sich das funktionell nicht ändern lässt, weil es mehrere Parameter geben kann die mittels "_" erkannt werden müssen, dann wäre ein Hinweis in der Doku / readme sinnvoll.

**Comment by aschempp** [comment]
@richardhj any idea?

**Comment by frontendschlampe** [comment]
also ich nutze immer "_" und habe damit noch nie Probleme gehabt! Ich habe es hier in verschiedenen Contao-Versionen im Einsatz.

**Comment by richardhj** [comment]
Ggf. steht ein `&#95;` statt eines `_` in der DB?

**Comment by richardhj** [comment]
Im Forum ging es um was anderes. Und bei mir klappt es mit Underscore :-)
