### ISSUE TITLE
Inserttag in hidden field not working in notifications subject

### ISSUE THREAD

**Issue by Kahmoon** [terminal42/contao-notification_center#196]
I use hidden fields "referrer" with {{page::title}} to submit the referring page of the form. This works fine in mailbody. In subject it does not work. Subject is "Neue Anfrage von ##form_referrer##"

**Edit:** The problem is not hidden field...its an inserttag as default value. When is use string "test" in hidden field... it is "Neue Anfrage von test"

Contao: 4.8.5
NC: 1.5.8
Leads: 1.4.14

**Comment by richardhj** [comment]
Und welchen `value` hat `<input type="hidden" name="referrer">`?

**Comment by Kahmoon** [comment]
Sorry, ich kann das Problem nicht mehr nachstellen. Es scheint sich irgendwann entweder durch ein Update oder Cache gelöst zu haben.
