### ISSUE TITLE
No html email sent

### ISSUE THREAD

**Issue by codedge** [terminal42/contao-notification_center#197]
Hey guys,

although I set "HTML und Text" and assigned some new template `mail_contactform.html5` the notification center does noth sent any HTML email (text only) and therefore does not pick up the new template.

Despite the email is properly sent, just the template and type is wrong.

I am using Contao 4.8 and the latest version of your extension.

Is there any other option that I am missing?

Best

**Comment by contaoacademy** [comment]
Did you select your new template at message > Expert settings > Template file?

Can you show the content of your new template.

**Comment by codedge** [comment]
That is the selected template file.
![image](https://user-images.githubusercontent.com/4409904/72158089-b6610780-33b9-11ea-969a-7bd445df3fe7.png)

The content in `mail_contactform.html5` looks like this:
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Ihre E-Mail</title>
</head>

<body>
<br>
Sehr geehrte(r) Frau/Herr {{form::name}},<br>

... text...

<br>
Mit freundlichen Grüßen <br>
<br>
Ihre Eingaben: <br>
------------------
<br>
Ihr Betreff: {{form::subject}}<br>
Ihr Name: {{form::name}}<br>
Ihre Telefonnummer: {{form::phone}}<br>
Ihre E-Mail-Adresse: {{form::email}}<br>
Ihre Nachricht: {{form::message}}<br>
<br>

</body>
</html>

```

**Comment by contaoacademy** [comment]
You need to add

`<?= $this->body ?>`

I haven't tested it, but I dont think, that `{{form::fieldname}}` will work.
You have to add your Text to the Message with simple tokens `##form_name##`

I think a better place for help is the forum instead of GitHub.

**Comment by codedge** [comment]
The problem is, that no html content is added to the mail. So regardless what I write as HTML, it is not appearing inside the email.
Everything that is in the „HTML“ field is not applied.

**Comment by contaoacademy** [comment]
Did you add `<?= $this->body ?>`

**Comment by codedge** [comment]
Yes, I did. The template now looks like this:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Ihre E-Mail</title>
</head>

<body>
<br>
Sehr geehrte(r) Frau/Herr {{form::name}},<br>

... text...

<br>
Mit freundlichen Grüßen <br>
<br>
Ihre Eingaben: <br>
------------------
<br>
Ihr Betreff: {{form::subject}}<br>
Ihr Name: {{form::name}}<br>
Ihre Telefonnummer: {{form::phone}}<br>
Ihre E-Mail-Adresse: {{form::email}}<br>
Ihre Nachricht: {{form::message}}<br>
<br>

BEFORE BODY
<?= $this->body ?>
AFTER BODY

</body>
</html>
```

I am sure we have a misunderstanding, because:

1. The template `mail_contactform.html5` is only taken, if an HTML file is sent. As I said, I only receive TEXT emails. No idea why. As you see I configured `HTML und text`. 
2. If the template would be used by Contao and the NC, then at least the text like `BEFORE` or `Mit freundlichen Grüßen` should be in my mail. No it is not.

So the initial question is surely why only a text email is sent, although I configured to use HTML email.

**Comment by codedge** [comment]
It seems, HTML emails are only sent, if the checkbox "Nachricht veröffentlichen" is checked.

<img width="878" alt="grafik" src="https://user-images.githubusercontent.com/4409904/72175100-980c0380-33db-11ea-8c41-c28fc53a7dfd.png">


That solved the problem for me :-)
