### ISSUE TITLE
Do not send form generator email when using nc

### ISSUE THREAD

**Issue by codedge** [terminal42/contao-notification_center#200]
Hi,

When using the notification center, the email entered inside the form generator should not be sent. 

**Email address + template in form generator**
![image](https://user-images.githubusercontent.com/4409904/72255011-ee5c8a80-3605-11ea-9162-27743b46cb9e.png)

**Inconsistencies**
* The email sent to the address of the form generator is a _text email_, although in NC it is set to _HTML_.
* Form generator and NC do not share the same HTML templates. I created a template for NC (`mail_general.html5`) which cannot be used in form generator. At least I cannot select it.
* If I apply all email address inside the NC to a notification, another email is always sent to the one defined in the form generator.
  * addressA + addressB in NC
  * I still need to add an address to the form generator :( 

Is that just a "mis-use" on my side or what do you think?

**Comment by frontendschlampe** [comment]
yes ... it is a "mis-use" on your side. You should configure your notification in the separat menu entry in the left col ... also see https://isotopeecommerce.org/de/handbuch/v/2.6/r/benachrichtigszentrum.html for more information

Use your notification or the build in "Per E-Mail versenden"

**Comment by codedge** [comment]
@frontendschlampe Thanks a lot. Is somehow did not see the checkbox "Per E-Mail versenden". That solves the issue.
