### ISSUE TITLE
Memory leak / Weiße Seite bei multiplen Löschen von Elementen

### ISSUE THREAD

**Issue by chriza** [terminal42/contao-notification_center#206]
Contao 4.9.3
php 7.3
all-inkl premium
php_value memory_limit 2G

Hallo,
ich habe eine frische 4.9.3 Installation. Das Notification Center ist die einzige installierte Extension.
Zum Test habe ich 40 Elemente in Events, oder Nachrichten oder in einem Artikel erzeugt und diese mit "Alle Bearbeiten" versucht zu löschen. Dabei kommt es zu einer weißen Seite und nach Page Reload ist auch ein Großteil der ausgewählten Elemente gelöscht. Dieser Effekt tritt auch beim Löschen von Systemlog-Einträgen auf.

Welche Einstellungen soll ich vornehmen, um diesen Effekt zu vermeiden?
Besten Dank für die Mühen.

**Comment by cliffparnitzky** [comment]
Eigentlich wäre es immer besser ein solche Frage im Contao Community Forum zu stellen: https://community.contao.org/

Dort wird dann immer erstmal gemeinsam der Sachverhalt analysiert. In deinem Fall stellt sich nämlich die Frage, warum das mit dem Notification Center zu tun haben sollte? Geht denn alles einwandfrei, wenn du die Erweiterung deinstallierst?

**Comment by chriza** [comment]
Hallo,
die Löschprozesse laufen ohne Probleme, wenn die Extension nicht installiert ist, bzw. wieder deinstalliert wird.

**Comment by frontendschlampe** [comment]
Ich muss gestehen, ich habe soeben das selbe feststellen müssen, beim Löschen von mehreren Artikeln. Ich habe jetzt mal den RAM erhöht (auf -1) und da endet es dann irgendwann (wahrscheinlich nach irgendeinem Timeout) in einem 500er. Es scheint mir, als hängt das mit dem Verhalten und der weißen Seite im Installtool zusammen bzw. scheint das Verhalten ähnlich zu sein https://github.com/terminal42/contao-notification_center/issues/194. Das haben wir schon mehrfach auf allen möglichen Kanälen diskutiert, aber das Problem noch nicht finden können.

**Comment by frontendschlampe** [comment]
Nachtrag: Nachdem ich den 500er irgendwann bekommen habe und dann nochmal einen Reload gemacht habe bei der weißen Seite, hat das Löschen dann geklappt.

**Comment by richardhj** [comment]
Weiße Seiten hab ich öfters bei All-Inkl., auch bei Projekten ohne NC.
Wenn der Fehler nicht im Scope von Contao geloggt wird, dann müsste doch was in der apache.log oder error.log stehen, nicht?

**Comment by frontendschlampe** [comment]
leider nein ...

**Comment by frontendschlampe** [comment]
@chriza ich habe gerade mal folgendes probiert: Ich habe mal in der Artikelansicht einen Filter auf die Seite gesetzt (also Klick auf den Seitennamen einer Seite), so dass ich nur noch die Artikel der ausgewählten Seite sehe, dann habe ich die 11 Artikel der Seite gelöscht, da hat es dann ohne Probleme und schnell geklappt.

**Comment by chriza** [comment]
Hallo,
der Fehler tritt auch beim Löschen von Einträgen des System-Logs und von Elementen in Nachrichtenkanälen und Kalendern auf.

**Comment by chriza** [comment]
Habe gerade eine Testinstallation bei IONOS erstellt. Der Fehler tritt nicht auf.

**Comment by chriza** [comment]
Ich habe jetzt in der htaccess Datei folgende Variablen verändert:
php_value memory_limit -1
php_value max_execution_time 500
php_value max_input_time -1

Damit kann ich bei all-inkl die gewünschten großen Löschaktionen durchführen.
