### ISSUE TITLE
Mitglieder Namen im Notifikations Center verwenden

### ISSUE THREAD

**Issue by Hanswega** [terminal42/contao-notification_center#207]
Guten Tag erst mal.
Hie im [Contao Forum](https://community.contao.org/de/showthread.php?78017-Pers%C3%B6nliche-Anrede-f%C3%BCr-registrierte-Mitglieder&p=525623#post525623) ist ein Tread in dem die Versuche nachvollziehbar sind eine Nachricht an ein Mitglied mit dem Token ##member_lastname## und ##member_firstname## usw. zu verwenden.
Das NC kennt keine dieser Tokens. Was mache ich da falsch.
Ein Tipp wäre wirklich sehr gut.
Hans
(Nachtrag: Contao: 4.9.3 / Php 7.3)

**Comment by aschempp** [comment]
Ich habe mir das mal im Code angesehen. Die Benachrichtigungen für *PersonalData* erwarten ein `##member_*##` Simple Token. Die vom Listener übertragenen Tokens scheinen aber ohne `member_` Präfix zu sein? @richardhj kannst du dir das vielleicht mal bei Gelegenheit ansehen?

**Comment by Hanswega** [comment]
Hi danke für die Antwort. Dann kann ich ja lange probieren😂 ok dann wird ja bald. Und schön gesund bleiben.

Mit freundlichen Grüßen
Gottfried Weber

05.06.2020 10:45:42 Andreas Schempp <notifications@github.com>:

**Comment by richardhj** [comment]
Hi, ich habe mir das mal angeschaut.

1. die Tokens `##member_xxx##` werden ordnungsgemäß generiert. Auszug der zur Verfügung stehenden Tokens in der Benachrichtigung:

```array(47) { ["member_old_id"]=> string(3) "345" ["member_old_tstamp"]=> string(16) "24.06.2020 13:28" ["member_old_firstname"]=> string(5) "test2" ["member_old_lastname"]=> string(4) "test" ["member_old_company"]=> string(0) "" ["member_old_street"]=> string(0) "" ["member_old_postal"]=> string(0) "" ["member_old_city"]=> string(0) "" ["member_old_country"]=> string(2) "de" ["member_old_phone"]=> string(0) "" ["member_old_mobile"]=> string(0) "" ["member_old_fax"]=> string(0) "" ["member_old_email"]=> string(28) "richard-test@example.me" ["member_old_website"]=> string(0) "" ["member_old_language"]=> string(0) "" ["member_old_groups"]=> string(6) "xx" ["member_old_login"]=> string(2) "ja" ["member_old_username"]=> string(28) "richard-test@example.me" ["member_old_password"]=> string(97) "xx" ["member_old_useTwoFactor"]=> string(0) "" ["member_old_disable"]=> string(4) "nein" ["member_old_dateAdded"]=> string(16) "20.11.2019 11:41" ["member_old_lastLogin"]=> string(16) "01.01.1970 01:00" ["member_old_currentLogin"]=> string(16) "01.01.1970 01:00" ["member_old_locked"]=> string(16) "01.01.1970 01:00" ["member_old_session"]=> string(0) ""["member_old_secret"]=> NULL ["member_old_trustedTokenVersion"]=> string(1) "0" ["member_old_backupCodes"]=> NULL ["member_old_loginAttempts"]=> string(1) "0" ["member_old_hosts"]=> NULL ["member_old_stop"]=> string(0) "" ["member_old_start"]=> string(0) "" ["admin_email"]=> NULL ["domain"]=> string(29) "ferienpass-badoldesloe.de.wip" ["member_firstname"]=> string(5) "test2" ["changed_firstname"]=> string(1) "0" ["member_lastname"]=> string(4) "test" ["changed_lastname"]=> string(1) "0" ["member_phone"]=> string(0) "" ["changed_phone"]=> string(1) "0" ["member_mobile"]=> string(0) "" ["changed_mobile"]=> string(1) "0" ["member_email"]=> string(28) "richard-test@exapmle.me" ["changed_email"]=> string(1) "0" } 
```

2. Laut `config.php` sind die Tokens für die Perosonal-Data-Notification erlaubt: `array('domain', 'member_*', 'member_old_*', 'changed_*', 'admin_email'),`.
Das gilt für `email_text`.

3. Du schreibst, dass das NC meckert, wenn du `member_xx` Tokens verwenden willst. Verwendest du vllt eine andere Notification als E-Mail?

**Comment by richardhj** [comment]
Ich schließe das Ticket aufgrund fehlendenden Feedbacks. Kann gerne wieder geöffnet werden.

**Comment by wedega** [comment]
Hallo Richard,
erst mal Entschuldigung für die Nichtbeachtung der Kommentare.
Ich war 4 Wochen ausser Gefecht und nun wieder aktiv dabei,
Für E-Mail habe ich ##member_email## verwendet.
Heute werde ich das mit den Tolenproblem nochmal testen.
