### ISSUE TITLE
Feature attachFileFromString

### ISSUE THREAD

**Issue by bekanntmacher** [terminal42/contao-notification_center#209]
Wäre supercool wenn zusätzlich `attachFileFromString` genutzt werden könnte.

https://github.com/contao/contao/blob/7def0fef3327c81c431d42cac11675accad3bb32/core-bundle/src/Resources/contao/library/Contao/Email.php#L336

Zum Beispiel für ein PDF welches generiert wird und nur verschickt aber nicht gespeichert wird.

**Comment by richardhj** [comment]
Wie funktioniert das dann?

**Comment by bekanntmacher** [comment]
Ich verstehe deine Frage nicht.

**Comment by Toflar** [comment]
Die `Email` Klasse von Contao wird früher oder später sterben. Daher wird in [Version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277) auf sie verzichtet. Ich schliesse das Ticket daher - die Mailer-Komponente und neue Events werden entsprechendes Feature ermöglichen.
