### ISSUE TITLE
Eigener Text fehlt bei Abonnieren (Notification Center)

### ISSUE THREAD

**Issue by exscorp** [terminal42/contao-notification_center#211]
Hallo, beim Modul **Abonnieren (Notification Center)** fehlt die Textarea des normalen **Abonnieren**-Moduls. Dafür befindet sich dort ein Auswahlfeld für die Benachritigung, dieser müsste eigentlich unter **E-Mail-Einstellungen** rein, da es dort um die E-Mail geht. **E-Mail-Einstellungen** ist aber auch weg im **Abonnieren (Notification Center)** Modul.

Ein Kunde wollte den Text geändert haben, habe diesen aber nirgendwo gefunden, alle Seiten und Templates durchgegangen und nur das im nl_default Template gefunden

```
<?php if ($this->text): ?>
  <div class="widget widget-explanation">
    <?= $this->text ?>
  </div>
<?php endif; ?> 
```

aber kein Textfeld wo ich das eintragen kann, bis ich auf die Idee kam das Modul zu tauschen.

Ist es ein Bug oder so beabsichtigt? Den **Eigener Text** hat ja nichts mit der Notification zu tun und dient dem Modul als zusätzlicher Text.

![newsletter-contao](https://user-images.githubusercontent.com/3008649/84905731-5598d200-b0b1-11ea-92ed-0dc89f7efac7.jpg)
![newsletter-notification](https://user-images.githubusercontent.com/3008649/84905734-56c9ff00-b0b1-11ea-90f8-5f56462cebb4.jpg)

**Comment by Ernestopheles** [comment]
So wie ich es verstanden habe und auch erfolgreich benutze, fehlen beim Modul des NC die Email-Einstellungen deshalb, weil sie durch die Benachrichtigung ersetzt werden. Beim NC-Modul kannst und solltest du das double-opt-in mittels einer Benachrichtigung durchführen. Das bietet weitere Vorteile.

In der Tat ist die Platzierung der Benachrichtigung unter "Eigener Text" wenig glücklich und sollte imo geändert werden. 

Ich halte den eigenen Text für sinnvoll, der hat ja nichts mit dem Notification zu tun und sollte immer möglich sein. Bitte aktiviert den "alten" eigenen Text wieder!

**Comment by richardhj** [comment]
Found an evil bug in the dca. Fixed in d8ab2b673b5db8dd512583b1e17daec284e11303 😈
