### ISSUE TITLE
downloads element not accepting new files written by NC

### ISSUE THREAD

**Issue by Ernestopheles** [terminal42/contao-notification_center#214]
Contao 4.9

Downloads element showing to a directory /files/dir/.

Adding files to dir/ by notification center (.txt)

Downloads does not integrate these new files to it's list. New files will not be shown on side.

If new files being dragged and dropped in filemanager hence and forth, downloads will integrate them.

Answer from Fritz:
"If you selected a folder in the downloads element, then the element will only show files that have been added to the DBAFS (tl_files). Presumably, the NC does not add the generated file to the DBAFS."

I found that Fritz is right. So I moved this issue from Contao to NC.

**Comment by richardhj** [comment]
Hi, thank you for bringing this up.

I checked the source and found that - when writing a file via NC - the new file actually is added to the DBAFS.

For reference: 
https://github.com/terminal42/contao-notification_center/blob/bf111209bf5617d08d08581b2dc4ca0b9622eeab/library/NotificationCenter/Gateway/File.php#L193
Closing the file will call Dbafs::addRessource().

When adding a ressource to the DBAFS, all folder hashes will be updated as well.
To be honest, I cannot tell why your download content element will not show the correct files.

But as you mentioned, doing a file sync in the back end will fix this issue?

**Comment by Ernestopheles** [comment]
yes, I tried it out once more, File will be shown on website via downloads element only after doing a manuel sync in filemanagement.

**Comment by Ernestopheles** [comment]
![Bildschirmfoto vom 2020-10-29 16-09-40](https://user-images.githubusercontent.com/7561403/97592736-459ae280-1a01-11eb-8af9-db02e073f5de.png)

**Comment by Ernestopheles** [comment]
we are not using this feature any more, so for me its done
