### ISSUE TITLE
Fehlermeldung in Contao 4.10.0

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-notification_center#218]
Fehler beim Absenden eines Formulars über das Notification-Center:

`Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Swift_SmtpTransport" from the global namespace. Did you forget a "use" statement?" at /volume1/web/webseiten/contao410/vendor/terminal42/notification_center/library/NotificationCenter/Gateway/Email.php line 61 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Attempted to load class \"Swift_SmtpTransport\" from the global namespace.\nDid you forget a \"use\" statement? at /volume1/web/webseiten/contao410/vendor/terminal42/notification_center/library/NotificationCenter/Gateway/Email.php:61)"} []`

Soweit ich weiß, ist der Swiftmailer dem Symfony-Mailer gewichen.

**Comment by Toflar** [comment]
@richardhj can you take care? We need to handle both mailers as done in core now.

**Comment by richardhj** [comment]
It won't work to override the SMTP settings in runtime since the transports are immutable. I will work on a fix that provides a select on available transports (same as the per-root-setting).

**Comment by richardhj** [comment]
Die Änderungen vom Core sind nun im Notification Center unterstützt.
