### ISSUE TITLE
Error message in contao 4.9 due override smtp settings

### ISSUE THREAD

**Issue by koertho** [terminal42/contao-notification_center#220]
The new hint about custom smtp settings in contao 4.10 is a litte greedy and also appears in contao 4.9, where we can't remove it.

> [Notification Center]: Using custom SMTP settings has been changed in Contao 4.10. Please visit the documentation to learn how to define SMTP settings. Then, please update all email gateways that need this feature and disable "Override SMTP settings".

Contao 4.9.5
PHP 7.4.9
terminal42/notification_center: 1.5.14

**Comment by richardhj** [comment]
What do you mean by "greedy"?

**Comment by koertho** [comment]
The message should only appear in contao 4.10 as we can't use the new features in 4.9 and older 😉

**Comment by richardhj** [comment]
Roger! 347dee3d4193e864824132352ab993817a37cf37 should fix this.
