### ISSUE TITLE
Feature proposal: add automatically generated ICS files to notifications

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-notification_center#221]
Hello,

for a customer we currently have the request for a new feature concerning notifications and I thought it might be a cool addition for the notification center "core" module.

For an event registration function we need to auto generate ICS files and append these to the notifications being sent.

My first idea was to add an option to a notification which activates the feature and is a selector for a subpalette where I can specify the token(s) being used for the generation of the file.

Is there any interest to have such a feature in the core module or is it rather an extension which should go into a separate module?

Thanks in advance :-)

Bye Defcon0

**Comment by richardhj** [comment]
Hi @Defcon0, apologize for the late response. 
I worked with ICS files in Contao as well, and IMHO an iCal export cannot be generalized in that extent to be suitable for the notification center.
This will only work if the event data passed as token is in a very specific format / or array structure.
Furthermore, this would add a new dependency which can be avoided :)
