### ISSUE TITLE
Could not find matching language or fallback for message ID … and language …

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-notification_center#223]
Since version `1.5.17`, notifications with messages of Gateways that do not require any actual message content or language specific data (i.e. there is no `tl_nc_language` entry for them, like for API communications) do not work any more. In the system log the following message will appear for example:

```
Could not find matching language or fallback for message ID "6" and language "de".
```

Probably due to the changes introduced in #222.

I will try to analyse the problem and create a PR myself - however, since @rabauss and @richardhj worked on #222 in more detail: do you guys have any initial idea how to solve this?

**Comment by richardhj** [comment]
Instead of returning false here:
https://github.com/terminal42/contao-notification_center/pull/222/files#diff-1b258e93c30422acaf6526c8a5005149e5f293d380f136bb2f3d1a663de214d2R79
We should set the language inside this block instead

A message without actual languages is an edge case, isn't it? :D

**Comment by fritzmg** [comment]
> A message without actual languages is an edge case, isn't it? :D

I don't know, seems valid to me to use Notification Center messages for API calls. e. g. you have a form collecting leads and you not only want to send the collected data via e-mail but also make an API call to an external service like Klick-Tipp for automatic follow ups for example.

**Comment by contaoacademy** [comment]
3 of my extensions with API-calls don't work anymore with Version `1.5.17`
I would pay for priority support ;-)

**Comment by richardhj** [comment]
@fritzmg do you provide a PR or should I? WDYT of my idea (https://github.com/terminal42/contao-notification_center/issues/223#issuecomment-720367255)

**Comment by fritzmg** [comment]
I _think_ it sounds right 😁 . But as I said, I did not follow the PR in great detail, thus I am not sure if there are other implications to consider. I'd like to hear @rabauss feedback too.

@richardhj if you could provide a PR that would be great :).

**Comment by richardhj** [comment]
Ok fixed @contaoacademy :)

**Comment by richardhj** [comment]
It should work @fritzmg because if you don't have a language model, you don't need to switch the language of the framework 😆

**Comment by contaoacademy** [comment]
@richardhj I will test it and give you feedback.

**Comment by contaoacademy** [comment]
@richardhj Seems to work fine. Thx for your fast support.

**Comment by rabauss** [comment]
Sorry! Seems to be good for me - unfortunately, this was no test case for me.
Although I wondered why the logic was not in all the gateways.

@richardhj Thanks for the fix!
First I thought we need to disable the switch back of the framework language but fortunately this is only done, if the currentLanguage is not null ;-)
