### ISSUE TITLE
In combination with conditionalformfields the simple tokens will no longer be replaced

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-notification_center#227]
Notification Center version 1.5.18 was installed during the last system update.

In connection with the terminal42/contao-conditionalformfields extension, the Simple Tokens are not replaced if the condition is met.

Instead of `beds: 2`, `beds: ##form_beds##` is output in the notification.

![error](https://user-images.githubusercontent.com/1942550/102049522-4b962880-3de1-11eb-95dd-02f0beadb455.png)

I am now back on version 1.5.17 and everything works fine.

**Comment by richardhj** [comment]
Currently, you installed `notification_center:1.5.17` and `conditional-formfields:2.3.3`?

**Comment by netzarbeiter** [comment]
Thats right

**Comment by netzarbeiter** [comment]
I could set up a copy of the system and grant you access.

**Comment by richardhj** [comment]
That's odd. I try to reproduce this issue.
If it doesn't cause any trouble, please give me access to the system.

**Comment by netzarbeiter** [comment]
I have set up a copy of the system and failed to reproduce the issue. After updating NC on the live system it also works here. Please excuse the circumstances.

**Comment by richardhj** [comment]
There was only one significant change in the last weeks: https://github.com/terminal42/contao-conditionalformfields/commit/c9054db766e06bbae96cce068e0c3ae6f5121d77
This change is part of condffl version 2.3.3 and that's why I wanted to be concrete on the version.
Great, if the error vanishes.
