### ISSUE TITLE
Symfony Expression Language not working in recipients field?

### ISSUE THREAD

**Issue by bennyborn** [terminal42/contao-notification_center#234]
I just noticed when using Contao 4.11 (which supports Symfony Expression Language) it seems I cannot use the following expression in the `Recipients` field:

`{if form_inquiry_type in ["marketing", "sales"]}sales@example.com{else}contact@example.com{endif}`

![image](https://user-images.githubusercontent.com/226890/126773536-1f753c74-af89-4d06-b71c-ee6abdbbf764.png)

Using the same statement in `Raw text` or `HTML` works totally fine.

Ah okay, I see the problem...

https://github.com/terminal42/contao-notification_center/blob/d9f127310c24f72d3850175dc8bffee2ff433307/classes/tl_nc_language.php#L166-L169

The commas in `{if form_inquiry_type in ["marketing", "sales"]}` causes "invalid" chunks.

What about a solution like this? 
Why not just parse all the SimpleTokens before trying to validate what is left afterwards?

```php
    public function validateEmailList($varValue, \DataContainer $dc)
    {
        if ($varValue != '') {

            $parsedValue = '';

            if (version_compare(VERSION . '.' . BUILD, '4.10.0', '>=')) {
                $parsedValue =  \System::getContainer()->get(SimpleTokenParser::class)->parse($varValue, array());
            } else if (version_compare(VERSION . '.' . BUILD, '3.5.1', '>=')) {
                $parsedValue = \StringUtil::parseSimpleTokens($varValue, array());
            } else {
                $parsedValue = \String::parseSimpleTokens($varValue, array());
            }

            $chunks = trimsplit(',', $parsedValue);

            foreach ($chunks as $chunk) {

                // Skip string with tokens or inserttags
                if (strpos($chunk, '##') !== false || strpos($chunk, '{{') !== false) {
                    continue;
                }

                if (!\Validator::isEmail($chunk)) {
                    throw new \Exception($GLOBALS['TL_LANG']['ERR']['emails']);
                }
            }
        }

        return $varValue;
    }
```

**Comment by aschempp** [comment]
this validation would only work for email, not actual content, right? I don't know if there's a way to ask the Expression Language to _validate_ a string instead of just parse 🤔

**Comment by bennyborn** [comment]
> this validation would only work for email, not actual content, right?

I'm not sure if I understand you correctly but yes, in this case this is only intended to validate the email adresses. 

> I don't know if there's a way to ask the Expression Language to validate a string instead of just parse

Why bother? I see nothing wrong with the original approach itself, it's just missing the handling of the SEL 🤷‍♂️

**Comment by Toflar** [comment]
In [version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277) I've dropped the validation part completely. It had also other strange implications such as simply not being able to write `##content##` as it is.
You may want to revisit this issue once there's a public beta. I'm closing it for now as I need to do some cleanup here.
