### ISSUE TITLE
Attachment tokens not working when Contao is not in production mode!

### ISSUE THREAD

**Issue by smohring** [terminal42/contao-notification_center#235]
Hi Guys, 

I have a attachment template registered for a notification.
There will be only one path echo'ed within the template.
Unfortunately it is working only, if the **site is in production mode**.
Otherwise, Contao will add it's template tags, causing your logic to use more than the actial path - the "is_file" check will then fail.
See: **system/modules/notification_center/library/NotificationCenter/Util/StringUtil.php:76**

Template when "dev" mode is enabled - not working:
```
<!-- TEMPLATE START: templates/holtzbrinck-karriere.com/notification_applicant_attachment.html5 -->
files/mytestfile.zip
<!-- TEMPLATE END: templates/holtzbrinck-karriere.com/notification_applicant_attachment.html5 -->
```

Template, when "prod" mode is enabled - working:
```
files/mytestfile.zip
```

**Comment by fritzmg** [comment]
@smohring can you please install and test `dev-hotfix/token-attachment-templates`?

**Comment by smohring** [comment]
Sorry guys, for miss testing, but thank you all for fixing the bug :) Appreciate it!
