### ISSUE TITLE
Warning: Undefined array key "GATEWAY" / Warning: Undefined array key "NOTIFICATION_TYPE"

### ISSUE THREAD

**Issue by xprojects-de** [terminal42/contao-notification_center#236]
Hello all,

using the notificationCenter in dev-Mode with high error_reporting there are the following errors:

ErrorException:
Warning: Undefined array key "GATEWAY"

  at vendor/terminal42/notification_center/config/config.php:95
  at include('/Users/benjaminhummel/Documents/MAMPP/alpdesk-booking/vendor/terminal42/notification_center/config/config.php')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php:151)
  at Contao\Config->initialize()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php:116)
  at Contao\Config::getInstance()
     (vendor/contao/core-bundle/src/Framework/Adapter.php:44)
...

ErrorException:
Warning: Undefined array key "NOTIFICATION_TYPE"

  at vendor/terminal42/notification_center/config/config.php:110
  at include('/Users/benjaminhummel/Documents/MAMPP/alpdesk-booking/vendor/terminal42/notification_center/config/config.php')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php:151)
  at Contao\Config->initialize()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php:116)
...

It´s working fine but has to be fixed when running in Debugmode for development :-)

Thankx and Greetings

**Comment by fritzmg** [comment]
Closing in favor of #230
