### ISSUE TITLE
Using notification for member registration email leads to members being deleted

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-notification_center#237]
If you use the regular notification option in the registration module (`nc_notification`), the Notification Center will currently _always_ create an opt-in token.

However, this is problematic in setups where an administrator is supposed to activate the members, instead of the members themselves through the link in the email. Since the opt-in token has been created, all registered members will get deleted after 24 hours, since the opt-in can never be confirmed.

Contao itself will only create the opt-in token, if the option **Send activation e-mail** (`reg_activate`) is enabled. Because otherwise it is assumed that the admin will activate the member and an email to the admin will be sent instead.

I am not sure how this should be solved though. Maybe the NC should create the opt-in token only on-the-fly, if the `##link##` token is present in one of the messages? Because if it isn't there is no way to confirm the opt-in.

**Comment by Toflar** [comment]
> I am not sure how this should be solved though. Maybe the NC should create the opt-in token only on-the-fly, if the `##link##` token is present in one of the messages? Because if it isn't there is no way to confirm the opt-in.

As NC cannot know about the `reg_activate` option I think this is the only way?

**Comment by fritzmg** [comment]
Well, the `ContaoHelper::sendRegistrationEmail` method _can_ know about this option. But it would not be intuitive to use together with the notification center, as you control in the notification where you want to send an e-mail to, not in the module.

**Comment by Toflar** [comment]
Yes that's what I meant. So probably we could use a placeholder in `##link##` (like `https://....?token=NC_ACTIVATION_TOKEN` and use our own `sendNotificationMessage` hook to check if there's `##link##` used in the message and only then actually generate the opt-in token and replace `NC_ACTIVATION_TOKEN` with the correct value in `##link##`?

**Comment by fritzmg** [comment]
Or `ContaoHelper::sendRegistrationEmail` could load all messages of the notification and all languages of these messages and check their content for `##link##` and only then actually create the opt-in token and simple token. The `sendNotificationMessage` Hook would need to do something similar, but also load the parent notification and check its type.

**Comment by Toflar** [comment]
Hmm, probably the first option sounds better but I'll leave that up to you.
The two questions

- Does message use token x?
- Does notification use token x? (essentially just a proxy for foreach($messages as $message) -> $message->doesContainTokenX)

should be answered in separate helper methods maybe. That sounds like a use case that could come up in other constellations too.

**Comment by fritzmg** [comment]
Closing in favor of #238
