### ISSUE TITLE
Error saving mailtemplates with if queries + module variables

### ISSUE THREAD

**Issue by Kahmoon** [terminal42/contao-notification_center#239]
Hi,

actually i found a problem that i cannot save mailtemplates anymore which contain variables from contao event subscriptions (https://github.com/codefog/contao-events_subscriptions) in combination with if query.

Contao is sending existing mailtemplates correctly but i cannot edit them anymore.

`{if event_startTime!=""}Uhrzeit: ##event_startTime##{endif}{if event_endTime!=""} - ##event_endTime## Uhr{endif}`
"Unexpected character "#" around position 17 for expression event_startTime!=""."

`{if subscription_username!=""}`
Unexpected character "#" around position 23 for expression subscription_username!="".

Variables without if query, e.g. ##subscription_firstname##, ##event_title## do not have this problem.

<img width="871" alt="Bildschirmfoto 2021-08-25 um 10 22 13" src="https://user-images.githubusercontent.com/6390770/130763531-fa1a95aa-cca5-4c6f-9d42-cd9ba6dffb2e.png">

I´m using the latest versions from all modules:
Contao: 4.11.9
NC: 1.5.18
Event Subscriptions: 2.12.13

**Comment by fritzmg** [comment]
Have you tested whether this happens with other tokens too? In combination with the conditions.

**Comment by MacKP** [comment]
Can you check the content in your Database? Is there really a # in the Database or is it encodet there?

**Comment by qzminski** [comment]
Looks like it's coming from symfony/expression-language: https://github.com/symfony/expression-language/blob/fe696e2669cb47507e5635223ac4b64500339658/Lexer.php#L88

So could be a Contao core issue. @aschempp @Toflar what do you think?

**Comment by Toflar** [comment]
Contao tries to dected whether it can use expression language or if it has to fall back to our previous implementation: https://github.com/contao/contao/blob/c00b90a1c1e84b0df417c82196747863f21dd086/core-bundle/src/Util/SimpleTokenParser.php#L128

But honestly, I don't think this is the problem.

**Comment by Kahmoon** [comment]
> Have you tested whether this happens with other tokens too? In combination with the conditions.

In another form there is no error with stand form fields
`{if form_betreff}###{endif}`

**Comment by Toflar** [comment]
Can you post the whole invalid text? I don't feel like typing it from a screenshot.

**Comment by Kahmoon** [comment]
`Hallo ##subscription_firstname##,

das ist eine automatische Erinnerung an einen bevorstehenden Termin zu dem Du Dich angemeldet hast.

Hier noch mal die Details:
Veranstaltung (##event_id##): ##event_title##
Datum: ##event_startDate##
{if event_startTime!=""}Uhrzeit: ##event_startTime##{endif}{if event_endTime!=""} - ##event_endTime## Uhr{endif}
Link: ##event_link##

{if subscription_username!=""}

Du findest eine Übersicht deiner Anmeldungen unter https://www.xxxx.de/intern/termine/meine-termine.html

[nbsp]

{{insert_content::10406}}

{else}

[nbsp]

{{insert_content::10419}}

{endif}`

**Comment by Kahmoon** [comment]
OK, i have the same error in another form and an normal form field. Maybe its the "empty"?

`{if member_username != ""}test{endif}`
Unexpected character "#" around position 18 for expression `member_username != ""`.

**Comment by Toflar** [comment]
I'm pretty sure the problem is not what you type but what's stored behind the sences. It is encoded and thus we get `#` instead of the raw value. /cc @ausi

**Comment by ausi** [comment]
> Unfortunately the fix did not solve the problem in contao-4.9.20

Did you resave the HTML code?
Does the issue also occur if the text only consists of `{if member_username != ""}test{endif}` ?

**Comment by mdollde** [comment]
I just tried to resave the HTML code, and unfortunetaly it still doesn't work. But I get a different error message:

_Unknown data type of comparison value "= """._

Contao 4.90.20
NC 1.5.18

![screenshot_Contao-NC](https://user-images.githubusercontent.com/45212958/131312714-22ada76f-11f5-4aeb-b8b0-adb346fc843d.png)

**Comment by ausi** [comment]
> I just tried to resave the HTML code, and unfortunetaly it still doesn't work.

Did you apply the fixes from contao/contao#3390 ?

**Comment by mdollde** [comment]
Sorry, my fault. I thought the fixes were already in 4.9.20...

I applied the fixes from contao/contao#3390, and they solve the issue!

**Comment by ausi** [comment]
So we confirmations from @mdollde and @de-es that contao/contao#3390 fixes the issue. 

But it does not seem to fix it for @bizon1 as written in https://github.com/terminal42/contao-notification_center/issues/239#issuecomment-907350821  
@bizon1 can you give us more details? Is the error message still the same? How did you apply the changes from the linked pull request?

**Comment by bizon1** [comment]
The fix solved the issue now. There is no error message anymore. But in database - email_html - every = and " are still encoded.
Thx for the fix guys.

**Comment by Toflar** [comment]
I'm closing this as there are pull requests to fix this in Conato core now. 
Thank you very much @ausi for tackling this and fixing all the security vulnerabilities <3

PS: To everybody reading, he owns a GitHub Sponsors profile and deserves a coffee a month at your expense...

**Comment by aschempp** [comment]
Unfortunately, the changes in Contao do not fix our own token validation in https://github.com/terminal42/contao-notification_center/blob/main/library/NotificationCenter/AutoSuggester.php#L175

**Comment by aschempp** [comment]
see https://github.com/terminal42/contao-notification_center/pull/240

**Comment by Kahmoon** [comment]
Will this be fixed in Contao 4.12.2 or did i miss something?? Is there a workaround i can use meanwhile in Contao 4.12.1?
