### ISSUE TITLE
Support queue via console for Contao 4.12

### ISSUE THREAD

**Issue by rabauss** [terminal42/contao-notification_center#244]
While working for https://github.com/terminal42/contao-notification_center/pull/230 I realized that the queue wont work via console for contao 4.12+ because the `initialize.php` cannot be found anymore!

https://github.com/terminal42/contao-notification_center/blob/ba54a8075f66b96ab26f5faa7a7e4aba2008ed5f/bin/queue#L26

**Comment by Toflar** [comment]
That would be a BC break in core then. It should be there for 3.5 style modules like NC to continue to work.

**Comment by rabauss** [comment]
Well, I haven't investigated any further, but I couldn't run `php system/modules/notification_center/bin/queue` with contao 4.12 - or do I have to execute it different? First, I was looking for a symfony console command 😁

**Comment by fritzmg** [comment]
I cannot reproduce. Executing

```
./system/modules/notification_center/bin/queue
```

Works fine without any error. So does

```
./vendor/terminal42/notification_center/bin/queue
```

**Comment by rabauss** [comment]
Okay, sorry for the false alarm!
It was because auf my develop version, which I placed in a different folder structure and from there the `initialize.php` cannot be found!
