### ISSUE TITLE
BCC Email problem

### ISSUE THREAD

**Issue by asaage** [terminal42/contao-notification_center#245]
My notification_center does not send E-mails to bcc-recipients.
I use the "Standard e-Mail-Gateway" as gateway and there is no special mailer-transport configured.
Contao-System-Log tells me that mail should have been sent to bcc but that's not the case - however normal recipients receive mail flawlessly (didn't check CC).
I'm using contao 4.11.9 and nc 1.6.1
I did test multiple E-mail-Adresses and also checked the spamfolders with no success.
Any Idea how to troubleshoot this?
https://community.contao.org/de/showthread.php?81836-Notification-Center-BCC

**Comment by fritzmg** [comment]
For debugging you can use mailhog for example in order to analyse the e-mail headers of any sent emails. If everything is correct there, then it's a problem of your SMTP.

**Comment by asaage** [comment]
Thanks for finding that @Toflar.
I don't quiet understand the issues with the mentioned pull request.
Should that here stay open until solved or will there be no fix?
In the meantime i can duplicate  and use a seperate notification as a workaround.

**Comment by asaage** [comment]
> switch to a real SMTP setting

That's more or less the problem.

- I do not have access to a mailbox on this (the sender) domain
- If i had, i'd most likely only be able to use one "From" address (but there are multiple for various forms)
- passwords there change on a regular base so keeping that in sync with the config.yml would be challenging

according to composer i use symfony/mailer v5.2.12
https://symfony.com/doc/current/mailer.html#using-built-in-transports

In https://github.com/symfony/symfony/issues/40070 is stated that there is no problem if ```sendmail://default``` is used (instead of ```native://default```)
but i have no clue how i would try that.

**Comment by fritzmg** [comment]
> but i have no clue how i would try that.

One of these would work:

```yaml
# config/parameters.yaml
parameters:
    mailer_transport: sendmail
```

```
# .env.local
MAILER_URL=sendmail://default
```

```
# .env.local
MAILER_DSN=sendmail://default
```

```yaml
# config/config.yaml
framework:
    mailer:
        dsn: sendmail://default
```

**Comment by asaage** [comment]
> Yes, Contao deliberately uses native...

Ok i get it.

Then it boils down to that:
just replacing the php.ini value 
```sendmail_path  = /usr/sbin/sendmail -t -i```
with 
```sendmail_path  = /usr/sbin/sendmail -bs``` 
would have done exactly the same thing (make native work with bcc at least in my environment)?

**Comment by fritzmg** [comment]
Closing as unrelated to the Notification Center.
