### ISSUE TITLE
Newsletteraktivierung funktioniert nicht

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-notification_center#249]
Beim Modul "Abonnieren (Notification Center)" funktioniert die Newsletteraktivierung nicht.
Der generierte Aktivierungslink (https://www.xxxxxxxxxx.de/newsletter/anmeldung.html?token=nl-49d5c25a62c8f9e9b8938) funktioniert, wenn man zusätzlich das Contao-Standard-Modul mit in die Seite einbindet - aber man hat dann auf der Anmeldeseite zwei Formularfelder (einmal vom Modul NC und einmal das Standard-Modul).

Das Ganze kann ich in zwei Installationen nachvollziehen.

Contao 4.9.23
Version 1.6.4
PHP 7.4.25
Provider: All-Inkl

![screenshot](https://user-images.githubusercontent.com/2067428/144406221-9b6645a3-c9dc-4f9a-9c0b-a74a1a63efca.jpg)

**Comment by aschempp** [comment]
Notification Center funktioniert anders als Contao Core. Für die Aktivierung benötigst du das zusätzliche "Aktivieren" Modul.

**Comment by Schmidty2** [comment]
Danke - das war es
