### ISSUE TITLE
##form_file## mit zu viel Informationen

### ISSUE THREAD

**Issue by Acta2000** [terminal42/contao-notification_center#254]
ich habe das NC in Contao 4.4 mit Version 1.6.1 laufen

Dort gibt der Shorttag "##form_file## den Dateipfad ab dem Ordner files aus:

files/ordner/dateiname.endung

In meiner 4.9 mit NC 1.6.5 habe ich folgendes Problem:

Dort gibt: ##form_file##

D:\htdocs\contaoupdate/files/ordner/dateiname.endung

auch wirklich so mit den Slashes und Backslashes aus.

Per E-Mail versenden im Formulargenerator gibt jedoch korrekt
https://domain.de/files/ordner/dateiname.endung aus.

Soll das so sein, dass "D:\htdocs\contaoupdate/" jetzt bei  ##form_file## mitgegeben wird?

**Comment by Acta2000** [comment]
The Change comes with https://github.com/terminal42/contao-notification_center/releases/tag/1.6.4

**Comment by Gwennyphar** [comment]
Hallo,

seit der Contao Version 4.13.2 tritt folgender Fehler mit dem Plugin NC Version 1.6.9 wieder auf.

Mit dem Formulargenerator wird https://domain.de/files/verzeichnis/dateiname.pdf angezeigt.
Mit ##form_file## wird wieder der komplette Serverpfad angezeigt.

Ist das Problem schon bekannt?

Viele Grüße
