### ISSUE TITLE
Improve error handling when sending emails

### ISSUE THREAD

**Issue by rabauss** [terminal42/contao-notification_center#258]
Unfortunately, errors when sending emails are not handled correctly, so the sender will see the success page, although an error occured.

The hook `pocessFormData` will only stop with exceptions:
https://github.com/contao/contao/blob/2f1827b8a2cac27d2b86d7ba6337470217d6c60d/core-bundle/src/Resources/contao/forms/Form.php#L563

But the NC catches all exceptions when trying to send emails:
https://github.com/terminal42/contao-notification_center/blob/068f8680dd0e0d2f9f1d9b8e69a86cd726348166/library/NotificationCenter/Gateway/Email.php#L164

Can we find a better solution for this bad error handling and user/customer experience?

**Comment by Toflar** [comment]
I don't think we can all of a sudden throw the exceptions again.

**Comment by rabauss** [comment]
That's true! Because of that I opened this issue so that it gets attention in v2 ☺️

**Comment by Toflar** [comment]
NC will require a complete rewrite which will be impossible without fundings.
Core: Sure, whatever you want to work on is appreciated :)

**Comment by rabauss** [comment]
Some ideas up for discussion:

- we add a new `MailErrorEvent` to the core
- the `MailErrorEvent` can be dispatched in the notification center on errors/exceptions while executing the hook `processFormData`
- after executing the hook `processFormData` there needs to be added a new listener or subscriber which handles the `MailErrorEvent` (I'm not sure if listener or subscriber is prefered by contao core)
- in the event handler we could redirect to a new `errorJumpTo` (which needs to be added to the forms)

this feature would be nice for contao 5 :-)

**Comment by fritzmg** [comment]
> this feature would be nice for contao 5 :-)

Only three days left for new features ;)
