### ISSUE TITLE
Token raw_data_filled um Zeilenumbruch ergänzen

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-notification_center#260]
Besteht die Möglichkeit, die Ausgabe des Token `raw_data_filled` nach dem Feld jeweils mit einem Zeilenumbruch zu versehen?

**Comment by cliffparnitzky** [comment]
Da wird immer ein `\n` angehängt: https://github.com/terminal42/contao-notification_center/blob/main/classes/tl_form.php#L88

D.h. in der HTML E-Mail hat das keine Auswirkung.

**Comment by contaoacademy** [comment]
> D.h. in der HTML E-Mail hat das keine Auswirkung.

Danke für die Info. D. h. für die HTML-Emails gibt es aktuell keine Lösung.

**Comment by asaage** [comment]
für die HTLM variante probier es mal mit folgendem:

```html
<div>{{flag::##fraw_data_filled##|nl2br}}</div>
```

**Comment by cliffparnitzky** [comment]
> ```
> {{flag::
> ```

Oha, was ist das für ein Inserttag?

**Comment by asaage** [comment]
kommt glaube ich mit Haste

**Comment by asaage** [comment]
hier hatte ich das mal her... allerdings nie mit ##raw_data_filled## probiert: 
https://github.com/terminal42/contao-notification_center/issues/61#issuecomment-146817195

**Comment by contaoacademy** [comment]
`{flag::##raw_data_filled##|nl2br}}` hat funktioniert.
Vielen Dank. Darauf wäre ich nie gekommen.
