### ISSUE TITLE
Notification Symbol fehlt

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-notification_center#263]
Hallo,
ich nutze den Notification Center zusammen mit Leads.
Bei den in Leads aufgelisteten Datensätzen wird das Notification-Symbol nicht mehr angezeigt.

Ursache: Das Symbol "notification.png" war bisher in ".../vendor/terminal42/notification_center/assets" abgelegt. Es fehlt nach dem Update des Notification Center. Wenn man das Symbol von Hand in das Verzeichnis kopiert, wird das Symbol wieder angezeigt.
In ".../assets" fehlen seit dem Update die drei Symboldateien:
- notification.png
- queue.png
- gateway.png

**Comment by Schmidty2** [comment]
Ich habe das Problem mittlerweile bei drei Installationen, das Problem tritt nach dem Update des Notification Center auf.
Hier noch ein paar Details:
- Provider: All-Inkl Business 
- PHP: 7.4.30 
 -Contao 4.13.5 
- Leads 1.4.30 
- NotificationCenter 1.6.12

**Comment by aschempp** [comment]
This would be a bug in leads then, not in notification center. Somehow I'm unable to transfer the issue in GitHub, maybe @Toflar or @qzminski can?

**Comment by Toflar** [comment]
No, and I have this combination in multiple setups.

**Comment by aschempp** [comment]
nevermind, fixed in leads then 🙃
