### ISSUE TITLE
Undefined array key "email_sender_name"

### ISSUE THREAD

**Issue by Ernestopheles** [terminal42/contao-notification_center#279]
at vendor/terminal42/notification_center/library/NotificationCenter/AutoSuggester.php:113

isotope 2.8.8 contao 4.13.14 php 8.1 lokale Umgebung dev Mode

Neu aufgesetzte Webseite; Nachricht vom Typ "Änderung Bestellstatus" erstellt. Wenn ich darin in der Sprache "de" Absenderinformationen (Name und/oder Emailadresse) eintrage und speichere, gibt es diesen Fehler.

**Comment by Ernestopheles** [comment]
hler tritt im dev-Modus auf. Im prod-Modus wird er scheinbar ignoriert.

**Comment by Toflar** [comment]
Fixed e7d3939d1a967c4d4d513192d50e554b905a6fc0.
