### ISSUE TITLE
Postmark Header: X-PM-Message-Stream: broadcast

### ISSUE THREAD

**Issue by Metis77** [terminal42/contao-notification_center#284]
The postmark gateway will always use the transactional stream.
Is there any way to change that  so the gateway will send to the breadcast stream?

The postmark documentation says the the header needs to be set to:
Header: X-PM-Message-Stream: broadcast

**Comment by Toflar** [comment]
I don't think this is supported, no.

**Comment by Toflar** [comment]
I'm closing this. If anybody needs this, build your own gateway.
The next iteration of Notification Center will be 2.0 and we will not support Postmark anymore anyway so it's up to the community to build and maintain a solution.
