### ISSUE TITLE
Support for boolean operators?

### ISSUE THREAD

**Issue by itxup** [terminal42/contao-notification_center#287]
I have a form which offers a multiple-checkbox - so the value within the notification for this field can be "A" or "A,B" or "A,B,C" and so on, as the field itself is an array carrying the values selected.

 I'd like to include an if-clause in my notification which checks if for example checkbox A has been chosen among others. So I want to know if the former array which is being turned into a comma-separated string contains for example value A. Later I want to check for B and for C of course. 

When I try to use simple tokens like 
{if form_myCheckbox contains 'A'} my installation of the notification center says this is not supported. 

When I try to check the cases with a bit cumbersome query like
{if form_myCheckbox == "A" || form_myCheckbox == "A,B" || form_myCheckbox == "A,B,C" } ...{endif}
the check delivers only true for the first condition. Or is not validated correctly in my installation. Is there a plan to add this? 
To compare it: in the conditional form fields I can even use in_array( ... ), I would really appreciate it if something could work here too in this direction? 

My setup is PHP 8.1, Contao 4.13.23, Contao Haste 5.1.9, Notification Center 1.7.1, contao-conditionalformfields 3.0.11

Thanks in advance for any help or enhancement

**Comment by Toflar** [comment]
Yes there is a plan to support this use case better in NC 2.0. The internal representation of tokens should allow for improvements in this area.
