### ISSUE TITLE
Benachrichtungsfehler nach Update: Contao (4.13.35 zu 4.13.37) und Notification Center (1.7.5 zu 1.7.6). 

### ISSUE THREAD

**Issue by mem-lima** [terminal42/contao-notification_center#300]
Hallo Leute,

Fehler nach versuche die Sprachversion eine Benachrichtigung zu erstellen oder eine vorhandene aufzumachen:
"Attempted to load class "System" from namespace "Contao\Contao". Did you forget a "use" statement for another namespace?"

Cache wurde manuell gelöscht.

Zurück auf Version 1.7.5, funktioniert alles wieder normal.

**Comment by fritzmg** [comment]
See https://github.com/terminal42/contao-notification_center/pull/299
