### ISSUE TITLE
Should the sender name be mandatory?

### ISSUE THREAD

**Issue by bennyborn** [terminal42/contao-notification_center#313]
In NC 2.0 is there any reason why the sender email is now mandatory? 
I think there is potential room for error if the user is forced to make sure that the sender is the same as in the configured transport.

**Comment by aschempp** [comment]
I agree, I don't see a reason why it needs to be mandatory.

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-notification_center/commit/a7dcea84891bf159028eb540cdadf382074cf811.

**Comment by fritzmg** [comment]
> I think there is potential room for error if the user is forced to make sure that the sender is the same as in the configured transport.

To be clear: a _transport_ does not have a configured sender. You can override the sender for a transport - but this is always forced, no matter what the notification would say.

In the past the default sender was the admin email from the root page or the system settings - which I hope is still the case in 2.0?

**Comment by Toflar** [comment]
It's not as far as I can tell. PR welcome :)
