### ISSUE TITLE
Activation redirect only working with active activation notification

### ISSUE THREAD

**Issue by de-es** [terminal42/contao-notification_center#314]
NC 2.0.0

Die Weiterleitung nach erfolgreicher Aktivierung funktioniert aktuell nur, wenn auch eine Aktivierungsbenachrichtigung eingestellt ist. Wenn die Einstellung wie auf dem Screenshot ist, wird nur "Your subscription has been activated." auf der Seite angezeigt, wo auch das Modul eingebunden ist, ohne Redirect.

Bug oder Feature? Den Use Case Weiterleitung ohne Notification hätte ich aktuell. 

![contao-nc](https://github.com/terminal42/contao-notification_center/assets/7645771/690c6592-06b7-4a2d-a293-f7893951cb8c)

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-notification_center/commit/8bede90d6443f6b454306a0f2612c399408549cb.

**Comment by de-es** [comment]
Danke für die schnelle Reaktion. @Toflar
