### ISSUE TITLE
Field type "file upload" > Wrong result in E-mail on the first automatic notification

### ISSUE THREAD

**Issue by biowebfr** [terminal42/contao-notification_center#315]
Hi!

I've some kind of issue with the file upload field type.

Here the code I tried inside the e-mail : 

```
1- ##form_add##
2- {{file::##form_add##}} 
```

Here is the result inside the received e-mail  : 

```
1- /var/www/a-propos/files/uploads/avatar.jpg
2-
```

----
And after that when I use the function "Send notification of the lead" to resend the e-mail I got the **good result** :
![image](https://github.com/terminal42/contao-notification_center/assets/46192868/9a799403-857e-48f7-864d-bc0bf92d5358)
 
```
1- 13fa7af0-daf0-11ee-8bf0-fa163e917345

2- files/uploads/avatar.jpg
```

Am I doing something wrong ?

Thank you.

**Comment by Toflar** [comment]
What version of NC are you talking about? And what "lead"? Is this coming from the leads extension? Then it would be irrelevant for this project.

**Comment by biowebfr** [comment]
Sorry for the lack of information.

I use the :

1. Contao Manager 1.8.4
2. Contao 4.13.36
3. Notification Center 1.6.14
4. Leads 1.4

![image](https://github.com/terminal42/contao-notification_center/assets/46192868/acf3d56a-381e-432a-8521-f144a956ff86)

- It's not correct when the e-mail is sent at form completion with NC.
- And note that it is correct when the mail is sent from the Leads.

**Comment by fritzmg** [comment]
What is it that you want to do in your email exactly?

**Comment by biowebfr** [comment]
The e-mail should have this result : 

- 13fa7af0-daf0-11ee-8bf0-fa163e917345 (same has lead when resend)

So we can use insetags like {{file:: }}

At the moment the email has this (path from the server) : 

-  **/var/www/**a-propos/files/uploads/avatar.jpg

And it's not correct

Do you understand ? :)

**Comment by fritzmg** [comment]
> So we can use insetags like {{file:: }}

Why do you want to use this insert tag?

**Comment by fritzmg** [comment]
> Notification Center 1.6.14

You need to update to at least `1.7.8` btw. (which might not be possible due to other dependencies).

**Comment by biowebfr** [comment]
Yes, I think we should make a link to the file in the e-mail.

**Comment by biowebfr** [comment]
You are right, I cant update : 
```
> Resolving dependencies using Composer Cloud v3.7.0
[7.5MiB/0.23s] Loading composer repositories with package information
[87.4MiB/16.56s] Updating dependencies
[120.4MiB/17.03s] Your requirements could not be resolved to an installable set of packages.
[120.4MiB/17.04s] 
  Problem 1
    - Root composer.json requires terminal42/notification_center 1.7.8 -> satisfiable by terminal42/notification_center[1.7.8].
    - terminal42/notification_center 1.7.8 requires codefog/contao-haste ^5.0 -> found codefog/contao-haste[5.0.0, ..., 5.1.16] but these were not loaded, likely because it conflicts with another require.
[120.4MiB/17.04s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[55.3MiB/17.09s] Memory usage: 55.34MB (peak: 223.98MB), time: 17.1s.
[55.3MiB/17.09s] Finished Composer Cloud resolving.
```

**Comment by fritzmg** [comment]
> You are right, I cant update :

You need to update _all_ packages when trying to do that.

**Comment by biowebfr** [comment]
Is there any fix I can do to have the file id instead of the file path ?

**Comment by fritzmg** [comment]
> Is there any fix I can do to have the file id instead of the file path ?

The notification center only receives what Contao provides in the form. If that's the full path, then that's the full path - I don't think the NC can change that.

Usually the path is relative though - so what you would usally have to do in order to provide a direkt link to the file is something like:

```
https://example.com/##form_file##
```

**Comment by biowebfr** [comment]
Ok, I understand what you mean. But... how can we explain that Lead record the ID instead of this path from the root (/var/www/a-propos/files/uploads/avatar.jpg) ?

![image](https://github.com/terminal42/contao-notification_center/assets/46192868/b4c784f0-6385-4cd7-9fa4-1a88598e99ce)

I mean, something is wrong with the first mail send with NC.

There must have been some conversion to get the ID at some point. No ?

**Comment by biowebfr** [comment]
Here is what I have in the config of the e-mail : 
![image](https://github.com/terminal42/contao-notification_center/assets/46192868/bc770634-e681-4193-83a5-c2094716864d)

And here in the e-mail sent : 
![image](https://github.com/terminal42/contao-notification_center/assets/46192868/30466325-4610-4a3e-ad3a-162eb849d1d8)

**Comment by fritzmg** [comment]
> Ok, I understand what you mean. But... how can we explain that Lead record the ID instead of this absolute path from the root (/var/www/a-propos/files/uploads/avatar.jpg) ?

This has nothing to do with the Notification Center itself. It is instead related to how `terminal42/contao-leads` stores the data and then which data it passes to _its_ notification.

**Comment by biowebfr** [comment]
So you can't explain why I've this path (/var/www/...) and not the relative one (files/....) :
![image](https://github.com/terminal42/contao-notification_center/assets/46192868/05bb8576-030f-4b50-9636-04eed8fba3aa)
 
 Is it coming from a contao conf ?

**Comment by biowebfr** [comment]
And terminal42/contao-leads use the same e-mail from NC

**Comment by fritzmg** [comment]
> And terminal42/contao-leads use the same e-mail from NC

It's the same notification - but this time it is `terminal42/contao-leads` who provides the _data_ for the notification, not the Notification Center itself.

**Comment by biowebfr** [comment]
So you tell me that NC and Leads dont use the same data for the same variable when sending the same e-mail ?

Isn't it a problem ? Don't Leads and NC come from Terminal42 ?

**Comment by biowebfr** [comment]
By the way here is what I get on local winamp :
![image](https://github.com/terminal42/contao-notification_center/assets/46192868/bbab4b07-d157-417d-8a6e-d4107bb16f58)

At least it needs to be a relative path and it's not. So there is no way to fix manually this for at least take the relative path if the ID is impossible ? I don't ask for a release, just a way to fix it in my project.

I'm sorry...

**Comment by fritzmg** [comment]
> So you tell me that NC and Leads dont use the same data for the same variable when sending the same e-mail ?

Correct. Leads feeds the notification with its leads data (naturally) while the Notification Center feeds the notification with the data provided by the Contao form.

 > Don't Leads and NC come from Terminal42 ?

That has no bearing on this issue. `terminal42/contao-leads` _uses_ `terminal42/notification_center` - but `terminal42/notification_center` is otherwise an independent package.

> At least it needs to be a relative path and it's not.

Yes, usually the path is relative for regular Contao upload forms. I haven't had time to confirm your issue yet.

**Comment by fritzmg** [comment]
It's definitely wrong as the Notification Center must not pass just the UUID as the token value.

**Comment by biowebfr** [comment]
So how can I do it right and getting that uuid :) ?

**Comment by asaage** [comment]
In Contao 5.3 / NC 2 I'm getting just the uuid even without leads installed.
Thats pretty useless in the text/html field since ```{{file::##form_upload##}}``` returns nothing.
Adding an attachment with ##form_upload## however works flawlessly.

**Comment by Toflar** [comment]
It's perfectly correct and by design. Being able to link to a file in text is not a supported use case and never was.

**Comment by Toflar** [comment]
But you are mixing v1 and v2 here. Also please remember this is an issue tracker, not a support forum. We have other means for that.

**Comment by biowebfr** [comment]
Sorry, for me it sounds like an issue.

I finally choose to do this.

![image](https://github.com/terminal42/contao-notification_center/assets/46192868/3670feb9-bb57-4ffa-a147-addad3069680)
