### ISSUE TITLE
Probleme mit Spalte language

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-notification_center#316]
Beim Übergang von Contao 4.11 zu Contao 4.12 wurde die Spalte 'language' in den Core-DCAs von 5 auf 64 Zeichen verlängert. Den Hintergrund kenne ich zwar nicht, aber es hat vielleicht mit dem utf8mb4 und mit den Untervarianten der Sprachen zu tun.

Beim NC ist die Tabelle tl_nc_language seit der Version 1.7 auch auf 64 Zeichen verlängert worden, leider habt Ihr die Verlängerung für die Warteschlange in tl_nc_queue nicht angepasst. Ich vermute, dass daraus meine Fehlermeldung resultiert **"String data, right truncated: 1406 Data too long for column 'language' at row 1"**. Leider geht aus der Meldung nicht hervor in welcher Tabelle der Fehler auftritt. Das Log sagt auch nicht mehr.

**Comment by Metis77** [comment]
Ich kann bestätigen, das tl_nc_queue auch nach der DB Migration die Länge 5 hat.
Nach manuellem Änder in der DB auf 64 funktioniert es uns unser Fehler ist weg.

Allerdings kommt der Fehler natürlich bei jeder DB Migration wieder ... was aktuell ein Deployment verhindert.

**Comment by fritzmg** [comment]
Just add the following to your application for a workaround:

```php
// contao/dca/tl_nc_queue.php
$GLOBALS['TL_DCA']['tl_nc_queue']['fields']['language']['sql'] = ['type' => 'string', 'length' => 64, 'default' => ''];
```

**Comment by aschempp** [comment]
Fixed in bd6f6e48e3a5626e615b25eeba5cdcc82dcc2ae7
