### ISSUE TITLE
Simple Tokens Doku

### ISSUE THREAD

**Issue by LBeckX** [terminal42/contao-notification_center#317]
Hi zusammen,

aktuell entwickle ich eine Seite weiter, die vor einigen Jahren entwickelt wurde. Hier ist mir aufgefallen, dass in dem HTML-Feld des Notification-Centers folgender Simple Token verwendet wird:

```
##template_HTML-SINNVOLLER_NAME_FUER_EIN_TEMPLATE##
```

in dem Contao-Templates Ordner liegt dann das folgende Template:

```
notification_HTML-SINNVOLLER_NAME_FUER_EIN_TEMPLATE.html5
```

wessen Inhalt den Tag austauscht.
Leider finde ich nur 0,0 Doku zu den Simple-Tokens außer in der Pro Doku und in der Contao-Doku.
https://extensions.terminal42.ch/docs/notification-center/en/configuration/

Könntet das die Doku ein bisschen ausgebaut werden? Das wäre klasse.
Danke und Grüße

**Comment by LBeckX** [comment]
@fritzmg würde ich gerne machen, jedoch finde ich dazu nichts.
Sprich wie soll ich etwas beschreiben, was ich nicht kenne? Wären da der/die Entwickler oder PMs viel besser geeignet mit mehr Hintergrund-Wissen?

**Comment by fritzmg** [comment]
It sounded like you know already.

**Comment by Toflar** [comment]
Die Dokumentation betrifft das NC in v2. Da gibt es m.E. kein solches Token.

**Comment by LBeckX** [comment]
Verstehe, das macht Sinn. Habe aktuell V1.7.8 im Einsatz.
Dennoch wäre m. E. eine kleine Doku bezüglich der verfügbaren Simple Tokens gut. Ist ja ein relevantes Feature, was das Darstellen und Handling von Daten viel einfacher macht. Bezogen auf Links, die ich in Foren gefunden habe, gab es so eine Doku schon einmal. Die ist wohl nur aus der GitHub README.md rausgeflogen.
