### ISSUE TITLE
Images in HTML-messages are not displayed in emails

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-notification_center#319]
When I insert an image (e.g. logo) into a message using TinyMCE, the relative path is used.

The source-code looks like this: `<img src="files/theme/img/logo-01.png" alt="Logo" width="800" height="199"></p>`

When the notification is sent, the e-mail client cannot display the image.
I then tried to use the inserttag `image`. No absolute path is output here either.

Now, I do not know whether this is a Contao 5.3 problem or one of the Notification Center 2.x.

Contao 5.3.1
NF: 2.0.1

**Comment by Toflar** [comment]
Embedding images is a feature that is currently not yet supported, see https://github.com/terminal42/contao-notification_center/blob/main/UPGRADE.md

**Comment by contaoacademy** [comment]
Thank you for your feedback. Please excuse me for not reading the upgrade.md. 🙈
