### ISSUE TITLE
Redirect page for successful activation not found (404)

### ISSUE THREAD

**Issue by de-es** [terminal42/contao-notification_center#320]
Testumgebung:
- Contao 4.13.38
- NC 2.0.1
- Offical Demo

Steps to reproduce:

- Erstelle zwei neue Zielseiten für Subscription und Activation.

![nc_site](https://github.com/terminal42/contao-notification_center/assets/7645771/016df6da-e443-4615-a549-f1514f3b6361)

- Erstelle neues Modul `Subscribe (Notification Center)`

![nc_module](https://github.com/terminal42/contao-notification_center/assets/7645771/3947ade6-9a6c-4160-943a-f1318be51cc7)

- Ersetze unter `domain.de/newsletter.html` das Standard-Subscribe-Modul mit dem von NC.
- Subscribe den Newsletter.
- 303-Redirect auf Seite Newsletter-Subscription ✅
- Mail erhalten mit `###link###` = `domain.de/newsletter.html?token=nl-123` ✅
- Aktivierungslink geklickt.
- 303-Redirect auf Seite Newsletter-Activation `domain.de/newsletter/newsletter-activation.html`  ✅

Bis hierhin funktioniert alles wie erwartet und erfolgreich.

- Ändere Page alias von der Seite, wo das Modul eingebunden ist, von `newsletter` auf `modules/newsletter`.
- Subscribe den Newsletter.
- 303-Redirect auf Seite Newsletter-Subscription ✅
- Mail erhalten mit `###link###` = `domain.de/modules/newsletter.html?token=nl-123` ✅
- Aktivierungslink geklickt.
- 303-Redirect auf `domain.de/modules/newsletter/newsletter-activation.html` ➡️ 404 ❌

Hier wird der Zielseite noch `/modules` vorgestellt, was vermutlich so nicht sein sollte.

**Comment by aschempp** [comment]
Fixed in f426ae7e6e7c721cbb6f3c2483d7c16401ab13d4

**Comment by de-es** [comment]
@aschempp Vielen Dank!
