### ISSUE TITLE
Unsubscribe without notification throws error

### ISSUE THREAD

**Issue by de-es** [terminal42/contao-notification_center#321]
Testumgebung:

- Contao 4.13.39
- NC 2.x (dev-main)
- Offical Demo

Steps to reproduce:

- Erstelle ein Modul "Unsubscribe (Notification Center)" ohne dort eine entsprechende Notification auszuwählen.
- Binde das Modul irgendwo ein.
- Führe eine Abmeldung durch.

Fehlermeldung:

```
Terminal42\NotificationCenterBundle\Exception\Parcel\CouldNotCreateParcelException:
The message ID "0" does not exist.
```

Nun könnte man die Notification dort einfach zum Pflichtfeld machen.

Mein aktueller Usecase wäre aber genau der, dass ich keine Notification versenden möchte. Dann stellt sich natürlich berechtigterweise die Frage, warum ich denn überhaupt hier das NC-Modul verwende. Weil leider das Unsubscribe-Modul von Contao auch immer eine Mail verschicken will. Und es würde als Feature IMHO ja gut zum Subscribe-Modul passen, wo die Activation notification auch optional ist.

Also Workaround schicke ich die Mail aktuell einfach nach /dev/null.

**Comment by fritzmg** [comment]
> Weil leider das Unsubscribe-Modul von Contao auch immer eine Mail verschicken will.

You could implement a `removeRecipient` hook that redirects immediately. This way Contao does not send the unsubscribe email.

**Comment by Toflar** [comment]
https://github.com/terminal42/contao-notification_center/commit/19acf509f614114bb1958f903300a479be965940
