### ISSUE TITLE
Insert tags in mail template not processed

### ISSUE THREAD

**Issue by de-es** [terminal42/contao-notification_center#322]
Testumgebung:

- Contao 4.13.39
- NC 2.x (dev-main)
- Offical Demo

Steps to reproduce:

- Setze zB `{{env::url}}` in das Standardtemplate für Mails `mail_default.html5`.
- Erstelle eine Notification.
- Löse die Notification aus.

Ergebnis:

Der Insert Tag wird in NC2 nicht ersetzt. In NC1.7 dagegen bei gleichartiger Konfiguration schon.

Eine Regression oder ist das im NC2 erstmal so konzeptionell nicht vorgesehen?

Insert Tags im Mailbody bei Plain Text und HTML funktionieren soweit ohne Probleme.

**Comment by simon-1977** [comment]
Ich konnte mir so behelfen und zwar direkt in der Benachrichtigung:
{{env::url|urlattr}}/{{link_url::*|urlattr}}

Umgebung:

- Contao 4.13.39
- NC 2.0.2

**Comment by Toflar** [comment]
https://github.com/terminal42/contao-notification_center/commit/ef06dd7794a2db6eb67bf86336daa578f8cac333

**Comment by de-es** [comment]
@Toflar Dankeschön für den Fix! :heart:
