### ISSUE TITLE
internal links not working

### ISSUE THREAD

**Issue by Ernestopheles** [terminal42/contao-notification_center#324]
Ein Link auf eine Seite innerhalb des Seitenbaums wird in der Email aufgelöst zu (am Beispiel Newsletter abbestellen Link):
mail://vfolder/funktionen/newsletter-kuendigen.html

**Comment by Toflar** [comment]
Wie lässt sich das Problem reproduzieren?

**Comment by Ernestopheles** [comment]
Erstelle eine Benachrichtigung vom Typ "Newsletter aktiviert"; schreibe eine Nachricht, die in der HTML Area einen Link enthält - z.B. auf die Startseite. 

Abonniere und aktiviere den Newsletter und schau in deine Bestätigungsmail. Der Link funktioniert nicht und hat o.g. Inhalt

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-notification_center/commit/9921b210246af51866207290ed2aec3862eeebf1. Please confirm before I release :)

**Comment by Ernestopheles** [comment]
Thanks, but sorry I am not able to confirm as my   IDE Not working (devilbox not working and no more supported)
