### ISSUE TITLE
No notification-type set ("Unbekannte Option") in Gateway after update to 2.0

### ISSUE THREAD

**Issue by janborg** [terminal42/contao-notification_center#327]
After updating the notification center to 2.0 with a previous gateway “e-mail”, the gateway type is set to “unknown option” after the update, as apparently no migration exists.

![Bildschirmfoto vom 2024-05-04 17-55-54](https://github.com/terminal42/contao-notification_center/assets/10844680/1400bfd8-5e75-43c4-8d51-43737590b665)

In this state, the language is no longer visible in the notifications and no more notifications can be sent. Only after the gateway type is set to (the only option) Contao-Mailer, you can see and edit the languages and notifications are sent again.

A migration for gateways email -> mailer would be useful or at least a note in the UPGRADE.md that the gateway type must be corrected manually after the update.

Jan 

Contao 4.13.40

**Comment by aschempp** [comment]
see https://github.com/terminal42/contao-notification_center/pull/328
