### ISSUE TITLE
Notifications fail silently

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-notification_center#335]
Currently if the `MailerGateway` for example returns a `Receipt` for an unsuccessful delivery, these failed attempts are not logged anywhere at all.

Should we at least add a system log entry in `NotificationCenter::sendParcel()` for unsuccessful receipts? This would restore the behavior of NC 1.x (and in Contao 5 these logs would be written to the file log as well).

wdyt?

**Comment by Toflar** [comment]
Yeah I think I would accept a PR that implements a simple listener for that. The `ReceiptEvent` can be used for exactly that and log to the system log in case the delivery failed. All the info required for that are part of the `Receipt` :)

**Comment by fritzmg** [comment]
Sounds good 👍. Will do a PR when I have the time.

**Comment by fritzmg** [comment]
See #337
