### ISSUE TITLE
Mail Problem: The parcel could not be delivered... The \"\" transport does not exist

### ISSUE THREAD

**Issue by ggradwohl** [terminal42/contao-notification_center#343]
From update Contao 4.13 to 5.3 
`SELECT * FROM tl_nc_gateway WHERE mailerTransport = ''; `
an update must be made after Update to work again: 
`UPDATE tl_nc_gateway SET mailerTransport = NULL WHERE mailerTransport = ''; -`

**Comment by fritzmg** [comment]
> From update Contao 4.13 to 5.3

To be clear: this error happens when yo update from NC 1.x to 2.x. It has nothing to do with Contao.

**Comment by Toflar** [comment]
Can you check if https://github.com/terminal42/contao-notification_center/pull/344 would fix the issue?
