### ISSUE TITLE
Dependency on a non-existent service "Codefog\HasteBundle\StringParser" Fehler nach Installation

### ISSUE THREAD

**Issue by chrizdee** [terminal42/contao-notification_center#353]
Nach der Installation von Notification Center über Contao Manager ist die Website nicht mehr erreichbar:

`The service "Terminal42\NotificationCenterBundle\NotificationCenter" has a dependency on a non-existent service "Codefog\HasteBundle\StringParser".`

Contao Version 4.13.45
Notification_center: 2.0.4
PHP: 8.2

Auch ein Versuch das Modul über composer im Terminal direkt zu installieren, führt zum gleichen Ergebnis.

**Comment by aschempp** [comment]
This has been fixed in version 2.0.5
