### ISSUE TITLE
"Dateianhänge via Tokens" funktionieren nicht

### ISSUE THREAD

**Issue by cscheibelhut** [terminal42/contao-notification_center#355]
Hallo,

ich habe das Problem, dass die Dateianhänge fehlen bei Nutzung von Tokens. 
Hier mein Eintrag dort: files/pdfs/##form_produkt##.pdf
"produkt" ist ein Checkbox-Feld, der value entspricht dem Dateinamen der PDF.

Contao ist auf Version 5.3 und ich verwende die aktuelle Version 2.0.13 von terminal42/notification_center.

Eventuell habe ich das auch falsch konfiguriert? Würde mich über Hilfe freuen.

Vielen Dank und liebe Grüße,
Christian

**Comment by fritzmg** [comment]
See https://github.com/terminal42/contao-notification_center/issues/342#issuecomment-2290821873
