### ISSUE TITLE
Dateianhänge werden immer mit vollem Pfad ausgegeben

### ISSUE THREAD

**Issue by theDyingMountain** [terminal42/contao-notification_center#356]
Seit Version 2.0 umfasst der Pfad des Dateianhangs in der E-Mail den vollen Serverpfad und nicht mehr ab dem Contao Root Folder:

_/homepages/xx/dxxxxxxx/htdocs/xxxxx/contao5/files/uploads/aussen02.jpg_

zuvor

_files/uploads/aussen02.jpg_

**Comment by Toflar** [comment]
Ein Token enthält was auch immer der/die Entwickler:in definiert. Das ist für das Notification Center egal. Das ist dann wahrscheinlich ein Token, was nicht für die Verwendung innerhalb von Text gedacht ist :)

**Comment by theDyingMountain** [comment]
Ich verwende einfach ##raw_data## :)

**Comment by theDyingMountain** [comment]
Wieso wurde das Ticket geschlossen? In ##raw_data## ist ja der komplette Pfad enthalten. Oder wurde etwas verändert?

**Comment by fritzmg** [comment]
Probably closed in favour of https://github.com/terminal42/contao-notification_center/pull/375

**Comment by Toflar** [comment]
Weil's eine Frage war und die beantwortet wurde🤷‍♂️ Nutzt bitte die üblichen Kanäle für Support😊

**Comment by theDyingMountain** [comment]
Okay, ich war mir nur unsicher, weil es direkt falsch in ##raw_data## ankommt, aber ja, da müssen die Entwickler vom Core oder des entsprechenden Upload-Plugins ran.
