### ISSUE TITLE
[V2.0] Fehlermeldung beim Versenden

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-notification_center#357]
nach einem Upgrade von Contao 4.13 NC 1.6 zu Contao 5.3 NC 2.0.13 mit PHP 8.3

kommt beim eim Versenden über ein Formular kommt im Log

`Message "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: "Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Expected response code "250/251/252" but got code "450", with message "450 4.1.0 Please try again in a new SMTP session."."`

Das Versenden über den Contao-Standardweg im Formular und Test über Konsole geht!

Erst nach dem Neuanlegen der Benachrichtigungen war die Fehlermeldung weg.

**Comment by zoglo** [comment]
I guess it'd help if you can provide a dump of the previous settings.

**Comment by aschempp** [comment]
gehe ich richtig dass wir den Fall nicht mehr reproduzieren können, weil du die Notification gelöscht und neu angelegt hast?

**Comment by zonky2** [comment]
leider ja - Agentur war schneller :(
