### ISSUE TITLE
Form Tokens von Feldern, deren Feldname auf "-suffix" o.ä. enden, werden in E-Mails nicht ersetzt!

### ISSUE THREAD

**Issue by bildschirmartist** [terminal42/contao-notification_center#363]
Moin zusammen,
wir haben ein Problem, das seit kurzem auftritt:
Es wurde ein Formular eingerichtet, dass über `notification_center` eine E-Mail generiert und verschickt. Hier sind auch einige Formularfelder enthalten, deren Feldname auf `-suffix` endet. Beispiel:

- `customer-id`
- `product-id`
- `error-message`

Diese werden in den E-Mails aktuell aber nicht ersetzt, stattdessen sieht die generierte E-Mail so aus:
![image](https://github.com/user-attachments/assets/3284fdbe-21f1-47c6-8622-16136cf12f3c)

Als Workaround haben wir die Felder nun wie folgt umbenannt:

- `customerId`
- `productId`
- `errorMessage`

Damit funktioniert es für uns temporär wieder.

Beste Grüße

**Comment by bildschirmartist** [comment]
Kurze Ergänzung: Scheinbar betrifft es sämtliche Formularfelder, die ein `-` im Namen beinhalten

**Comment by fritzmg** [comment]
Isn't this a known limitation of simple tokens? Or do such tokens work outside of the NC?

**Comment by bildschirmartist** [comment]
> Isn't this a known limitation of simple tokens? Or do such tokens work outside of the NC?

Hi @fritzmg,
thanks for your quick response.
Maybe this is a known limitation of simple tokens but it worked at least until v.2.0.9 of NC.
If it is a limitation, then this should be mentioned in the documentation when it comes to the `##form_*##` Simple Token description, because it is a valid form field name.

**Comment by fritzmg** [comment]
It does look like simple tokens with `-` are supported in general:

```php
// outputs "Hello World!"
$this->simpleTokenParser->parse('##foo-bar##', ['foo-bar' => 'Hello World!'])
```

**Comment by fritzmg** [comment]
The change was introduced in https://github.com/terminal42/contao-notification_center/commit/8d4e519eb66e4c8cd48ebf4ecc960a860b22179e

**Comment by fritzmg** [comment]
@Toflar I don't think it is necessary to silently remove the characters from the variable name. It just means you cannot use it for `{if …}` etc. There also won't be any errors if you try.

**Comment by Toflar** [comment]
You cannot have dashes `-` in token names. It's forbidden. That's why the NC normalizes them to `_`.

**Comment by fritzmg** [comment]
@Toflar but you can. `##foo-bar##` will output the content of the token. The only thing that won't work is

```
{if foo-bar …}
```

etc.

And that applies to everywhere in Contao, not just the NC.

**Comment by Toflar** [comment]
Yes, and we want unified tokens otherwise people don't understand why it works in `##` but not in the `{if` statement. In Contao 5, using it in the `{if` statement with a `-` will cause an error. Hence, they are normalized. Just use `_` instead of `-` and continue your day - no need to discuss this further.

**Comment by fritzmg** [comment]
> In Contao 5, using it in the `{if` statement with a `-` will cause an error.

No, I just tried, it does not cause an error.

**Comment by contaoacademy** [comment]
I use the NC as an interface for Digistore. I get fields from Digistore that look like this:

`data-fieldname`

Unfortunately, I have no influence on the field names. However, since the NC normalizes the value to “_”, I can access it, but I would appreciate it if the old option were restored.

**Comment by fritzmg** [comment]
See #363

**Comment by Toflar** [comment]
I have decided to automatically generate both, normalized and original token names in version 2.2.5. This means that `##form_product-id##` should now work again but if you want to use it in comparisons, you'll have to use `{if form_product_id == 42}`.
