### ISSUE TITLE
Anhänge via Tokens aus dem Backend werden nicht angehängt

### ISSUE THREAD

**Issue by marcfunkDE** [terminal42/contao-notification_center#372]
Guten Morgen!

Contao: 4.13.46
NC: 2.0.13

In den Benachrichtigungen gibt es eine Kataloganforderung, die Anhänge anhand des gewählten select-Menüs anhängt.
Dafür wird im Bereich "Dateianhänge via Tokens" folgendes eingetragen: files/holz*****/pdf/##form_katalog1##.pdf

Der Pfad zur Datei ist existent und lässt sich aufrufen. Dennoch wird der Anhang nicht an die Mail angehangen.
Da ich selbst auch Entwickler bin, habe ich ein wenig geforscht und folgendes gefunden:

MailerGateway.php, Zeile 220
`if ($this->isBulkyItemVoucher($parcel, $voucher)) {

     $emailStamp = $emailStamp->withAttachmentVoucher($voucher);
			
}`

Hier findet eine Prüfung "isBulkyItemVoucher" statt - diese schlägt fehl. $voucher enthält allerdings den korrekten Pfad zur Datei.

Testweise habe ich die if-Abfrage einfach deaktiviert, so dass $emailStamp = $emailStamp->withAttachmentVoucher($voucher); einfach ausgeführt wird. Selbst dann werden die Anhänge jedoch nicht angehangen.

Ich stoße jetzt auch an meine Grenzen.
Ziel ist:
Aufgrund des gewählten Wertes im Select-Feld, wird der entsprechende Katalog als PDF angehangen. Das hat bis zum update auf Version 2.0 auch problemlos funktioniert.

**Comment by Toflar** [comment]
Pfade als Anhänge werden in v2 nicht unterstützt. Das Token selbst muss via Bulky Items Logik funktionieren. Warum und wieso ist alles dokumentiert. Siehe auch https://github.com/terminal42/contao-notification_center/issues/342#issuecomment-2290821873

**Comment by marcfunkDE** [comment]
Hallo!

Ich nutze allerdings keine Erweiterung sondern einfach das vorhandene Feld unter Benachrichtigung.
Welchen Weg gibt es denn jetzt eine Datei als Anhang mitzusenden, die beim Formular vorher gewählt wurde?
Die Daten liegen alle stumpf unter files (sind aber 50 verschiedene Kataloge) und nur der gewählte soll an die Mail angehangen werden.

Ich verstehe es jetzt so, dass es mit Bordmitteln nicht mehr möglich ist?

**Comment by Toflar** [comment]
> Ich verstehe es jetzt so, dass es mit Bordmitteln nicht mehr möglich ist?

Die "Dateianhänge via Tokens" waren schon immer so gedacht, dass die Tokens selbst die Anhänge enthalten. Also `##foobar##` enthält die komplette Information zur Datei, nicht nur einen Teilpfad wie im angegebenen Beispiel. Die Konfiguration mit `pfad/zu/##foobar##.pdf` ist nicht mehr möglich, nein. Eben genau weil `##foobar##` auch `./../../../evil/path` oder sowas enthalten könnte und dann ist der Ausbruch aus dem System sehr einfach. Das wäre eine der genannten Gründe im verlinkten Kommentar.
