### ISSUE TITLE
NC 2.2 - Dateiname im Klartext Speichern

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-notification_center#381]
In der Benachrichtigung liefert `##file_item_html_form_feldname##` als Link 
`https://www.domain.de/notifications/download/20241126/efc3be6d-52d3-4569-8ca4-b75391a50b8f?_hash=tlsFbUOWv4YNMb76ZM6ZH6IUoEjJOj2V4cTIno5INPU%3D`
Der Link zum Download funktioniert auch, der Dateiname der heruntergeladen wird ist `efc3be6d-52d3-4569-8ca4-b75391a50b8f` und muss dann von Hand wieder in z.B.: Katalog.pdf umbenannt werden.
Kann das Ganze so angepasst werden, dass beim Download der Dateiname automatisch wieder zum ursprünglichen Dateinamen z.B.: Katalog.pdf wird?

**Comment by fritzmg** [comment]
Can probably be implemented via

```php
$disposition = HeaderUtils::makeDisposition(
    HeaderUtils::DISPOSITION_ATTACHMENT,
    $bulkyItem->getName(),
);

$response->headers->set('Content-Disposition', $disposition);
```

@Toflar wdyt?

**Comment by Schmidty2** [comment]
Danke
