### ISSUE TITLE
1.2.0-RC1 - 3: Insert Tag wird nicht aufgelöst

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-notification_center#44]
Hallo,

ich habe die RC eingespielt - wenn ich im (normalen) E-Mail-Text einen Insert-Tag wie ```{{link::123}}``` einsetze, erscheint in der gesendeten E-Mail nur "Newsletter" - was dem Seitentitel entspräche...

Contao 3.2.14
NC 1.2.0-RC1 3

**Comment by aschempp** [comment]
Hmm, also was soll denn sonst ausgegeben werden? HTML wird halt im Plain-Text natürlich entfernt…

**Comment by xantippe** [comment]
siehe Inserttags 
```
Dieses Tag wird mit einem Link zu einer internen Seite ersetzt (ersetzen Sie * mit der ID oder dem Alias).
```

prima wäre 
```
<a href="http://www.domain.tld/newsletter.html>http://www.domain.tld/newsletter.html</a>
```

**Comment by aschempp** [comment]
Das geht leider nicht. Das Notification Center hat keinen Einfluss auf die InsertTags, sondern auf dem Text wird einfach der HTML-Code entfernt. Du kannst für diesen Fall aber ja einfach `{{link_url::123}}` verwenden.

**Comment by xantippe** [comment]
o.k. werde ich testen...
