### ISSUE TITLE
Member Registration - Perhaps Config Setting for Token ##link## ##domain## missing

### ISSUE THREAD

**Issue by blackbee** [terminal42/contao-notification_center#46]
Hallo zusammen,

vielleicht bin ich auf einen Fehler gestoßen. Und zwar wollte ich die Mitglieder-Registrierung auch über das Notification-Center laufen lassen, da ich dieses sehr praktisch finde.

Dort ist mir aber aufgefallen, dass bei Member Registration die folgenden Tokens nicht funktionieren:
##token##
##domain##

Diese werden zwar in der Datei
..\library\NotificationCenter\ContaoHelper.php in Zeile 55 und folgende gesetzt,

jedoch scheint in der config.php Datei im Array 'member_registration' (ab Zeile 100) diese zu fehlen, sodass ich beim einsetzen im Notification Center die Fehlermeldung bekomme, dass diese nicht unterstützt werden und ich somit die Benachrichtigung nicht speichern kann.

Dies tritt bei Release Version 1.2.0 auf.

Vielleicht kann da jemand mal nachschauen?

**Comment by aschempp** [comment]
@qzminski the mentioned tokens apparently are not in the allowed list of the config file

**Comment by qzminski** [comment]
Fixed in 64667cb.
