### ISSUE TITLE
Anzeige von Datei- und Seitenstruktur-Wähler beim Schließen des Sprachen-Popups

### ISSUE THREAD

**Issue by cepharum** [terminal42/contao-notification_center#47]
In Contao 3.4.0 mit NC 1.2.1 b2:

## Beobachtung

1. Benachrichtigung bearbeiten
2. In der Sprachenliste den Stift zum Bearbeiten neben einer Sprache anklicken.
3. Es erscheint ein Popup zum Konfigurieren der jeweiligen Benachrichtigung. 
4. **Beim Klick auf die dortige Schaltfläche "Speichern und Schließen" bleibt der Popup offen und wechselt zum Datei-Wähler, sogar mit der Option, zum Seitenstruktur-Wähler zurückzukehren.**

## Versuche

1. Benachrichtigung bearbeiten
2. "Sprachen verwalten" anklicken ... Popup mit Sprachenauswahl erscheint
3. Gleiche Sprache wie zuvor über das dortige Stift-Icon bearbeiten
4. "Speichern & Schließen" führt zurück zur Sprachauswahl im Popup ... korrekt.

* Wiederholt man das Vorgehen oben unter "Beobachtung", dann kehrt das Popup bei "Speichern & Schließen" nicht zur Dateiauswahl, sondern zur Sprachenverwaltungsliste wie zuvor unter "Versuche".
* Öffnet man einen Dateiwähler-Popup (hier erprobt mit einem Bild-Content Element in einem Content Slider) und schließt diesen (hier erprobt mit Klick neben den Popup), dann ist fortan wieder die unter "Beobachtung" genannte Folge aktiv.

**Comment by Toflar** [comment]
Das hat ziemlich sicher was mit dem Referer zu tun und hängt mit dem dcaWizard zusammen. Da kann das Notification Center nichts für. Kannst du mal testen ob der Hotfix-Zweig vom dcaWizard dieses Problem behebt? https://github.com/terminal42/contao-dcawizard/tree/hotfix/2.3.1
Wenn ja, würde ich die 2.3.1 dann veröffentlichen.

**Comment by Toflar** [comment]
Feedback?

**Comment by cepharum** [comment]
Ich habe den Hotfix händisch in den Ordner des dcaWizard-Moduls entpackt. Das Problem blieb danach weiterhin bestehen. Erst Dateiwähler in einem CE-Editor geöffnet, dann Prozedere wie oben unter "Beobachtung" abgelaufen und wieder beim Dateiwähler für Bilder gelandet.

**Comment by Toflar** [comment]
Und du hast vorher den Session-Cache gelöscht? (In den Benutzereinstellungen)

**Comment by cepharum** [comment]
Nein, im vorherigen Testlauf nicht. Doch ein erneuter Testlauf jetzt bewirkte, dass ich nicht im zuvor genutzten Dateiwähler landete, sondern die Startseite von Contao im Popup dargestellt wurde.

So oder so funktioniert der Fix in dem Sinne noch nicht. 

Und bevor weiter Patches rumgeschickt werden: Ich habe vor allem aus massivem Mangel an Zeit den Fix bisher nicht erprobt. Wenn sich der Fehler nicht reproduzieren lässt, dann wäre das zwar unschön, aber auch aus meiner Sicht nicht zu ändern. Dann dürfte das Ticket gern ruhen oder abgewiesen werden. IMHO zeigen sich in Contao selbst wohl zu viele derartige Bugs, weil ich nur zu oft über die Funktion "Zurück" auf einzelnen ANsichten des Backends direkt zur Startseite komme ... und das Verhalten beobachte ich seit Erscheinen der Release 3.0 auf verschiedensten Servern zum Betrieb unterschiedlicher Websites. Daher verwundert mich auch das vorliegende Problem nicht ... einem Kunden könnte ich das nicht erklären, außer dass bei Open Source sowas passieren kann.

**Comment by Toflar** [comment]
Okay, dann schliesse ich das Ticket. Auch wenn es mit Open Source absolut überhaupt nichts zu tun hat :D

**Comment by cepharum** [comment]
Open Source insofern, als dass der Kunde nicht direkt dafür zahlt, dass die SW funktioniert.
