### ISSUE TITLE
Feature Request: Benachrichtigung testen

### ISSUE THREAD

**Issue by cepharum** [terminal42/contao-notification_center#48]
Wenn man für die Registrierung von Nutzern Benachrichtungen konfiguriert, kann man diese derzeit nur testen, wenn man alle Schritte der Nutzerregistrierung durchläuft. Vor allem bei zahlreichen Korrekturen ist dies ungemein müßig, weil man jedes Mal einen vorher genutzten Testnutzer löschen muss, dann das Formular neu ausfüllen müssen, dann auf die Benachrichtigung wartet, um zu sehen, was noch korrigiert werden muss.

Wünschenswert wäre eine Testfunktion wie bei den Newslettern.

**Comment by aschempp** [comment]
Da wir wissen welche Tokens vorkommen halte ich das für machbar…=

**Comment by cepharum** [comment]
**machbar** wie in "man kann ruhig immer wieder Nutzer löschen und neu testen" (sofern es nur um Tokens in der Gestaltung geht und auch wirklich jeder Nutzer des Systems immer einen leichten Zugang zur Auswahl bekannter Tokens hat) oder **machbar** wie in "dieser Feature Request ist einfach erfüllbar"?

**Comment by aschempp** [comment]
*machbar* wie "das könnten wir mal bauen wenn wir Zeit finden" ;-)

**Comment by cepharum** [comment]
Klar, ganz im Rhythmus der OSS! (y)

**Comment by jscholtysik** [comment]
+1

**Comment by Tastaturberuf** [comment]
+1

**Comment by Toflar** [comment]
Notification Center 2 is around the corner and will be released very, very soon. On top of that, we are going to be releasing Notification Center Pro, a commercial extension. This one will enhance NC 2 with additional features. One of which will be extremely convenient testing of notifications based on previously sent ones 😊 

So I am closing this.
