### ISSUE TITLE
xml - Datei speichern löscht auszeichnungen

### ISSUE THREAD

**Issue by Hauge** [terminal42/contao-notification_center#50]
Ich möchte gerne eine xml-datei über das NC im Ordner files speichern.
Das fertige Ergebnis sollte mit entsprechenden Auszeichnungen gespeichert werden - also etwa so:
```
<?xml version="1.0" encoding="utf-8" ?>
<data>
<field id="ac_title">Sehr geehrter Herr</field>
<field id="name">xxxxx</field>
<field id="surname">xxxx</field>
<field id="corporation"></field>
<field id="street">xxx</field>
<field id="country">D</field>
<field id="postalcode">12345</field>
<field id="city">xxxxx</field>
<field id="phone">124565</field>
</data>
```
Leider werden vom Notification Center in der Einstellung plain/xml
alle <,/,> gekillt. 
Ich habe das so in die Eingabemaske geschrieben:
```
<field id="name">##form_name##</field>
```
mit dem Ergebnis, dass dies hier in die Datei geschrieben wird:
```
Hauge
```
Das Ergebnis sollte allerdings bei xml ja so etwas sein:
```
<field id="name">Hauge</field>
```

**Comment by Toflar** [comment]
Bitte testen :)

**Comment by Hauge** [comment]
Passt - > Läuft -> DANKE!

**Comment by Toflar** [comment]
Hab's sogar mit CDATA getestet ;) Will's aber noch mal bisschen anpassen. Würde mir dann erlauben nochmal nach einem Test von deiner Seite zu fragen, bevor ich die 1.2.2 veröffentliche. Allerdings nicht in den nächsten 5 Minuten :) Aber du hast ja eine funktionierende Version für dich vorerst :)

**Comment by Hauge** [comment]
jop - > passt, ich kriegs mit und melde mich sobald ichs getestet hab...
Vielen Dank nochmal

**Comment by Toflar** [comment]
So, hab's nochmal angepasst. Das wär jetzt meine fertige Lösung.
Änderungen hier: https://github.com/terminal42/contao-notification_center/commit/e16885e386d896c6487094633fd89c1efdc17dfc
Ganze 1.2.2: https://github.com/terminal42/contao-notification_center/tree/hotfix/1.2.2

**Comment by Hauge** [comment]
Hallo Toflar, also ich hab mir die Ganze runtergeladen > die funktioniert leider nicht
Hätte das Ganze auch nur mit den einzelnen Änderungen versucht, geht leider auch nicht.
Habe diese hier: https://github.com/terminal42/contao-notification_center/blob/623ff16068e4f2e4d5ac3eb8ebf6d9624fa3555e/dca/tl_nc_language.php noch mit rein gepackt, dann scheint es zu funktionieren

**Comment by Toflar** [comment]
Du musst natürlich die gesamten Änderungen testen, nicht nur den einen Commit. Deswegen hab ich ja den Link zur gesamten 1.2.2 gepostet, da ist auch die Änderung in der `tl_nc_language.php` drin :) Hier direkt als ZIP: https://github.com/terminal42/contao-notification_center/archive/hotfix/1.2.2.zip

**Comment by Hauge** [comment]
Ähm, wie gesagt - ich hatte eigentlich zunächst die Ganze runtergeladen und probiert - > ich teste nachher gleich die zip unter deinem Link (wobei das aber die Gleiche url zu sein scheint)...

**Comment by Hauge** [comment]
Nein, Ok - hofix passt - alles gut, danke!

**Comment by Toflar** [comment]
Danke, veröffentlicht als 1.2.2.
