### ISSUE TITLE
Hook beim Versenden einer E-Mail

### ISSUE THREAD

**Issue by 47gn** [terminal42/contao-notification_center#51]
Hallo zusammen,
wäre es möglich einen Hook einzubauen, der jeweils beim Versenden einer E-Mail aufgerufen werden kann? Ich habe es für mich mal so eingebaut:

        // HOOK: add custom logic
        if (isset($GLOBALS['TL_HOOKS']['logNotificationCenterEmail']) && is_array($GLOBALS['TL_HOOKS']['logNotificationCenterEmail']))
        {
            foreach ($GLOBALS['TL_HOOKS']['logNotificationCenterEmail'] as $callback)
            {
                $this->import($callback[0]);
                $this->$callback[0]->$callback[1]($this->recursiveReplaceTokensAndTags($objLanguage->recipients, $arrTokens, static::NO_TAGS|static::NO_BREAKS), $objEmail->from, $arrCc, $arrBcc, $objEmail->subject, $objEmail->text);
            }
        }

Danke an der Stelle für die coole Erweiterung :)

**Comment by aschempp** [comment]
Vielleicht kannst du erklären was du machen willst? Es gibt ja noch andere Versandmöglichkeiten als Email, vielleicht sollte der Hook eher universell sein?

**Comment by 47gn** [comment]
Stimmt :) Ich möchte jeweils beim Versenden einer Mail über das NC einen Logeintrag in einer separaten Tabelle mit Absender-Email, Ziel-Mail und Textinhalt versenden.

**Comment by aschempp** [comment]
Ah. Ich glaub dafür hatten wir mal einen Feature-Branch gebaut, vielleicht weiss @Toflar das noch?

**Comment by Toflar** [comment]
Nein, wir wollten Trigger bauen (bzw. ich will immer noch), aber generelle Hooks für zusätzlichen Code (= nicht modifizierende Hooks) können wir gerne einbauen. Ich frag mich nur wo...In der Notification? Message? Gateway? Alle?

**Comment by 47gn** [comment]
Also ich hab jetzt mal für meinen Anwendungsfall den Hook in die Email.php ab Zeile 140 eingebaut. Das würde mir schon reichen :) Wenn es aber einen besseren universelleren Platz gibt, dann auch gerne da.

**Comment by Toflar** [comment]
Die Email ist aber eine Core-Klasse und die kriegt einen Hook in der 3.5 https://github.com/contao/core/pull/7616

**Comment by 47gn** [comment]
ah okay.... bedeutet, dass NC über die Core-Klasse die Mails versendet und ich mich so eigentlich an den in deinem Link beschriebenen Hook dranhängen kann? Dort steht mir wahrscheinlich auch die komplette Message mit Absender , Empfänger usw. zur Verfügung oder?

**Comment by Toflar** [comment]
Exakt :)

**Comment by 47gn** [comment]
isch bin begeistert :) Dann lass ich das NC komplett in Ruhe, mach ein Contao Update und nehme den Hook. Danke für den Tip!

**Comment by 47gn** [comment]
Hallo :)

So wie ich das hier verstehe https://github.com/contao/core/pull/7616 gibt es nun doch keinen Hook direkt in Contao, oder?

Wenn dem so ist, dann bin ich einfach so frei und frage nochmal nach ob es die Möglichkeit gib einen Hook für mein o.g. Szenario zu bekommen.

Danke schonmal :)

**Comment by Toflar** [comment]
Beim senden jeder einzelnen Message wird https://github.com/terminal42/contao-notification_center/blob/master/library/NotificationCenter/Model/Message.php#L44 ausgeführt :)

**Comment by 47gn** [comment]
Oh :) Ist das neu?

Welche Argumente muss ich dazu in meine Hook-Funktion übergeben?

**Comment by Toflar** [comment]
Wie? Hab dir doch den Code verlinkt, da siehst du ja was du kriegst?

**Comment by 47gn** [comment]
Sorry, jetzt hab ich es gesehen... da waren die Finger schneller beim schreiben wie das Hirn beim Denken :)

Danke dir.. schönen Sonntag noch 👍

**Comment by 47gn** [comment]
Mist.. ich bekomm es doch nicht so einfach hin...

Ich bekomme ja das Message Object, die Tokens, die Sprache und das Gateway Model in den Hook. Wie stelle ich es denn an, aus dem Message-Objekt die tatsächlich versendete Mail heraus zu bekommen? Bzw. am besten Absender, Betreffen, Text.

Ist das ganz simpel oder kompliziert ? :)

**Comment by Toflar** [comment]
Das E-Mail-Gateway kann das per Zufall. Ist halt abhängig vom Gateway. Nur die, die das `MessageDraftFactoryInterface` unterstützen, können einen Draft erstellen :) Aber in deinem Fall müsste es irgendwie so möglich sein:

```php
public function hook($message, $tokens, $language, $gatewayModel)
{
    $gateway = $gatewayModel->getGateway();
    // Du könntest hier auch eben auf MessageDraftFactoryInterface prüfen, aber ein SMS Gateway hätte ja kein Subject oder BCC-Empfänger, deswegen willst du wohl effektiv hier nur die Emails tracken.
    if ($gateway instanceof \NotificationCenter\Gateway\Email) {
        // Das gibt eine Instanz von EmailMessageDraft
        $draft = $gateway->createDraft($message, $tokens, $language);
        $sender = $draft->getSenderEmail();
        $senderName = $draft->getSenderName();
        // etc.
}
```

**Comment by 47gn** [comment]
Es funzt - ein Traum :)

Da in der Anwendung sicher nur E-Mails versendet werden, ist das eigentlich unkritisch. 

Nochmal Daaaaaaanke :)
