### ISSUE TITLE
Verwendung der nc_tokens auch bei email_sender_name und email_sender_adresse

### ISSUE THREAD

**Issue by 47gn** [terminal42/contao-notification_center#52]
Für die beiden oben genannten DCA-Felder kann es je nach Verwendung des Notification Centers praktisch sein, wenn man hier auch auf die Tokens zurückgreifen könnte. Wäre es machbar die beiden Felder entsprechend zu erweitern?

**Comment by Toflar** [comment]
Dagegen haben wir uns bewusst entschieden. Ein Mail-Server wird mit ziemlicher Sicherheit Absender mit fremder Domain als Spam markieren und wir wollen das NC nicht zur Spam-Schleuder umbauen :)

**Comment by aschempp** [comment]
Korrekt wäre vermutlich die Verwendung der Reply-To Feldes für deinen Fall.

**Comment by 47gn** [comment]
ups... stimmt...daran hab ich nicht gedacht :) Das mit dem Reply-To könnte ich mal versuchen...
