### ISSUE TITLE
Checkbox Array Token

### ISSUE THREAD

**Issue by Ainschy** [terminal42/contao-notification_center#53]
Hi,

Es geht um eine Erweiterung in der Classe tl_form: contao-notification_center/classes/tl_form.php

##form_checkboxmenu## liefert bekanntlich keine Ausgabe. Nur mit Angabe des Array Key's wird 'true' in Form einer 1 ausgegeben. Bei der Verwendung in einer Email schwerlich nutzbar.
Die FunKtion flatten habe ich um 3 Zeilen erweitert (sry, mit dem PR komm ich noch nicht zurecht)

    public function flatten($varValue, $strKey, &$arrData)
    {
        if (is_object($varValue)) {
            return;
        } elseif (!is_array($varValue)) {
            $arrData[$strKey] = $varValue;
            return;
        }

        $blnAssoc = array_is_assoc($varValue);
        $arrStr = array(); // eine Array erstellen um die vorhandenen Keys einzusammeln
        foreach ($varValue as $k => $v) {
            if ($blnAssoc && !is_array($v)) {
                $this->flatten($v, $strKey.'_'.$k, $arrData);
            } else {
                $arrData[$strKey.'_'.$v] = '1';
                $arrStr[] = $v; // vorhandene Keys in das Array schreiben
            }
        }
        $arrData[$strKey] = implode(", ", $arrStr); // das "fehlende" Token generieren
    }

$arrData[$strKey] = implode(", ", $arrStr); fügt das bisher fehlende Token hinzu.

Vllt. könnt ihr das so einsetzen.

VG Oliver

**Comment by frontendschlampe** [comment]
funktioniert - gerade getestet unter Contao 3.2.19

**Comment by Toflar** [comment]
Das gibt aber nur eine komma-separierte Liste aller Values zurück?

**Comment by frontendschlampe** [comment]
ah jo

**Comment by Ainschy** [comment]
Kannst natürlich auch ne GLOBALS einsetzten.

Ist mMn die einfachste Lösung.

**Comment by Toflar** [comment]
> Kannst natürlich auch ne GLOBALS einsetzten.

Hä?

**Comment by Ainschy** [comment]
Wenn kein festes Trennzeichen eingesetzt werden soll ", " dann wäre es sinnvoll das Trennzeichen in einer $GLOBALS zu hinterlegen, die dann jeder so anpassen kann wie er es wünscht.

**Comment by Toflar** [comment]
Ach so, ja aber es geht ja nicht darum ob ein Komma oder ein anderes Trennzeichen verwendet wird, sondern darum dass du nur die Values und nicht die Option-Labels kriegst.

**Comment by Ainschy** [comment]
Der HOOK processFormData liefert in den $arrData nur die Values.

**Comment by Toflar** [comment]
Ich weiss, hab ich @frontendschlampe auch schon gesagt :) Was genau möchtest du denn?

**Comment by Ainschy** [comment]
Ich möchte, das bei einem normalen Contao-Formular mit einem Checkbox Menu die ausgewählten Optionen mittels Simple-Token einfügbar sind. Die ausgewählten Option-Labels wären super, stehen aber im Hook nicht zur Verfügung. Daher mein Vorschlag zu mindest die Values zu übergeben. Nicht schön aber ein Anfang.

**Comment by Toflar** [comment]
Implementiert in https://github.com/terminal42/contao-notification_center/commit/9d02574105298a99ec2f72bb1095a9e0eb6794c2.

**Comment by Hauge** [comment]
Problem besteht wieder in 1.2.3 build 2

**Comment by Toflar** [comment]
Das ist kein Problem sondern ein fehlendes Feature, welches auch der 1.3 zugeordnet ist...

**Comment by juju2** [comment]
Hi. Kann es sein, dass das gleiche Problem auch für die Übergabe mehrerer Dateien per simple token im Feld attachment_tokens besteht? Es kann offensichtlich immer nur eine Datei pro token übergeben werden.

Danke und Grüße ans Terminal ;)

**Comment by Toflar** [comment]
Das ist immer noch kein "Problem", das ist einfach im Moment so :) Pro Token, 1 File :)

**Comment by juju2** [comment]
Hi Toflar, so war da ja gar nicht gemeint mit "Problem" ;) Hast Du einen Tipp, wie ich das trotzdem umsetzen könnte? Per Hook scheint auch keine Möglichkeit zu bestehen, die übergebenen Dateien einzubinden. Nochmal Danke!

**Comment by Toflar** [comment]
Wäre mir so ad hoc nichts bekannt.
