### ISSUE TITLE
Ausgabe Bezeichnung bei Checkbox/Radio Buttons

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-notification_center#54]
aktuell wird bei Checkboxes oder Radio Button der Wert in der Mail übermittelt - sinnvoller wäre aber, dass die passende Bezeichnung zum Wert ausgegeben wird

**Comment by aschempp** [comment]
Mit den Werten hast du die Möglichkeit, in deiner Nachricht zu schreiben was du willst.

**Comment by frontendschlampe** [comment]
naja - da hast du schon Recht, aber dann wird die ganze Sache natürlich ganz schön umfangreich (um es mal "milde" Auszudrücken und jedes Mal, wenn ich die Bezeichnung anpasse oder eine hinzufüge, muss ich auch im Notification Center alles anpassen, aber wenn man es direkt ausgeben könnte, würde dieser Schritt wegfallen - vielleicht könntet ihr da nochmal darüber nachdenken ;-)

**Comment by Toflar** [comment]
Ich hab das schon versucht, das geht aber nicht, weil im Hook keine Option-Labels ankommen. Die müsste man manuell aus der DB holen und da ja jeder Entwickler beliebige Form-Felder anbieten kann wird das ziemlich schwierig, da eine universelle Lösung zu bauen.

**Comment by zonky2** [comment]
@frontendschlampe siehe https://github.com/codefog/contao-haste/blob/master/docs/Util/InsertTags.md#forms

``{{options_label::805::##form_rahmenfarbe##}}``
