### ISSUE TITLE
Der Notification Typ überschreibt Texte von Erweiterungen

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-notification_center#55]
Problem ist, dass der Text ['type'] mehrfach verwendet wird. Wenn ich in meiner Erweiterung zusätzliche Benachrichtigungstexte definiere, werden diese vom notification_center überschrieben:
$GLOBALS['TL_LANG']['tl_nc_notification']['type'] = array('Type', 'Please select a type ...');
Die Zeile legt ein neues Array an, ohne bestehende Texte einzubeziehen.
Es hängt davon ab, in welcher Reihenfolge die Texte der Erweiterungen geladen werden.

$GLOBALS['TL_LANG']['tl_nc_notification']['type']['myExtension'] = 'My Extension';
$GLOBALS['TL_LANG']['tl_nc_notification']['type']['myNotification'] = array('My Notification', 'help...');

Lösungsvorschlag:
Verwendet doch einfach für den Feldnamen des Selects nicht ['type'] sondern ['types'], dann wäre ['type'] allein für die Select-Optionen verwendet und alles ist chic.

Gruß, Hagen

**Comment by aschempp** [comment]
Du must in der `autoload.ini` deiner Erweiterung das Notification Center als (optionale) Abhängigkeit definieren.

**Comment by do-while** [comment]
Wie erstelle ich denn eine optionale Abhängigkeit?
In https://contao.org/de/cookbook/3.3/autoloading.html#abhaengigkeiten-definieren ist davon nichts zu lesen.

Das notification_center soll nur vorher geladen werden, wenn es auch installiert und aktiv ist, sonst  kommt die Meldung, dass die Abhängigkeiten nicht aufgelöst werden können.

**Comment by aschempp** [comment]
Kurz gegoogelt… http://contao.ninja/autoloadini-angaben.html

**Comment by do-while** [comment]
Ich hatte auch gegoogelt, offenbar mit den falschen Suchbegriffen.
Danke Dir, an BugBusters Seite habe ich nicht gedacht.
