### ISSUE TITLE
Feature Request: Optionale HTML-Datei anhängen

### ISSUE THREAD

**Issue by Nico0o** [terminal42/contao-notification_center#59]
Es wäre toll wenn man neben dem HTML-Editor auch noch eine HTML-Datei anhängen könnte.
Hätte den Vorteil das man die E-Mail dann auch mit CSS etc. wie ein Newsletter vorbereiten könnte.
Der TinyMCE filtert logischerweise alles raus!

**Comment by aschempp** [comment]
Dazu gibt es in der Notification die Konfiguration eines E-Mail Templates.

**Comment by Nico0o** [comment]
Danke für die schnelle Antwort! 
Das Template kann ich ja nur in der Nachricht angeben, nicht in der Sprachkonfiguration wo der Empfänger etc. eingestellt wird, außerdem möchte ich ja die Rohtext Ansicht zusätzlich hinterlegen.
Sprich Rohtext + E-Mail-Template.
Wenn ich also ein E-Mail-Template hinterlege und in der Sprachkonfiguraion nur Rohtext ankreuze, bekomme ich auch nur den Rohtext aber nicht meine hinterlege Template Datei.

**Comment by aschempp** [comment]
Die HTML-Template-Datei macht bei Rohtext ja auch keinen Sinn. Das Template wird nur für die HTML-Variante benutzt, und alles was sprachabhängig ist sollte in den TinyMCE. Stylesheets sind kaum sprachabhängig…

**Comment by Nico0o** [comment]
Ich glaub ich habe mich ein bisschen unklar ausgedrückt, entschuldigen dafür.
Folgendes Problem habe ich: 
Ich möchte gerne den Rohtext als Fallback verwenden und eine aufbereitete E-Mail mittels dem E-Mail-Template verschicken. Dies funktioniert allerdings nur wenn ich "HTML und Text" in einer bevor erstellten Sprache (z.B. "DE") ankreuze und dann im TinyMCE HTML-Feld mit einem Contao-Inserttag mein zuvor erstelltes E-Mail-Template lade. Das davor ausgewählte E-Mail-Template hat 0 Auswirkung.
