### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-notification_center#60]
gibt es einen und wenn ja, wo finde ich den...?

Dank!

**Comment by aschempp** [comment]
ich glaube aktuell nicht, nur die commits (https://github.com/terminal42/contao-notification_center/commits/master)

Da wir aber erst bei Version 1.1 sind, gab es seit der ersten initialen version ja erst ein release mit neuen Features ;-)

**Comment by aschempp** [comment]
Ausserdem: https://github.com/terminal42/contao-notification_center/releases

**Comment by xantippe** [comment]
Dank!
