### ISSUE TITLE
Keine Zeilenumbrüche bei Textarea in der HTML-Mail

### ISSUE THREAD

**Issue by do-while** [terminal42/contao-notification_center#61]
in der HTML-Mail werden die Zeilenumbrüche aus der Textarea nicht korrekt umgesetzt. Alle Zeilen stehen ohne Umbruch aneinander.

In meinen Augen fehlt hier für die HTML-Mail ein **nl2br()**

**Comment by aschempp** [comment]
Das wäre Aufgabe der Erweiterung, welche Inhalte zuliefert. Bei Isotope haben wir das Beispielsweise bereits behoben: https://github.com/isotope/core/issues/1401

In welchem Fall hattest du das Problem?

**Comment by do-while** [comment]
Hallo Andreas,
das war ganz normal bei "form submission" aus dem Standard-Formulargenerator. Da würde ich nicht immer eingreifen müssen.

**Comment by marebe1602** [comment]
+1 ich bin gerade auch darüber gestolpert. nl2br() wäre fein.

**Comment by Toflar** [comment]
@aschempp Hab's dir zugewiesen, 1.3 ist eh schon eine Weile in RC-Phase und man könnte den Bugfix in die Stable einfliessen lassen.

**Comment by Metis77** [comment]
+1 
Das feature wäre SUPER.

**Comment by aschempp** [comment]
Leider lässt sich das nicht automatisch lösen, da das Notification Center nicht weis woher der Wert kommt. Ich habe die Lösung deshalb als Insert Tag (via `codefog/contao-haste`) eingebaut:

Mittels dem `flag` insert tag können insert tag flags auf beliebige Werte angewendet werden. In diesem Fall also ´{{flag::##form_fieldname##|nl2br}}` um die Zeilenumbrüche in HTML zu erhalten.

Benötigt Notification Center 1.3.1+ und Haste 4.10.0+

**Comment by marebe1602** [comment]
habe gerade die Updates gezogen und getestet.
Funktioniert prima, dankeschön!

**Comment by asaage** [comment]
Für diejenigen, die es hier nochmal her verschlägt:
Alternative Lösung für HTML-Ausgabe mit Umbrüchen ohne Haste ->

```<pre style="font-family: sans-serif">##form_fieldname##</pre>```
scheint ganz gut zu funktionieren / führt bei einigen Mailclients zu Scrollleisten wenn jmd. gar keine Umbrüche setzt

```<div style="white-space-collapse: preserve;">##form_fieldname##</div>```
Der ein oder andere Mailclient wie z.B. Gmail weigert sich.
