### ISSUE TITLE
Mail Template aus Theme Template Ordner

### ISSUE THREAD

**Issue by Nico0o** [terminal42/contao-notification_center#62]
Hi,
wenn man sich ein eigenes mail_* Template anlegt und es anschließend in seinen Theme Template Ordner schiebt es ist nicht in der Benachrichtung Nachricht nicht auswählbar.

**Comment by Toflar** [comment]
Das ist das Contao-Core Standardverhalten. Es gibt dazu aber schon ein Feature-Request: https://github.com/terminal42/contao-notification_center/issues/13
