### ISSUE TITLE
Platzhalter ##recipient_email## wird unter bestimmten Umständen nicht korrekt aufgelöst

### ISSUE THREAD

**Issue by Zwmann** [terminal42/contao-notification_center#64]
Benutzte Versionen:
Contao 3.2.20
notification_centre 1.2.3 Build 2
isotope 2.1.13

Beschreibung:
Problem trat bei einer Bestellbestätigung in isotope auf. Hier sollte der Kunde eine Bestellbestätigung bekommen, daher wurde der Platzhalter ##recipient_email## ins Empfängerfeld eingestellt. Das funktionierte noch in Version 1.1.4 Build 2, in der aktuellen Version kommt die Mail an den Empfänger nicht an.

Fehleranalyse:
Beim Erzeugen der Mail wird die E-Mail-Adresse in der Form *"Lorem Ipsum" <dolor@sit.amet>* in einem assoziativen Array zur Verfügung gestellt. In einem Vorverarbeitungsschritt werden in allen Werten im Array die HTML-Tags eliminiert. Da ein Teil der E-Mail-Adresse in spitze Klammern eingefasst ist (und damit an HTML-Tags erinnert), wird versehentlich ein Teil der E-Mail-Adresse gelöscht. Übrig bleibt _"Lorem Ipsum"_, was natürlich keine gültige E-Mail-Adresse darstellt.

Beteiligte Dateien und Codesnippets:
**system/modules/notification_center/library/NotificationCenter/Util/String.php**
In der Funktion *recursiveReplaceTokensAndTags* wird hier das Array $arr_tokens modifiziert, so dass die ungültige E-Mail-Adresse entsteht:

---
    if ($intTextFlags > 0) {
            $arrTokens = static::convertToText($arrTokens, $intTextFlags);
    }
---

**Vor** dieser Zeile ist 

---
    $arrTokens["recipientEmail"] == "Lorem Ipsum" <dolor@sit.amet>
---

**Nach** dieser Zeile ist 

---
    $arrTokens["recipientEmail"] == "Lorem Ipsum"
---

Der Wert in *$arrTokens["recipientEmail"]* wird später im Code für den Platzhalter ##recipient_email## eingesetzt.

**Comment by Toflar** [comment]
@aschempp can you check that as you wrote the "convert" methods?

**Comment by aschempp** [comment]
I don't have the time to look at that right now, but I'll keep it in my inbox for next month.

**Comment by Toflar** [comment]
*bump*

**Comment by aschempp** [comment]
Wie lautet die E-Mail Adresse, welche du verwendet hat? Es gibt eine explizite Prüfung für dieses Problem, es sieht allerdings so aus als dürfte die TLD nicht länger als 6 Zeichen sein damit es aktuell funktioniert…

**Comment by Zwmann** [comment]
Die E-Mail-Adressen bei mir hier im lokalen Netzwerk sind alle nach dem Schema <account>@<rechner>.localdomain aufgebaut. Somit ist die TLD natürlich länger als 6 Zeichen.

**Comment by qzminski** [comment]
Fixed in https://github.com/codefog/contao-haste/commit/1bfce5703f834aa182839d52d50e4527d0859ccf.

**Comment by aschempp** [comment]
Make sure to adjust minimum dependency of Haste for the 1.4 release.
