### ISSUE TITLE
Platzhalter für "In Datei schreiben" erlauben und ausgeben

### ISSUE THREAD

**Issue by jenda77** [terminal42/contao-notification_center#66]
Hallo, 

es wäre sehr toll, wenn man die Platzhalter von Isotope für die Möglichkeit "In Datei schreiben" verwenden und damit ausgeben könnte, genau wie es bei Mail geht. Oder gibt es dafür eine Lösung? 

Liebe Grüße,
Jan

**Comment by aschempp** [comment]
:+1: aber bitte stell das Ticket direkt bei Isotope (https://github.com/isotope/core).

**Comment by jenda77** [comment]
Gemacht, kannst du das bitte als neue Funktion markieren?

**Comment by aschempp** [comment]
Das mach ich dann schon sobald ich mich wieder um die Isotope-Issues kümmere :-)

**Comment by jenda77** [comment]
Danke. Es wäre natürlich klasse, wenn es schon mit den neusten Versionen 2.3 (isotope) und 1.3 (Benachrichtungszentrum) kommen könnte. Ansonsten würde ich es gerne selber ausprobieren, allerdings weiß ich nicht, ob mir bestimmte Schnittstellen (hooks) zur Verfügung stehen. Gibt es diese?
