### ISSUE TITLE
Simple Token mit Bindestrich

### ISSUE THREAD

**Issue by Nico0o** [terminal42/contao-notification_center#68]
Wenn man Feldnamen mit Bindestrichen verwendet und diese anschließend mit einem Simple Token ausgeben möchte, kommt folgender Fehler:

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 130968 bytes) in/var/www/vhosts/xxx/system/modules/core/library/Contao/InsertTags.php on line 686

Beispiel: Feldname: plz-ort
Simple Token: ##form_plz-ort##
Verwendet in: Sprachen => DE => Rohtext

**Comment by aschempp** [comment]
Entsprechende Feldnamen werden nicht unterstützt, da Simple Tokens intern mit PHP Variabeln arbeiten und dass dann ungültig wär. Du musst deine Felder umbenennen.

**Comment by Nico0o** [comment]
Okay, dachte ich mir schon, wollte es nur durchgeben falls andere das gleiche Problem haben :)

**Comment by Toflar** [comment]
Ja, das tritt immer öfter auf, dass Leute Probleme damit haben. Contao sollte entsprechend eine Exception werfen und nicht einen Fatal Error. Aber ich weiss ehrlich gesagt (habe mir den Code gerade angeschaut) nicht, warum überhaupt ein Memory-Issue auftritt. Ich wüsste auch nicht (man lese den Code) warum ein `-` in einem Simple Token nicht erlaubt sein sollte...

**Comment by k-webdesign** [comment]
Bei mir wird da gar kein Fehler geworfen, es wurde einfach durchgewunken und in der Mail stand dann

Tel (Mobil):
##form_tel-mobile##

**Comment by aschempp** [comment]
We should add a check for invalid tokens (we already have one for known tokens…)

**Comment by Toflar** [comment]
Implemented in 5d0863a200f8e4b5be0b7d2325c4fc364667943b. Nice side benefit: `form_*` is now not allowed anymore either, so people have to think about replacing the `*` with the correct e.g. form field names. :-)

**Comment by timgatzky** [comment]
Hi, aus welchem Grund wurde der Sternchen-Platzhalter entfernt? Der Weg war prima um alle Werte eines Datensatzes zu übergeben, ohne jedes einzelne Feld ausschreiben zu müssen.

**Comment by Toflar** [comment]
Genau so ist es doch noch? Es geht ja nur um die Validierung hier. Die Leute haben z.B. `##fo` getippt und dann `##form_*##` vorgeschlagen erhalten. `*` steht aber als Platzhalter für alle Formularfelder, damit man eben nicht alle übergeben musste. Aber der **User** sollte niemals `##form_*##` in seiner Nachricht verwenden. Sondern eben `##form_feldname##`.

**Comment by timgatzky** [comment]
##member_*## wird  nicht akzeptiert.
![screenshot_1981](https://cloud.githubusercontent.com/assets/970730/23249425/985b8db6-f9a4-11e6-81e2-e38e39318d6d.jpg)

**Comment by Toflar** [comment]
Ja, und genau so soll es sein, weil `member_*` ist kein gültiges Token. Genau dieser Fehler wird dadurch verhindert.

**Comment by timgatzky** [comment]
Den Token definiert man doch selbst. In diesem Fall steht * halt für ALLE

Der Inhalt der Tokens ist doch ohnehin selbst definiert.

Ich hab hier einen Token ##customcatalog_edit_*##, den Inhalt muss ist selbst definiert. Dort kommt als Fließtext alle Feldwerte rein.

Jetzt muss ich mir quasi einen neuen * Sternchenplatzhaler ausdenken z.b. _ALLEFELDER, damit ich diese Funktion wieder habe.

Ich fand das prima, wie es war, da Sternchen auch save war gegenüber Feldnamen

**Comment by Toflar** [comment]
Das entspricht nicht meiner Vorstellung von dem Token. Das `*` steht **überall** sonst für einen Platzhalter den man als User ersetzen muss. Es funktioniert **nirgends** als Platzhalter für "alles". In keinem Core-Benachrichtigungstypen und keinem der x Typen die ich für Kunden programmiert hab. So war das nie gedacht :-) Da musst du dir eine Alternative überlegen, weil das ändere ich nicht. Ich hätte an deiner Stelle ein `member_all` gemacht, was aber natürlich nicht save gegenüber Feldnamen wäre. Ich adde dir auch ein Zeichen, aber nicht das `*`, das hat eine ganz bestimmte Bedeutung.

**Comment by timgatzky** [comment]
Ruhig Blut. :)

Da NC keine automatisierte Logik hier gibt, und man alle Tokens und deren Inhalt eh händisch erstellen muss, wäre der Platzhalter eigentlich egal. Ich habe das Sternchen wie bei einem Regex interpretiert als alles. Egal, nehm ich halt nen Fragezeichen. :)

**Comment by Toflar** [comment]
Ich bin ganz entspannt :-) Ich will nur, dass es sich für den User überall gleich anfühlt. Deswegen soll der `*` als Platzhalter dienen, damit der User weiss, dass er da was ersetzen muss. Fragezeichen klingt gut, oder ein `+`.

**Comment by timgatzky** [comment]
Ok, ist natürlich Ansichtssache. Persönlich repräsentiert das Sternchen für mich immer ALLES. Bei ner SQL Abfrage ist es auch das Sternchen. Das hatte hier gut Sinn gemacht. Das Fragezeichen wäre für mich logisch für eine erwartete Eingabe. Egal...

**Comment by Toflar** [comment]
Naja, es ist halt seit Version 1 so. Sprich die User haben sich wohl über die 3.5 Jahre daran gewöhnt.

**Comment by timgatzky** [comment]
Jau, genau deswegen war ich verwundert, dass es nicht mehr geht.

**Comment by Toflar** [comment]
Eben, weil es über 3.5 Jahre so war, dass der `*` dafür steht, dass der User anstelle des `*` was eingeben muss. Es wurde nur nie validiert.

**Comment by timgatzky** [comment]
Mhh... isotope scheint wohl auch wie ich zu denken. 
So steht es hier in der Readme

form_* => All the order condition from fields

![screenshot_1982](https://cloud.githubusercontent.com/assets/970730/23252245/7be628c4-f9b0-11e6-9c4c-607f54b4ab1c.jpg)

**Comment by Toflar** [comment]
Richtig. `All the order condition form fields`. Das bedeutet wenn du ein Formular mit den Formularfeldern `name` und `vorname` hast, gibt es `form_name` und `form_vorname`. `form_*` gibt es nie.

**Comment by timgatzky** [comment]
Ok, habe ich leider falsch interpretiert die Doku. Liest sich nach alle Felder ausgeben. Hätte viel getippe gespart in ner Mail :). Zack... alle Formfelder, formatiert mit nem Linebreak, bissel wie Rohdaten senden.
Vielleicht reservierst du ein allgemeingültiges Zeiches. 👍

**Comment by aschempp** [comment]
Die Idee eines allgemeinen Zeichens find ich cool, aber es sollte schon nicht * sein. Fragezeichen oder Plus find ich allerdings auch nicht besonders sexy…

**Comment by timgatzky** [comment]
Fragezeichen und Plus, finde ich auch unlogisch. Hast ja hier gelesen... sinnig fand ich das Sternchen und dachte sogar ihr hättet das so vorgesehen.

**Comment by k-webdesign** [comment]
Was wäre mit einem $ ?

**Comment by timgatzky** [comment]
Sonderzeichen sollten eigentlich überhaupt keine Probleme machen. Yanik hat recht oben, auch ein Minus ist kein Problem. Am Ende wird das ein Array-Schlüssel, da ist ein Minus völlig ok. Das rgxp müsste eigentlich keine Sonderzeichen killen, ausser den Umstand, das Tokens ggf. nicht geschlossen wurden / verschachtelt sind.

**Comment by Toflar** [comment]
Es geht nicht darum, was für PHP okay ist sondern was Contao kann. Deswegen darf es auch keine `<>!=` enthalten.

**Comment by aschempp** [comment]
Hmm, ja das Sternchen wär schon irgendwie richtig. Aber es wird bereits anders verwendet, und ich denke eine doppelte Funktion wäre nicht gut. Auch weil das Dropdown keine Hilfe für zwei verschiedene Funktionen anbieten kann.

Ausserdem, egal welches Token wir wählen, es kann auch ein Feld mit Namen "%" geben und damit wäre Token ##form_%## doppelt belegt. Die einzige wirklich sichere Möglichkeit ist ein unabhängiges Token wie ##all_fields##, so machen wir das ja bereits an anderer Stelle.

**Comment by timgatzky** [comment]
Gerade weil Contao in Feldnamen kein * erlaubt, ist es ein wunderbarer Platzhalter für "alle". Mit der Speicherung des Sternchenzeichens in einem Fließtext hat Contao keine Probleme. Auch NC hat super funktioniert, sonst wäre ich ja nie auf die Idee gekommen mit * einen linebreak formatierten Text aller Feldwerte anzubieten. :)
% schluckt Contao auch nicht mehr 👍 . Eigentlich alles, was SQL nicht erlauben würde, wären super Platzhalter :)

**Comment by Toflar** [comment]
Wir können doch nicht einfach das Verhalten von einem `*` ändern, das wäre ja der BC Break des Jahres. Ich fasse zusammen: Für das NC entsteht überhaupt kein Handlungsbedarf. Der `*` war schon immer ein Platzhalter und wird es auch bleiben. Alle anderen Zeichen bis auf diejenigen die reserviert sind für PHP-Comparisons (`<>!=`)  sind erlaubt und jeder Entwickler kann sich selbst sein passendes Zeichen aussuchen oder das Token `form_wieauchimmersuffix` nennen.
