### ISSUE TITLE
Im Sprachmenü "Speichern & Schließen"

### ISSUE THREAD

**Issue by NicolasGoerlach** [terminal42/contao-notification_center#69]
Wenn man im Sprachmenü (Lightbox) einer Benachrichtigung "Speichern & Schließen" klickt landet man in der Dateiverwaltung.

**Comment by Toflar** [comment]
Ja, das ist je nach dem wo du her kommst und unter welchen Umständen du an diesen Punkt gelangst (also je nach Referer). Das haben wir schon zig mal versucht zu lösen, aber das funktioniert einfach nicht zuverlässig. Muss man wohl mit leben :)

**Comment by Nico0o** [comment]
Man könnte den Speicher & Schließen Button einfach rausnehmen, brauch man an dieser Stelle eh nicht da man das Popup so oder so manuell schließen muss, oder?

**Comment by aschempp** [comment]
Der Button wird leider von Contao ausgegeben und kann nicht entfernt werden. Ich schliesse dies mal als "known limitation".
