### ISSUE TITLE
Mehrere Empfänger mit komma getrennt im Simple-Token

### ISSUE THREAD

**Issue by cboelter** [terminal42/contao-notification_center#71]
Ich versuche gerade mehrere Empfänger komma getrennt über einen Simple-Token zu übergeben. Leider wird die E-Mail dann nicht verschickt. Wenn ich die E-Mail Adressen direkt im Notification-Center hinterlege geht es.
Auch wenn ich über den Simple-Token nur eine Adresse übergebe, funktioniert es.

**Comment by Toflar** [comment]
Ein Token sollte auch nur eine E-Mail-Adresse enthalten, meiner Meinung nach.

**Comment by cboelter** [comment]
Dann müsste ich aber, um eine Notification an mehrere zu versenden, viele Textfelder anlegen. Der Core bietet ja auch die Möglichkeit eine E-Mail an beliebig viele Empfänger schicken zu lassen. Mein Anwendungsfall ist gerade der, das ich eine Benachrichtigung an eine beliebige Anzahl von Empfängern schicken möchte. Diese Empfänger sind frei im Backend erfassbar.

**Comment by Toflar** [comment]
Okay, dann müsstest du dir ansehen, ob wir dem NC das beibringen können. Ich habe aktuell keine Zeit dazu, würde mir aber einen Pull Request ansehen.

**Comment by Toflar** [comment]
Closed via #75
