### ISSUE TITLE
problem with insert tags

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-notification_center#73]
I use the following insert tag in a notification with v1.1.4 and Contao 3.2.20:

``` {{env::path}}{{env::referer}} ```

The output in an e-mail is:

``` http://www.my-domain.tld/the-page-where-the-form-is-send-from.html ```

In v1.2.4 and Contao 3.2.21 I use the same insert tag and the out in the e-mail is:

``` http://www.my-domain.tld/http://www.my-domain.tld/the-page-where-the-form-is-send-from.html ```

What's the problem?

**Comment by aschempp** [comment]
This can hardly be related to the notification center, as these insert tags are replaced by the core. It however depends on where the notification is sent (e.g. there might not be a domain for cron jobs).

**Comment by frontendschlampe** [comment]
It seems to be a server configuration problem, but I have to check again. It's not a problem of notification center.
