### ISSUE TITLE
fatal error when token not exist

### ISSUE THREAD

**Issue by gebi84** [terminal42/contao-notification_center#74]
I get following error:
    Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10677 bytes) in /var/www/vhosts/system/modules/core/library/Contao/String.php(521) : eval()'d code on line 1

when i use a token which doesn't exist. for example ##form_foo##

**Comment by Toflar** [comment]
That's Contao default behaviour. It should be fixed there - if even possible.
