### ISSUE TITLE
Erweiterung der Spracheinstellungen für "In Datei schreiben"

### ISSUE THREAD

**Issue by jscholtysik** [terminal42/contao-notification_center#76]
1. Leider gibt es bei den Spracheinstellungen für "In Datei schreiben" bisher nicht die Möglichkeit, beim Dateinamen Datum- und Zeitangaben anhand von Simple Tokens mit anhängen zu können:

Bsp.: 
dateiname --> funktioniert
dateiname_##date## --> funktioniert nicht

Diese Erweiterung des Dateinamen-Feldes würde es dann ermöglichen, eine Datei für jeden Tag mit z.B. allen Kontaktanfragen zu erstellen und per Batchjob in der Nacht z.B. um 00:00 Uhr die komplette Datei vom Vortag abzuholen.

![bildschirmfoto 2015-09-10 um 13 09 28](https://cloud.githubusercontent.com/assets/1425566/9786819/591a21f6-57bd-11e5-9d38-6bdaf1c7ac5c.png)

2. Dateiinhalt 
Hier sollte es ebenso wie bei der Exportfunktion in Contao Leads die Möglichkeit geben, anzugeben, was in der zu schreibenden Datei enthalten sein soll und ob die Kopfdaten auch in die Datei geschrieben werden sollen. Bei Contao Leads gibt es beim Export die Möglichkeiten

- Alle Daten exportieren
- Individueller Export

Analog dazu hier im Notification Center die Punkte
- Alle Daten in Datei schreiben
- Individuelle Daten in Datei schreiben

Bisher gibt es nur folgende Möglichkeiten:
- ##form_*## --> Alle Formular-Felder.
- ##formconfig_*##
- ##admin_email## --> E-Mail-Adresse des aktuellen Seitenadministrator
oder Felder einzeln hinzuzunehmen.

![bildschirmfoto 2015-09-10 um 13 06 41](https://cloud.githubusercontent.com/assets/1425566/9786786/123b4e40-57bd-11e5-839c-18bf52f6a606.png)

**Comment by jenda77** [comment]
+1 

Ich fände auch toll.

**Comment by jscholtysik** [comment]
Leider kann das Dateinamenfeld weder mit Simple Tokens wie z.B. ##date## noch mit Inserttags wie z.B. {{date}} umgeben. Beide Anhänge tauchen dann so wie sie eingegeben sind im Dateinamen auf: Dateiname_##date## oder Dateiname_{{date}}...

**Comment by Toflar** [comment]
Also das mit den Tokens im Dateinamen, meintwegen. Das andere hat absolut nichts mit dem Notification Center zu tun.

**Comment by cliffparnitzky** [comment]
@jscholtysik Was soll der 2. Teil überhaupt bewirken? Da werden doch max. die Daten von einem abgesendeten Formular in der Datei sein. Das kannst doch gestalten wie du willst.

**Comment by jscholtysik** [comment]
@cliffparnitzky und @toflar Um es dem User einfacher zu machen, auszuwählen, welche Daten er in der Datei haben möchte? Vielleicht auch mit einer Kopfzeile?
Die Daten eines Tages sollen ja auch quasi in einer Datei gesammelt und 1x in der Nacht abgeholt werden
Welchen Sinn hätte dann die Funktion "In Datei schreiben" sonst für Euch? Vielleicht sollte die Funktion dann komplett in Contao-Leads integriert werden, denn da gibt es die Auswahl für den Inhalt und die Kopfzeile der Download-Datei ja schon...

**Comment by cliffparnitzky** [comment]
Ich verstehe gar nicht, warum du das Notification Center und Leads vermischt. Da hat doch das eine mit dem anderen erstmal nix zu tun. Wie ich oben schon geschrieben habe, wird pro Formularabsendung eine Datei erzeugt ... beim Export via Leads sind doch X Formularabsendung drin. Bei Leads geht es um Massendaten, hier im NC um einen Datensatz. Insofern muss doch auch keine Funktion von NC nach Leads wandern.

**Comment by jscholtysik** [comment]
Hallo Cliff,

Du scheinst meine Gedanken dahinter nicht zu verstehen. Ich versuche ja zu erklären, dass im NC ALLE Datensätze eines Tages in eine Datei zusammengeführt werden soll(t)en, denn hier wird ja gleich eine Datei erzeugt (die ich dann in der Nacht abholen könnte), aber es sollen dann nur die Felder in der Datei landen, die der Admin auch benötigt. 
Leads kann ja nur auf Anforderung eine Datei erstellen. Also machen beide Erweiterungen nicht zu 100% das, was ich brauche.

Noch einmal:
Notification Center: 
- erstellt laufend eine Datei (optimal: alle Datensätze in einer Datei pro Tag speichern)
- keine Simple Tokens oder Inserttags im Dateinamen möglich
- kann keine vorher selektierten Daten in Datei speichern
Leads:
- erstellt nur auf Anforderung eine Export-Datei
- SimpleTokens können an den Dateinamen angehängt werden
- kann selektierte Daten in Datei speichern

Eine Verschmelzung von NC und Leads würde dann wahrscheinlich alles können...
Die neue Möglichkeit der Queues in den Gateways ist mir hier noch zu unflexibel, da man z.B. nicht definieren kann, dass alle Queue-Einträge exportiert werden sollen.

Ich hoffe, ich habe die Diskrepanzen der beiden Programme etwas verständlich erklärt.

**Comment by cliffparnitzky** [comment]
Hmmm, hat nun wieder nix mit Kopfdaten zu tun, aber naja.

Im Grunde wäre doch eine Option im NC "an Datei anhängen" das richtige ... dann kann man mit dem oben gewünschten Token im Dateinamen für einen Tag eine Datei definieren. Hier wäre dann die getrennte Definition von Kopfdaten und Formulardaten sicher sinnig.

Klingt meiner Meinung nach sinnig und machbar ... solltest du den neues Ticket für aufmachen.

Ggf. wäre auch die Beauftragung bei T42 sinnvoll :wink: .

**Comment by jscholtysik** [comment]
Doch, das mit den Kopfdaten steht doch schon weiter oben, wollte ich nur nicht noch mal durchkauen, gehört für mich aber zu den selektierten Daten mit dazu. Die Daten sollen ja sauber weiterbearbeitet werden können.
Ich hatte mit Andreas schon mal telefoniert bezüglich eines Angebots für eine andere Sache, vielleicht können sie diese Punkte auch darin berücksichtigen.
Jetzt muss ich erst mal versuchen, alles sauber zum Laufen zu bekommen: 
https://github.com/terminal42/contao-notification_center/issues/78

**Comment by aschempp** [comment]
Insert-Tags und Simple-Tokens sind und waren im Dateinamen schon immer möglich. Zur Export-Funktion gibt es mittlerweile auch bereits eine Funktion um Daten an einer Datei anzufügen.

**Comment by jscholtysik** [comment]
Hi Andreas,

dateiname_##date## funktioniert eben nicht, deshalb ja die Anfrage...

**Comment by aschempp** [comment]
Vermutlich weil es kein Token `##date##` gibt? Aber Insert-Tags `{{date}}` zum Beispiel…
