### ISSUE TITLE
Cron binary needs missing include

### ISSUE THREAD

**Issue by seaneble** [terminal42/contao-notification_center#77]
It seems as though the extension is not meant to be used via composer (symlink mode):

    PHP Warning:  require(/…/htdocs/composer/vendor/terminal42/notification_center/bin/../../../initialize.php): failed to open stream: No such file or directory in /…/htdocs/composer/vendor/terminal42/notification_center/bin/queue on line 15

There is a hard dependency for ```system/initialize.php``` which is only present in that location when using the extension within ```system/modules```.

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-notification_center/commit/c5dd4db3f491453d3e9c5367da2edd2af1cc6e91

**Comment by seaneble** [comment]
Thanks a lot! That was a very quick fix.

One note: the path to use the binary does not actually need to be changed, as the file is symlinked. But it never hurts.
