### ISSUE TITLE
Speicherüberlauf beim Absenden eines Formulars

### ISSUE THREAD

**Issue by jscholtysik** [terminal42/contao-notification_center#78]
Quelle im Forum:
https://community.contao.org/de/showthread.php?59101-Notification-Center-Fatal-Error-normaler-Formularversand-funktioniert-aber

Leider haben wir enorme Probleme, NC sauber zum Laufen zu bekommen.
Dies ist der Text aus dem Forum, dort habe ich aber leider noch keine Tipps erhalten, die den Speicherüberlauf erklären könnten... :-( Vielleicht habt Ihr ja noch ein paar Tipps:

Ich versuche gerade in einer Contao 3.4.5 Installation mit Composer 0.15.4 das Notification Center, Contao Leads, Contao MP-Forms und PHPExcel anhand der Konferenz-Unterlagen und des Videos zum Laufen zu bringen. Der Server ist ein Testaccount eines Managed Server L bei Mittwald, auf dem PHP 5.6 und MySQL 5.6 läuft. Das Speicherlimit beträgt 256MB.

Die Erweiterungen haben folgende Releasestände:
- Terminal42/Notification Center: 1.3.0
- Terminal42/Contao-Leads: 1.1.5
- Terminal42/Contao-MP_Forms: 2.0.4
- PHPOffice/PHPExcel: 1.8.1

Dazu habe ich ein Kontaktformular in Contao erstellt.

Wenn ich nun ein Formular ganz normal mit den Contao SMTP Einstellungen per E-Mail versende, kommt eine E-Mail mit den Feldern an. Der Mailversand funktioniert also.

Ich habe nun für den Versand über das Notification Center folgende Einstellungen gemacht:

- Erstellung Standard-E-Mail-Gateway, Name: Mailversand über Contao SMTP
- Erstellung eines Benachrichtigungs-Container, Name: Mailversand Kontakt, Benachrichtigungstyp: Formularübertragung
- Im Benachrichtigungs-Container sind zwei Benachrichtigungen angelegt:

1. Kontaktanfrage für Admin, HTML und Text Modus und folgendem Text in der Sprache Deutsch, die auch Fallback-Sprache ist:

Guten Tag,
eine neue Kontaktanfrage ist eingetroffen.
##form_*##
Viele Grüße.

2. Kontaktanfrage für Interessenten, HTML und Text Modus und folgendem Text in der Sprache Deutsch, die auch Fallback-Sprache ist:

Guten Tag ##form_vorname## ##form_nachname##,
vielen Dank für Ihre Kontaktanfrage.
Im Folgenden sehen Sie noch einmal Ihre eingegebenen Daten:
##form_*##
Viele Grüße.

Beide Benachrichtigungen sollen über das zuvor angelegte Gateway "Mailversand über Contao SMTP" versendet werden und sind auch beide aktiviert.

Im Kontaktformular selbst ist bei Benachrichtigung der Nachrichtigungs-Container "Mailversand Kontakt" ausgewählt.

Sobald ich das Formular dann versende erhalte ich immer ein der folgenden Fehlermeldungen:

PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 2853 bytes) in /html/system/modules/core/library/Contao/String.php(520) : eval()'d code on line 1

oder

PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 2855 bytes) in Unknown on line 0

Ich habe auch schon den Speicher auf dem Managed Server L auf 512MB und 1024MB in der PHP.INI angehoben, die Fehlermeldung ist jedoch immer die gleiche, natürlich angepasst auf die jeweils eingestellte Speichergröße.

**Comment by cliffparnitzky** [comment]
Der Fehler kann nachgestellt werden. Hierbei handelt es sich allerdings eher um eine Benutzerproblem.

Das Token `##form_*##` im HTML Text verwendet, führt zu dem Fehler.

Das ist so aber eben nicht richtig, denn der Stern `*` muss entsprechend ersetzt werden.

@jscholtysik Also die E-Mail Text entsprechend anpassen und noch mal probieren.

**Comment by jscholtysik** [comment]
Hi Cliff,

danke für den Tipp!! Ich dachte, mit ##form_*## kann ich alle Felder auf einmal anzeigen lassen... :-(

Ich habe es gerade noch einmal mit den einzelnen Feldern probiert, funktioniert!!

Vielen Dank!!

**Comment by cliffparnitzky** [comment]
:+1:
