### ISSUE TITLE
Hochgeladene und gespeicherte Dateien aus einem Frontend Formular werden nicht versand

### ISSUE THREAD

**Issue by Ainschy** [terminal42/contao-notification_center#81]
Datei-Upload im Formulargenerater erlaubt die Speicherung der übermittelten Dateien. Diese Einstellung verhindert den Versand über das Notification Center.

Mein Lösungsansatz habe ich in einem PR https://github.com/terminal42/contao-notification_center/pull/80 beschrieben und erfolgreich getestet.

**Comment by aschempp** [comment]
Jeder Pull Request ist auch ein Ticket, das hier ist also unnötig :-)
