### ISSUE TITLE
Namespace classloader is no longer required by autoload directive is still there

### ISSUE THREAD

**Issue by dmolineus** [terminal42/contao-notification_center#82]
After updating my project nothig worked anymore as you have removed the dependency of the namespace classloader this is mainly a great move. Unfortunately you forgot to remove the autoload.ini directive `requires[] = "_autoload"`

**Comment by discordier** [comment]
Seconded, @frontendschlampe ran into the same problem.

**Comment by frontendschlampe** [comment]
meeehhh ...

**Comment by dmolineus** [comment]
@frontendschlampe You're not alone: https://community.contao.org/de/showthread.php?59556-The-module-dependencies-could-not-be-resolved&p=387291#post387291 ;)

**Comment by aschempp** [comment]
Fixed in 8f7797e76a8790dff564c184326466faddcecd85
