### ISSUE TITLE
EIngaben in den Eingabefeldern erhalten

### ISSUE THREAD

**Issue by TheRedTiger** [terminal42/contao-notification_center#89]
Hallo,

wenn ich ein Formular absende und vergessen habe ein Pflichtfeld auszufüllen, wird mir dieses markiert, damit es augefüllt wird. Gleichzeitig werden bei mir immer alle Eingabefelder geleert und ich muss alles neu eingeben.

Gibt es hierfür eine Lösung??

Grüße
Jörg

**Comment by cliffparnitzky** [comment]
Hmmm, das hat doch sicher nix mit dem NC zu tun ... sondern eher mit dem Formular bzw. Formulargenerator ... Solche Fragen sind im Forum deutlich besser aufgehoben.

**Comment by aschempp** [comment]
> Hmmm, das hat doch sicher nix mit dem NC zu tun ... sondern eher mit dem Formular bzw. Formulargenerator ... Solche Fragen sind im Forum deutlich besser aufgehoben.

seh ich auch so.

**Comment by TheRedTiger** [comment]
Sorry. Der Beitrag war hier wirklich falsch.
In welches Forum (Link?) gehören solche Anfragen?

**Comment by aschempp** [comment]
https://community.contao.org
