### ISSUE TITLE
Syntax der token für "Attachments via tokens"

### ISSUE THREAD

**Issue by TheRedTiger** [terminal42/contao-notification_center#90]
Hallo Zusammen,

kann mir jemand sagen wie der token für das Feld "Attachments via tokens" zum anhängen von Dokumenten an eine Mail aussehen muss?!

Mein Feld heißt "Anlage1", Datei speichern ist deaktiviert.

Ich habe es bereits mit **##form_Anlage1##** und **form_Anlage1** versucht, jedoch wird die Datei nicht an die Mail angehangen.

Was genau mache ich falsch???

Besten Dank.
Grüße
Jörg

**Comment by aschempp** [comment]
Für Fragen wende dich bitte an's Community Forum (https://community.contao.org). GitHub ist für Bug-Reports und Feature-Requests.

**Comment by TheRedTiger** [comment]
Ich habe den Fehler gefunden. Dieser hatte jedoch weniger mit meinen tokens zu tun.

In meinen Formularen nutze ich contao-mp_forms und hatte dort die Felder für den Upload auf der dritten Seite von insgesamt vier Seiten untergebracht. Verschiebe ich das Datei-Feld auf die letzte Seite funktioniert es.

Vielleicht lässt sich das in einer zukünftigen Version optimiern??!
