### ISSUE TITLE
crash when missing endtag

### ISSUE THREAD

**Issue by m-vo** [terminal42/contao-notification_center#91]
It took me some time to find out why my site was crashing when trying to send a contao form via the notification center. I found the reason to be a missing end tag in the message body (one inserttag looked like `##form_something` instead of `##form_something##`).

There was no entry in the system log. The displayed php error message pointed to contao's StringUtils class / memory limit exceeded (and to 'Unknown' on another system). 

Maybe the parser could be improved to be more error tolerant. :-) This could also be a problem of a contao function not checking/sanatizing the input. I did not trace it down any further, yet.

**Comment by aschempp** [comment]
This is actually a Contao issue, but we could add a validation to make sure there are no invalid tokens. Also applies to things like `form_field-name` which will result in an invalid PHP variable.

**Comment by Toflar** [comment]
This is already implemented in develop. Also see https://github.com/terminal42/contao-notification_center/issues/68

**Comment by Toflar** [comment]
Should be slightly adjusted again as `-` is now allowed in Contao. Still we should validate for `<>!=*`.

**Comment by Toflar** [comment]
Fixed in c8899909959448bf010023aff0c3548e1f2c49ab.
