### ISSUE TITLE
feature request: handle linebreaks

### ISSUE THREAD

**Issue by m-vo** [terminal42/contao-notification_center#92]
It would be nice, if linebreaks in multiline textfields (form / textarea) are kept (e.g. ``nl2br`` for html) when using such a field in an inserttag.

Is this an unwanted behaviour in any case? (And should it therefore be either optional or better be handled in a hook....)

**Comment by aschempp** [comment]
This has already been discussed in https://github.com/terminal42/contao-notification_center/issues/61

The solution is to use `{{flag::##form_fieldname##|nl2br}}` in your HTML mail markup.

**Comment by m-vo** [comment]
oh, i overlooked this one.
thanks a lot for pointing that out.
