### ISSUE TITLE
wrong context description for attachments via tokens?

### ISSUE THREAD

**Issue by eBlick** [terminal42/contao-notification_center#94]
The "attachement via tokens" feature is supposed to add files to the notifications, that are uploaded with the referred form, isn't it?

If so the german description seems to be buggy:
`$GLOBALS['TL_LANG']['tl_nc_language']['attachment_tokens']['1']    = 'Bitte geben Sie eine <strong>Komma-separierte</strong> Liste der Empfänger in dieses Feld ein. Nutzen Sie die Autovervollständigung um die verfügbaren "Platzhalter" zu sehen. (Beginnen Sie mit ##)';`

Shouldn't it be "Liste von Datei-Tokens" instead of "Liste der Empfänger"?

**Comment by aschempp** [comment]
Ich habe die Korrektur entsprechend vorgenommen, danke für den Hinweis. Die Übersetzungen kommen direkt von www.transifex.com, du kannst dich dort gerne anmelden und Anpassungen übermitteln :-)
