### ISSUE TITLE
Feature Request: Control notification by Date/Time

### ISSUE THREAD

**Issue by eBlick** [terminal42/contao-notification_center#96]
It would be a nice enhancement if the notifications could be controlled by a specific time/date.

Example:
On Weekends our clients want to have the notifications sent to different recipients.

**Comment by Toflar** [comment]
This will be possible in [version 2.0](https://github.com/terminal42/contao-notification_center/discussions/277). I'm closing it because I need to keep track for myself somehow. Once there is a public beta, I'd appreciate some testing :)
