### ISSUE TITLE
Attachment tokens can't contain comma separated paths themselves

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-notification_center#97]
Hi,

I recently had the problem that in a form using notification center we had an attachment field offering to upload more than one file at once. I added a token to the attachment field in notification center message in the backend. Now that token contains multiple filenames separated by comma:

##form_value_attachments## -> files/uploads/1.png,files/uploads/2.png

At the moment, this doesn't work. I wrote a little customization to support that. If you like, you can consider it as a pull request :)

The file is \NotificationCenter\Util\StringUtil:

`

public static function getTokenAttachments($strAttachmentTokens, array $arrTokens)
{
	$arrAttachments = array();

	if ($strAttachmentTokens == '') {
		return $arrAttachments;
	}

	foreach (trimsplit(',', $strAttachmentTokens) as $strToken) {
		if (version_compare(VERSION . '.' . BUILD, '3.5.1', '<')) {
			$strParsedToken = \String::parseSimpleTokens($strToken, $arrTokens);
		} else {
			$strParsedToken = \StringUtil::parseSimpleTokens($strToken, $arrTokens);
		}

		foreach (trimsplit(',', $strParsedToken) as $strFile) {
			$strFileFull = TL_ROOT . '/' . $strFile;

			if (is_file($strFileFull)) {
				$arrAttachments[$strFile] = $strFileFull;
			}
		}
	}

	return $arrAttachments;
}

`

Thanks in advance.

**Comment by qzminski** [comment]
Implemented in a0b4758.

**Comment by Defcon0** [comment]
Awesome :)
