### ISSUE TITLE
Pressing ESC while a token auto completion list ist opened results in data loss

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-notification_center#99]
Hello,

periodically I have data loss in the notification_center because of pressing ESC while a token auto completion list ist opened. I want to close the auto completion list but the whole popup closes resulting in data to be lost :(

It would be great if the list listens for ESC and closes itself before closing the whole popup.

Bye Defcon0

**Comment by aschempp** [comment]
I have had this issue too, but I'm not sure if there's something we can do about it. We would need to prevent the standard popup dialog from closing with the escape button… I think @qzminski implemented that in *dcawizard* for Contao 3?

**Comment by qzminski** [comment]
I have tried to fix that while implementing the initial version of the auto completion list and I was not able to fix it unfortunately. Any PRs or ideas are welcome.

> I think @qzminski implemented that in dcawizard for Contao 3?

No I haven't.

**Comment by aschempp** [comment]
Should be as simple as setting `escClose` to false in SimpleModel (http://www.ericmmartin.com/projects/simplemodal/#options) in dcawizard (https://github.com/terminal42/contao-dcawizard/blob/master/assets/dcawizard.js#L14) ?

Can you test that? I think that's a useful addition to dcawizard in general.

**Comment by qzminski** [comment]
That's a wrong plugin. Contao is using this: http://simplemodal.plasm.it/

But you pointed me in right direction. See https://github.com/terminal42/contao-dcawizard/commit/c19376688f9a1d5930d20dfbc3ab11a84ee0ea62

**Comment by aschempp** [comment]
Thanks, I just released *dcawizard* 2.3.4
